// Code generated by capnpc-go. DO NOT EDIT.

package rpc

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

type RPCRequest capnp.Struct

// RPCRequest_TypeID is the unique identifier for the type RPCRequest.
const RPCRequest_TypeID = 0xdb53774803587639

func NewRPCRequest(s *capnp.Segment) (RPCRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return RPCRequest(st), err
}

func NewRootRPCRequest(s *capnp.Segment) (RPCRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return RPCRequest(st), err
}

func ReadRootRPCRequest(msg *capnp.Message) (RPCRequest, error) {
	root, err := msg.Root()
	return RPCRequest(root.Struct()), err
}

func (s RPCRequest) String() string {
	str, _ := text.Marshal(0xdb53774803587639, capnp.Struct(s))
	return str
}

func (s RPCRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RPCRequest) DecodeFromPtr(p capnp.Ptr) RPCRequest {
	return RPCRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RPCRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s RPCRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RPCRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RPCRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RPCRequest) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s RPCRequest) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RPCRequest) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s RPCRequest) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s RPCRequest) Method() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s RPCRequest) HasMethod() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s RPCRequest) MethodBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s RPCRequest) SetMethod(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s RPCRequest) Payload() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s RPCRequest) HasPayload() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s RPCRequest) SetPayload(v []byte) error {
	return capnp.Struct(s).SetData(2, v)
}

func (s RPCRequest) Metadata() (RPCRequest_KeyValue_List, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return RPCRequest_KeyValue_List(p.List()), err
}

func (s RPCRequest) HasMetadata() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s RPCRequest) SetMetadata(v RPCRequest_KeyValue_List) error {
	return capnp.Struct(s).SetPtr(3, v.ToPtr())
}

// NewMetadata sets the metadata field to a newly
// allocated RPCRequest_KeyValue_List, preferring placement in s's segment.
func (s RPCRequest) NewMetadata(n int32) (RPCRequest_KeyValue_List, error) {
	l, err := NewRPCRequest_KeyValue_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return RPCRequest_KeyValue_List{}, err
	}
	err = capnp.Struct(s).SetPtr(3, l.ToPtr())
	return l, err
}

// RPCRequest_List is a list of RPCRequest.
type RPCRequest_List = capnp.StructList[RPCRequest]

// NewRPCRequest creates a new list of RPCRequest.
func NewRPCRequest_List(s *capnp.Segment, sz int32) (RPCRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[RPCRequest](l), err
}

// RPCRequest_Future is a wrapper for a RPCRequest promised by a client call.
type RPCRequest_Future struct{ *capnp.Future }

func (f RPCRequest_Future) Struct() (RPCRequest, error) {
	p, err := f.Future.Ptr()
	return RPCRequest(p.Struct()), err
}

type RPCRequest_KeyValue capnp.Struct

// RPCRequest_KeyValue_TypeID is the unique identifier for the type RPCRequest_KeyValue.
const RPCRequest_KeyValue_TypeID = 0xedcf580da724a2bf

func NewRPCRequest_KeyValue(s *capnp.Segment) (RPCRequest_KeyValue, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return RPCRequest_KeyValue(st), err
}

func NewRootRPCRequest_KeyValue(s *capnp.Segment) (RPCRequest_KeyValue, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return RPCRequest_KeyValue(st), err
}

func ReadRootRPCRequest_KeyValue(msg *capnp.Message) (RPCRequest_KeyValue, error) {
	root, err := msg.Root()
	return RPCRequest_KeyValue(root.Struct()), err
}

func (s RPCRequest_KeyValue) String() string {
	str, _ := text.Marshal(0xedcf580da724a2bf, capnp.Struct(s))
	return str
}

func (s RPCRequest_KeyValue) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RPCRequest_KeyValue) DecodeFromPtr(p capnp.Ptr) RPCRequest_KeyValue {
	return RPCRequest_KeyValue(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RPCRequest_KeyValue) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s RPCRequest_KeyValue) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RPCRequest_KeyValue) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RPCRequest_KeyValue) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RPCRequest_KeyValue) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s RPCRequest_KeyValue) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RPCRequest_KeyValue) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s RPCRequest_KeyValue) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s RPCRequest_KeyValue) Value() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s RPCRequest_KeyValue) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s RPCRequest_KeyValue) ValueBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s RPCRequest_KeyValue) SetValue(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// RPCRequest_KeyValue_List is a list of RPCRequest_KeyValue.
type RPCRequest_KeyValue_List = capnp.StructList[RPCRequest_KeyValue]

// NewRPCRequest_KeyValue creates a new list of RPCRequest_KeyValue.
func NewRPCRequest_KeyValue_List(s *capnp.Segment, sz int32) (RPCRequest_KeyValue_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[RPCRequest_KeyValue](l), err
}

// RPCRequest_KeyValue_Future is a wrapper for a RPCRequest_KeyValue promised by a client call.
type RPCRequest_KeyValue_Future struct{ *capnp.Future }

func (f RPCRequest_KeyValue_Future) Struct() (RPCRequest_KeyValue, error) {
	p, err := f.Future.Ptr()
	return RPCRequest_KeyValue(p.Struct()), err
}

type RPCResponse capnp.Struct
type RPCResponse_result RPCResponse
type RPCResponse_result_Which uint16

const (
	RPCResponse_result_Which_success RPCResponse_result_Which = 0
	RPCResponse_result_Which_error   RPCResponse_result_Which = 1
)

func (w RPCResponse_result_Which) String() string {
	const s = "successerror"
	switch w {
	case RPCResponse_result_Which_success:
		return s[0:7]
	case RPCResponse_result_Which_error:
		return s[7:12]

	}
	return "RPCResponse_result_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// RPCResponse_TypeID is the unique identifier for the type RPCResponse.
const RPCResponse_TypeID = 0xbbfe56f07c04e004

func NewRPCResponse(s *capnp.Segment) (RPCResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return RPCResponse(st), err
}

func NewRootRPCResponse(s *capnp.Segment) (RPCResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return RPCResponse(st), err
}

func ReadRootRPCResponse(msg *capnp.Message) (RPCResponse, error) {
	root, err := msg.Root()
	return RPCResponse(root.Struct()), err
}

func (s RPCResponse) String() string {
	str, _ := text.Marshal(0xbbfe56f07c04e004, capnp.Struct(s))
	return str
}

func (s RPCResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RPCResponse) DecodeFromPtr(p capnp.Ptr) RPCResponse {
	return RPCResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RPCResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s RPCResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RPCResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RPCResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RPCResponse) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s RPCResponse) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RPCResponse) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s RPCResponse) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s RPCResponse) Result() RPCResponse_result { return RPCResponse_result(s) }

func (s RPCResponse_result) Which() RPCResponse_result_Which {
	return RPCResponse_result_Which(capnp.Struct(s).Uint16(0))
}
func (s RPCResponse_result) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RPCResponse_result) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RPCResponse_result) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RPCResponse_result) Success() ([]byte, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != success")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s RPCResponse_result) HasSuccess() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s RPCResponse_result) SetSuccess(v []byte) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetData(1, v)
}

func (s RPCResponse_result) Error() (RPCError, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != error")
	}
	p, err := capnp.Struct(s).Ptr(1)
	return RPCError(p.Struct()), err
}

func (s RPCResponse_result) HasError() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(1)
}

func (s RPCResponse_result) SetError(v RPCError) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewError sets the error field to a newly
// allocated RPCError struct, preferring placement in s's segment.
func (s RPCResponse_result) NewError() (RPCError, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewRPCError(capnp.Struct(s).Segment())
	if err != nil {
		return RPCError{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s RPCResponse) Metadata() (RPCRequest_KeyValue_List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return RPCRequest_KeyValue_List(p.List()), err
}

func (s RPCResponse) HasMetadata() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s RPCResponse) SetMetadata(v RPCRequest_KeyValue_List) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewMetadata sets the metadata field to a newly
// allocated RPCRequest_KeyValue_List, preferring placement in s's segment.
func (s RPCResponse) NewMetadata(n int32) (RPCRequest_KeyValue_List, error) {
	l, err := NewRPCRequest_KeyValue_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return RPCRequest_KeyValue_List{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}

// RPCResponse_List is a list of RPCResponse.
type RPCResponse_List = capnp.StructList[RPCResponse]

// NewRPCResponse creates a new list of RPCResponse.
func NewRPCResponse_List(s *capnp.Segment, sz int32) (RPCResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[RPCResponse](l), err
}

// RPCResponse_Future is a wrapper for a RPCResponse promised by a client call.
type RPCResponse_Future struct{ *capnp.Future }

func (f RPCResponse_Future) Struct() (RPCResponse, error) {
	p, err := f.Future.Ptr()
	return RPCResponse(p.Struct()), err
}
func (p RPCResponse_Future) Result() RPCResponse_result_Future {
	return RPCResponse_result_Future{p.Future}
}

// RPCResponse_result_Future is a wrapper for a RPCResponse_result promised by a client call.
type RPCResponse_result_Future struct{ *capnp.Future }

func (f RPCResponse_result_Future) Struct() (RPCResponse_result, error) {
	p, err := f.Future.Ptr()
	return RPCResponse_result(p.Struct()), err
}
func (p RPCResponse_result_Future) Error() RPCError_Future {
	return RPCError_Future{Future: p.Future.Field(1, nil)}
}

type RPCError capnp.Struct

// RPCError_TypeID is the unique identifier for the type RPCError.
const RPCError_TypeID = 0x9277fba8e44bc4ae

func NewRPCError(s *capnp.Segment) (RPCError, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return RPCError(st), err
}

func NewRootRPCError(s *capnp.Segment) (RPCError, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return RPCError(st), err
}

func ReadRootRPCError(msg *capnp.Message) (RPCError, error) {
	root, err := msg.Root()
	return RPCError(root.Struct()), err
}

func (s RPCError) String() string {
	str, _ := text.Marshal(0x9277fba8e44bc4ae, capnp.Struct(s))
	return str
}

func (s RPCError) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RPCError) DecodeFromPtr(p capnp.Ptr) RPCError {
	return RPCError(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RPCError) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s RPCError) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RPCError) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RPCError) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RPCError) Code() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s RPCError) SetCode(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s RPCError) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s RPCError) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RPCError) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s RPCError) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s RPCError) Details() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s RPCError) HasDetails() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s RPCError) DetailsBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s RPCError) SetDetails(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// RPCError_List is a list of RPCError.
type RPCError_List = capnp.StructList[RPCError]

// NewRPCError creates a new list of RPCError.
func NewRPCError_List(s *capnp.Segment, sz int32) (RPCError_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[RPCError](l), err
}

// RPCError_Future is a wrapper for a RPCError promised by a client call.
type RPCError_Future struct{ *capnp.Future }

func (f RPCError_Future) Struct() (RPCError, error) {
	p, err := f.Future.Ptr()
	return RPCError(p.Struct()), err
}

type RPCBatch capnp.Struct

// RPCBatch_TypeID is the unique identifier for the type RPCBatch.
const RPCBatch_TypeID = 0x99d9a8473962474c

func NewRPCBatch(s *capnp.Segment) (RPCBatch, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return RPCBatch(st), err
}

func NewRootRPCBatch(s *capnp.Segment) (RPCBatch, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return RPCBatch(st), err
}

func ReadRootRPCBatch(msg *capnp.Message) (RPCBatch, error) {
	root, err := msg.Root()
	return RPCBatch(root.Struct()), err
}

func (s RPCBatch) String() string {
	str, _ := text.Marshal(0x99d9a8473962474c, capnp.Struct(s))
	return str
}

func (s RPCBatch) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RPCBatch) DecodeFromPtr(p capnp.Ptr) RPCBatch {
	return RPCBatch(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RPCBatch) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s RPCBatch) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RPCBatch) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RPCBatch) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RPCBatch) Requests() (RPCRequest_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return RPCRequest_List(p.List()), err
}

func (s RPCBatch) HasRequests() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RPCBatch) SetRequests(v RPCRequest_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewRequests sets the requests field to a newly
// allocated RPCRequest_List, preferring placement in s's segment.
func (s RPCBatch) NewRequests(n int32) (RPCRequest_List, error) {
	l, err := NewRPCRequest_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return RPCRequest_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// RPCBatch_List is a list of RPCBatch.
type RPCBatch_List = capnp.StructList[RPCBatch]

// NewRPCBatch creates a new list of RPCBatch.
func NewRPCBatch_List(s *capnp.Segment, sz int32) (RPCBatch_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[RPCBatch](l), err
}

// RPCBatch_Future is a wrapper for a RPCBatch promised by a client call.
type RPCBatch_Future struct{ *capnp.Future }

func (f RPCBatch_Future) Struct() (RPCBatch, error) {
	p, err := f.Future.Ptr()
	return RPCBatch(p.Struct()), err
}

type RPCBatchResponse capnp.Struct

// RPCBatchResponse_TypeID is the unique identifier for the type RPCBatchResponse.
const RPCBatchResponse_TypeID = 0xc396625f8c8c3dda

func NewRPCBatchResponse(s *capnp.Segment) (RPCBatchResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return RPCBatchResponse(st), err
}

func NewRootRPCBatchResponse(s *capnp.Segment) (RPCBatchResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return RPCBatchResponse(st), err
}

func ReadRootRPCBatchResponse(msg *capnp.Message) (RPCBatchResponse, error) {
	root, err := msg.Root()
	return RPCBatchResponse(root.Struct()), err
}

func (s RPCBatchResponse) String() string {
	str, _ := text.Marshal(0xc396625f8c8c3dda, capnp.Struct(s))
	return str
}

func (s RPCBatchResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RPCBatchResponse) DecodeFromPtr(p capnp.Ptr) RPCBatchResponse {
	return RPCBatchResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RPCBatchResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s RPCBatchResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RPCBatchResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RPCBatchResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RPCBatchResponse) Responses() (RPCResponse_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return RPCResponse_List(p.List()), err
}

func (s RPCBatchResponse) HasResponses() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RPCBatchResponse) SetResponses(v RPCResponse_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewResponses sets the responses field to a newly
// allocated RPCResponse_List, preferring placement in s's segment.
func (s RPCBatchResponse) NewResponses(n int32) (RPCResponse_List, error) {
	l, err := NewRPCResponse_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return RPCResponse_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// RPCBatchResponse_List is a list of RPCBatchResponse.
type RPCBatchResponse_List = capnp.StructList[RPCBatchResponse]

// NewRPCBatchResponse creates a new list of RPCBatchResponse.
func NewRPCBatchResponse_List(s *capnp.Segment, sz int32) (RPCBatchResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[RPCBatchResponse](l), err
}

// RPCBatchResponse_Future is a wrapper for a RPCBatchResponse promised by a client call.
type RPCBatchResponse_Future struct{ *capnp.Future }

func (f RPCBatchResponse_Future) Struct() (RPCBatchResponse, error) {
	p, err := f.Future.Ptr()
	return RPCBatchResponse(p.Struct()), err
}

const schema_b09bba32e59de543 = "x\xda\x94\x93Mh\x13M\x1c\xc6\xff\xcf\xcc\xe6M_" +
	"H\xded\xd9\x96\xf7\x83\xbe\x14\xa4b[lM[/" +
	"\x0dHKj\xe9\xa7\x90\x89Zz\x10\xeav3\x98\xda" +
	"\xa4I\xb3\x9b\x86\x8a\x12\xf4\xe4\xa1'\x0f\x82\x14\x11\xbc" +
	"\xd8\x93\x1f\x88\x17E<\xa8\x07\x0f\xd2s\x15\xa1\x07\x8b" +
	"'\xc1\xab\x88]\x99&\xd9\xa4\xc1\xa2\xbde&\xff\x99" +
	"y\x9e\xdf\xf3l\xe41\x86\xb4\xde\xe0\x06'&\x8e\xfa" +
	"\xfep\xef\xbf\x9a\xfc\xb8\xfe\xadx\x83D+\xe0\x0eo" +
	"\xdf\xde\xee{\xba\xf6\x90|\xccO\xd4\xff\x16]0>" +
	"\xc0Odl\xe2\x01\xc1\x9d\x1a\x9d\x1b\x18]\xdf\xbcE" +
	"zk\xfd\xb0\x9a\xe8_b]0\xae\xaas\xc6\x156" +
	"Hp#\xff\x18Kk-[wHt\x00\xae\xb6\xa5" +
	"]\xfe2\xbd\xf3\x8c\xcer?\x18Q\xff#v\x09\x04" +
	"\xe39+R\xdd\xbf\x0d2\xb8\xba\xf9_\x1e\x83\xd1\xa9" +
	"~\x1a\x87\xb9\x92\xf1\xee\xc4\xea\xea\xec\xdc\xcd\x97?\x93" +
	"\xf1\x84_\x84\xf1fw\xf85W2\x06\x96g\xf8X" +
	"\xf1\xf4\xfb\x86aM\x0d\x7f\xe5Q\x18\x7fj\x7f\x13\x19" +
	"-\xda'\x82\xfb\xe2n\xfb\xbd\xe0\xcc\xc6g\xd2\x8f\xd4" +
	"\x9d,\xd3\xf8\xae]\x83\xa1\xfb\xd4\xcdA_\x91\xba]" +
	"\xdbJ\xc9\x8ci\x1f\xe3E9gg\xad\x05\xe9\xcc\xe6" +
	"sV\x8fe\xe6\x16s\xd1D|x$\x94\xcfg\xf3" +
	"q@\x04\xb8F\xa4\x81H\x1f\xe9\"\x12C\x1cb\x8a" +
	"\x01h\x86\xda\x1b\x8f\x11\x89\x93\x1c\"\xce\xa034+" +
	"<\xfa)\xb59\xc6!\xce0\x84\xaclRB#\x06" +
	"\x8dP\xcaH\xdb6/H\x04\x88!@(%\xa5c" +
	"\xce\xa7\xed\xea\xfa\x97\xb2b!\xd3\xb1RJ\x96\xe6\xc9" +
	"\x0aN\x10\x89\x00\x87\xe8`p\xf3r\xa9 m\xc7&" +
	"\"\xfcE\x88s \\\x83AP\x9b\xde+\xda>\xaf" +
	"$\xa4\x9d\xcb.\xda\xb2g0/\xedB\xda\x11M\\" +
	"ku\xdd\x8a\xe5N\xe5\xae\x9dCD\x18\xfe\xc7\x8e[" +
	"1\xdd\xddG$:8\xc4q\x86\x92]\xb0,i\xdb" +
	"\x08\x12C\x90\xd0&\x15M\x84k\x95% |\x00%" +
	"\xd4\x90\xc4\x7f\xf5I\xa0\xae\xaf\xfax\x94\x98\xceX3" +
	"8\x91\xde\xab\xd0D\xcas|>Y\xc5\\\xb1\xe5f" +
	"\xa4c&M\xc7\xdc\x03\xcb\xab\xd1o\xc2\x8a\xa9D\x94" +
	"\xce\x90\x12\xda\x10MbO4\x15/\xb0k\xafy\x1f" +
	"O\xc3k\xfb\x15 1X\x0eXh\xa8o<&\xdc" +
	"I\xb92m\xa6\x0b\x92\x88D\xd8S`*R\xe78" +
	"D\x8aA\xaf\x96VF\x89\xc4y\x0e\x91V\xa5e\xe5" +
	"\xfc\xe6U\xacI\x0e\x91c\xd09/\x03\xcc(\x80i" +
	"\x0eq}/\xc0\x8ctRYoY\xca\x99+\xe9\xac" +
	"\x99\xac\xc6}0\xb0\xbe}\xb3\xdfu\xda\xe3\x19Sl" +
	"\x9b<g\x9d\x87j5\xf4\x9c\xd5\x97\xd0\xbf W\xaa" +
	"\x0a\xdb\x96\xd5\x0d\xd5\xd5\x8f\x00\x00\x00\xff\xff\xfb\xe1V" +
	"\xfe"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_b09bba32e59de543,
		Nodes: []uint64{
			0x9277fba8e44bc4ae,
			0x99d9a8473962474c,
			0x9fe0159b71131830,
			0xbbfe56f07c04e004,
			0xc396625f8c8c3dda,
			0xdb53774803587639,
			0xedcf580da724a2bf,
		},
		Compressed: true,
	})
}
