// Code generated by capnpc-go. DO NOT EDIT.

package models

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type Message capnp.Struct

// Message_TypeID is the unique identifier for the type Message.
const Message_TypeID = 0xd98357118488407f

func NewMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return Message(st), err
}

func NewRootMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return Message(st), err
}

func ReadRootMessage(msg *capnp.Message) (Message, error) {
	root, err := msg.Root()
	return Message(root.Struct()), err
}

func (s Message) String() string {
	str, _ := text.Marshal(0xd98357118488407f, capnp.Struct(s))
	return str
}

func (s Message) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Message) DecodeFromPtr(p capnp.Ptr) Message {
	return Message(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Message) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Message) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Message) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Message) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Message) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Message) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Message) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Message) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Message) SenderId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Message) HasSenderId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Message) SenderIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Message) SetSenderId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Message) Content() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Message) HasContent() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Message) ContentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Message) SetContent(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Message) Timestamp() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s Message) SetTimestamp(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s Message) RoomId() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Message) HasRoomId() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Message) RoomIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Message) SetRoomId(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

// Message_List is a list of Message.
type Message_List = capnp.StructList[Message]

// NewMessage creates a new list of Message.
func NewMessage_List(s *capnp.Segment, sz int32) (Message_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[Message](l), err
}

// Message_Future is a wrapper for a Message promised by a client call.
type Message_Future struct{ *capnp.Future }

func (f Message_Future) Struct() (Message, error) {
	p, err := f.Future.Ptr()
	return Message(p.Struct()), err
}

type Room capnp.Struct

// Room_TypeID is the unique identifier for the type Room.
const Room_TypeID = 0xc1fb3ff6729701cd

func NewRoom(s *capnp.Segment) (Room, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Room(st), err
}

func NewRootRoom(s *capnp.Segment) (Room, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Room(st), err
}

func ReadRootRoom(msg *capnp.Message) (Room, error) {
	root, err := msg.Root()
	return Room(root.Struct()), err
}

func (s Room) String() string {
	str, _ := text.Marshal(0xc1fb3ff6729701cd, capnp.Struct(s))
	return str
}

func (s Room) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Room) DecodeFromPtr(p capnp.Ptr) Room {
	return Room(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Room) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Room) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Room) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Room) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Room) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Room) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Room) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Room) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Room) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Room) HasName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Room) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Room) SetName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Room) IsPublic() bool {
	return capnp.Struct(s).Bit(0)
}

func (s Room) SetIsPublic(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s Room) Members() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return capnp.TextList(p.List()), err
}

func (s Room) HasMembers() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Room) SetMembers(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewMembers sets the members field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s Room) NewMembers(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}

// Room_List is a list of Room.
type Room_List = capnp.StructList[Room]

// NewRoom creates a new list of Room.
func NewRoom_List(s *capnp.Segment, sz int32) (Room_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[Room](l), err
}

// Room_Future is a wrapper for a Room promised by a client call.
type Room_Future struct{ *capnp.Future }

func (f Room_Future) Struct() (Room, error) {
	p, err := f.Future.Ptr()
	return Room(p.Struct()), err
}

type DirectMessage capnp.Struct

// DirectMessage_TypeID is the unique identifier for the type DirectMessage.
const DirectMessage_TypeID = 0x90a7329ce01298ae

func NewDirectMessage(s *capnp.Segment) (DirectMessage, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return DirectMessage(st), err
}

func NewRootDirectMessage(s *capnp.Segment) (DirectMessage, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return DirectMessage(st), err
}

func ReadRootDirectMessage(msg *capnp.Message) (DirectMessage, error) {
	root, err := msg.Root()
	return DirectMessage(root.Struct()), err
}

func (s DirectMessage) String() string {
	str, _ := text.Marshal(0x90a7329ce01298ae, capnp.Struct(s))
	return str
}

func (s DirectMessage) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (DirectMessage) DecodeFromPtr(p capnp.Ptr) DirectMessage {
	return DirectMessage(capnp.Struct{}.DecodeFromPtr(p))
}

func (s DirectMessage) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s DirectMessage) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s DirectMessage) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s DirectMessage) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s DirectMessage) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s DirectMessage) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s DirectMessage) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s DirectMessage) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s DirectMessage) SenderId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s DirectMessage) HasSenderId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s DirectMessage) SenderIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s DirectMessage) SetSenderId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s DirectMessage) RecipientId() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s DirectMessage) HasRecipientId() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s DirectMessage) RecipientIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s DirectMessage) SetRecipientId(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s DirectMessage) Content() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s DirectMessage) HasContent() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s DirectMessage) ContentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s DirectMessage) SetContent(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s DirectMessage) Timestamp() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s DirectMessage) SetTimestamp(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

// DirectMessage_List is a list of DirectMessage.
type DirectMessage_List = capnp.StructList[DirectMessage]

// NewDirectMessage creates a new list of DirectMessage.
func NewDirectMessage_List(s *capnp.Segment, sz int32) (DirectMessage_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[DirectMessage](l), err
}

// DirectMessage_Future is a wrapper for a DirectMessage promised by a client call.
type DirectMessage_Future struct{ *capnp.Future }

func (f DirectMessage_Future) Struct() (DirectMessage, error) {
	p, err := f.Future.Ptr()
	return DirectMessage(p.Struct()), err
}

const schema_a4bd6cd0c4644fa1 = "x\xda\x9c\x91\xbf\x8b\x13Q\x14\x85\xcfywb\x9au" +
	"uL\xb0\x10%`\xa7\xb0\xfeZl\x16d\xd7E\x8b" +
	"\x15\x82\xb9il,\x9cL\x1e\x9b\x81\xccL\x9c\x19\xc1" +
	"F\xa2\x98\"\xc2\x0a\x11V\xdcb\x0b\x05\xc1\xce\xff\xc0" +
	"B\xb0\x15l\xb5\xb2\xb3\xb7\xb0\xb1\x18yk\xc8\xba\xa2" +
	"(\xdb\xddw9\xefr>\xbes\xab\\\xf1\xce\x1fL" +
	"\x0d\x8c\x1e\xaf\x1c(_o\x1d\xf9\xbc}\xe1\xd5\x04z" +
	"\x94,_\\\xef\xbe\xfb\xd0\x7f\xf3\x12\x15\xaf\x0a,\x9e" +
	"\xe0I\xd6\x16\xe8\xc6Sl\x10,\xdf\xf3Y\xf6m\xf9" +
	"\xfb\xdb\xdf\xe3R\x05jW\xcd\xa7\x9a\x1a75\xcd\x17" +
	"\xb0\x1c\xae\x8cG\xfe\x8d\x87\x1f\xfft\xbbvQ\xbe\xd6" +
	".\xbbo\x8b\x97\xa4A,\x94y\xd8\xb3q\x90\x9f\x95" +
	"\xd8\xe6y\xb0n\xcf\x84\xc1 \x19,]\x892\x1b\x16" +
	"M\x9b\xe7\xd5`\xdd\xb6H\xad\x8b\x07x\x04\xfc{\xc7" +
	"\x00\xbd+\xd4\x91\xa1O\xd6\xe9\x96\x0f\xae\x01z_\xa8" +
	"\x1b\x86\xbe1u\x1a\xc0\x7f\xd4\x01t,\xd4MC_" +
	"\xa4N\x01\xfc'\xab\x80n\x08u\xcb\x90^\x9d\x1e\xe0" +
	"?m\x03\xba)\xd4\xe7\x86\x12u9\x07\xc39\xb0\xcc" +
	"m\xd2\xb5\xd9Z\x17\xc0l\x97\xd90\x1aD6A\xb5" +
	"X\x9b%\x87a\x9a\x146)f\xa9\"\x8am^\x04" +
	"18`\x05\x86\x15wm\xcaj\xf6\xb2\xb6SIc" +
	"\x87xx\x86\x188\xc4\x9bB\xed\xfd\x82hO\x03z" +
	"K\xa8}CN\x09#\x87\xdd\x13j\xe1\x08\xcdO\xc2" +
	"\xdb\x8e\xb0/\xd4\xf1\x1e\x9aCI\x10\xdbY\xc1(o" +
	"\xdd\xe9\xf4\xa3\xd0\xa1\x11\x86\x04\x87\xb1\x8d;6\xcb9" +
	"\x0f\xb6\x84;\xd1\xf9\xbf\xf7n\xda\xc6\xces\xdfv\\" +
	"\xcd\x91P'\x86\x9c\xcay\xdc\xde\x95\xe3{2\xb5\xb3" +
	"\x04\xe8D\xa8\xdb\xff\xb4\xf3?\x1e\x96\xb34\x8dw\xd5" +
	"\xfd\x08\x00\x00\xff\xff\xc3\xc8\xa5\xe0"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_a4bd6cd0c4644fa1,
		Nodes: []uint64{
			0x90a7329ce01298ae,
			0xc1fb3ff6729701cd,
			0xd98357118488407f,
		},
		Compressed: true,
	})
}
