// Code generated by capnpc-go. DO NOT EDIT.

package models

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
)

type Idea capnp.Struct

// Idea_TypeID is the unique identifier for the type Idea.
const Idea_TypeID = 0xb64281c7019dfd62

func NewIdea(s *capnp.Segment) (Idea, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 64, PointerCount: 17})
	return Idea(st), err
}

func NewRootIdea(s *capnp.Segment) (Idea, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 64, PointerCount: 17})
	return Idea(st), err
}

func ReadRootIdea(msg *capnp.Message) (Idea, error) {
	root, err := msg.Root()
	return Idea(root.Struct()), err
}

func (s Idea) String() string {
	str, _ := text.Marshal(0xb64281c7019dfd62, capnp.Struct(s))
	return str
}

func (s Idea) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Idea) DecodeFromPtr(p capnp.Ptr) Idea {
	return Idea(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Idea) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Idea) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Idea) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Idea) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Idea) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Idea) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Idea) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Idea) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Idea) Title() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Idea) HasTitle() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Idea) TitleBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Idea) SetTitle(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Idea) Description() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Idea) HasDescription() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Idea) DescriptionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Idea) SetDescription(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Idea) Summary() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Idea) HasSummary() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Idea) SummaryBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Idea) SetSummary(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Idea) Status() IdeaStatus {
	return IdeaStatus(capnp.Struct(s).Uint16(0))
}

func (s Idea) SetStatus(v IdeaStatus) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s Idea) Stage() IdeaStage {
	return IdeaStage(capnp.Struct(s).Uint16(2))
}

func (s Idea) SetStage(v IdeaStage) {
	capnp.Struct(s).SetUint16(2, uint16(v))
}

func (s Idea) Priority() IdeaPriority {
	return IdeaPriority(capnp.Struct(s).Uint16(4))
}

func (s Idea) SetPriority(v IdeaPriority) {
	capnp.Struct(s).SetUint16(4, uint16(v))
}

func (s Idea) CreatorId() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s Idea) HasCreatorId() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Idea) CreatorIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s Idea) SetCreatorId(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s Idea) ProjectId() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s Idea) HasProjectId() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Idea) ProjectIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s Idea) SetProjectId(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s Idea) AssigneeId() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s Idea) HasAssigneeId() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s Idea) AssigneeIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s Idea) SetAssigneeId(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s Idea) Collaborators() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return capnp.TextList(p.List()), err
}

func (s Idea) HasCollaborators() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s Idea) SetCollaborators(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(7, v.ToPtr())
}

// NewCollaborators sets the collaborators field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s Idea) NewCollaborators(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(7, l.ToPtr())
	return l, err
}
func (s Idea) Content() (IdeaContent, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return IdeaContent(p.Struct()), err
}

func (s Idea) HasContent() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s Idea) SetContent(v IdeaContent) error {
	return capnp.Struct(s).SetPtr(8, capnp.Struct(v).ToPtr())
}

// NewContent sets the content field to a newly
// allocated IdeaContent struct, preferring placement in s's segment.
func (s Idea) NewContent() (IdeaContent, error) {
	ss, err := NewIdeaContent(capnp.Struct(s).Segment())
	if err != nil {
		return IdeaContent{}, err
	}
	err = capnp.Struct(s).SetPtr(8, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Idea) Attachments() (IdeaAttachment_List, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return IdeaAttachment_List(p.List()), err
}

func (s Idea) HasAttachments() bool {
	return capnp.Struct(s).HasPtr(9)
}

func (s Idea) SetAttachments(v IdeaAttachment_List) error {
	return capnp.Struct(s).SetPtr(9, v.ToPtr())
}

// NewAttachments sets the attachments field to a newly
// allocated IdeaAttachment_List, preferring placement in s's segment.
func (s Idea) NewAttachments(n int32) (IdeaAttachment_List, error) {
	l, err := NewIdeaAttachment_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return IdeaAttachment_List{}, err
	}
	err = capnp.Struct(s).SetPtr(9, l.ToPtr())
	return l, err
}
func (s Idea) Tags() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(10)
	return capnp.TextList(p.List()), err
}

func (s Idea) HasTags() bool {
	return capnp.Struct(s).HasPtr(10)
}

func (s Idea) SetTags(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(10, v.ToPtr())
}

// NewTags sets the tags field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s Idea) NewTags(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(10, l.ToPtr())
	return l, err
}
func (s Idea) Feasibility() (IdeaFeasibility, error) {
	p, err := capnp.Struct(s).Ptr(11)
	return IdeaFeasibility(p.Struct()), err
}

func (s Idea) HasFeasibility() bool {
	return capnp.Struct(s).HasPtr(11)
}

func (s Idea) SetFeasibility(v IdeaFeasibility) error {
	return capnp.Struct(s).SetPtr(11, capnp.Struct(v).ToPtr())
}

// NewFeasibility sets the feasibility field to a newly
// allocated IdeaFeasibility struct, preferring placement in s's segment.
func (s Idea) NewFeasibility() (IdeaFeasibility, error) {
	ss, err := NewIdeaFeasibility(capnp.Struct(s).Segment())
	if err != nil {
		return IdeaFeasibility{}, err
	}
	err = capnp.Struct(s).SetPtr(11, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Idea) Impact() (IdeaImpact, error) {
	p, err := capnp.Struct(s).Ptr(12)
	return IdeaImpact(p.Struct()), err
}

func (s Idea) HasImpact() bool {
	return capnp.Struct(s).HasPtr(12)
}

func (s Idea) SetImpact(v IdeaImpact) error {
	return capnp.Struct(s).SetPtr(12, capnp.Struct(v).ToPtr())
}

// NewImpact sets the impact field to a newly
// allocated IdeaImpact struct, preferring placement in s's segment.
func (s Idea) NewImpact() (IdeaImpact, error) {
	ss, err := NewIdeaImpact(capnp.Struct(s).Segment())
	if err != nil {
		return IdeaImpact{}, err
	}
	err = capnp.Struct(s).SetPtr(12, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Idea) Effort() (IdeaEffort, error) {
	p, err := capnp.Struct(s).Ptr(13)
	return IdeaEffort(p.Struct()), err
}

func (s Idea) HasEffort() bool {
	return capnp.Struct(s).HasPtr(13)
}

func (s Idea) SetEffort(v IdeaEffort) error {
	return capnp.Struct(s).SetPtr(13, capnp.Struct(v).ToPtr())
}

// NewEffort sets the effort field to a newly
// allocated IdeaEffort struct, preferring placement in s's segment.
func (s Idea) NewEffort() (IdeaEffort, error) {
	ss, err := NewIdeaEffort(capnp.Struct(s).Segment())
	if err != nil {
		return IdeaEffort{}, err
	}
	err = capnp.Struct(s).SetPtr(13, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Idea) AiInsights() (AIInsights, error) {
	p, err := capnp.Struct(s).Ptr(14)
	return AIInsights(p.Struct()), err
}

func (s Idea) HasAiInsights() bool {
	return capnp.Struct(s).HasPtr(14)
}

func (s Idea) SetAiInsights(v AIInsights) error {
	return capnp.Struct(s).SetPtr(14, capnp.Struct(v).ToPtr())
}

// NewAiInsights sets the aiInsights field to a newly
// allocated AIInsights struct, preferring placement in s's segment.
func (s Idea) NewAiInsights() (AIInsights, error) {
	ss, err := NewAIInsights(capnp.Struct(s).Segment())
	if err != nil {
		return AIInsights{}, err
	}
	err = capnp.Struct(s).SetPtr(14, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Idea) Feedback() (IdeaFeedback_List, error) {
	p, err := capnp.Struct(s).Ptr(15)
	return IdeaFeedback_List(p.List()), err
}

func (s Idea) HasFeedback() bool {
	return capnp.Struct(s).HasPtr(15)
}

func (s Idea) SetFeedback(v IdeaFeedback_List) error {
	return capnp.Struct(s).SetPtr(15, v.ToPtr())
}

// NewFeedback sets the feedback field to a newly
// allocated IdeaFeedback_List, preferring placement in s's segment.
func (s Idea) NewFeedback(n int32) (IdeaFeedback_List, error) {
	l, err := NewIdeaFeedback_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return IdeaFeedback_List{}, err
	}
	err = capnp.Struct(s).SetPtr(15, l.ToPtr())
	return l, err
}
func (s Idea) Votes() (IdeaVotes, error) {
	p, err := capnp.Struct(s).Ptr(16)
	return IdeaVotes(p.Struct()), err
}

func (s Idea) HasVotes() bool {
	return capnp.Struct(s).HasPtr(16)
}

func (s Idea) SetVotes(v IdeaVotes) error {
	return capnp.Struct(s).SetPtr(16, capnp.Struct(v).ToPtr())
}

// NewVotes sets the votes field to a newly
// allocated IdeaVotes struct, preferring placement in s's segment.
func (s Idea) NewVotes() (IdeaVotes, error) {
	ss, err := NewIdeaVotes(capnp.Struct(s).Segment())
	if err != nil {
		return IdeaVotes{}, err
	}
	err = capnp.Struct(s).SetPtr(16, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Idea) DueDate() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s Idea) SetDueDate(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s Idea) StartDate() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s Idea) SetStartDate(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

func (s Idea) CompletedDate() int64 {
	return int64(capnp.Struct(s).Uint64(24))
}

func (s Idea) SetCompletedDate(v int64) {
	capnp.Struct(s).SetUint64(24, uint64(v))
}

func (s Idea) CreatedAt() int64 {
	return int64(capnp.Struct(s).Uint64(32))
}

func (s Idea) SetCreatedAt(v int64) {
	capnp.Struct(s).SetUint64(32, uint64(v))
}

func (s Idea) UpdatedAt() int64 {
	return int64(capnp.Struct(s).Uint64(40))
}

func (s Idea) SetUpdatedAt(v int64) {
	capnp.Struct(s).SetUint64(40, uint64(v))
}

func (s Idea) LastActivity() int64 {
	return int64(capnp.Struct(s).Uint64(48))
}

func (s Idea) SetLastActivity(v int64) {
	capnp.Struct(s).SetUint64(48, uint64(v))
}

func (s Idea) IsArchived() bool {
	return capnp.Struct(s).Bit(48)
}

func (s Idea) SetIsArchived(v bool) {
	capnp.Struct(s).SetBit(48, v)
}

func (s Idea) Version() int32 {
	return int32(capnp.Struct(s).Uint32(56))
}

func (s Idea) SetVersion(v int32) {
	capnp.Struct(s).SetUint32(56, uint32(v))
}

// Idea_List is a list of Idea.
type Idea_List = capnp.StructList[Idea]

// NewIdea creates a new list of Idea.
func NewIdea_List(s *capnp.Segment, sz int32) (Idea_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 64, PointerCount: 17}, sz)
	return capnp.StructList[Idea](l), err
}

// Idea_Future is a wrapper for a Idea promised by a client call.
type Idea_Future struct{ *capnp.Future }

func (f Idea_Future) Struct() (Idea, error) {
	p, err := f.Future.Ptr()
	return Idea(p.Struct()), err
}
func (p Idea_Future) Content() IdeaContent_Future {
	return IdeaContent_Future{Future: p.Future.Field(8, nil)}
}
func (p Idea_Future) Feasibility() IdeaFeasibility_Future {
	return IdeaFeasibility_Future{Future: p.Future.Field(11, nil)}
}
func (p Idea_Future) Impact() IdeaImpact_Future {
	return IdeaImpact_Future{Future: p.Future.Field(12, nil)}
}
func (p Idea_Future) Effort() IdeaEffort_Future {
	return IdeaEffort_Future{Future: p.Future.Field(13, nil)}
}
func (p Idea_Future) AiInsights() AIInsights_Future {
	return AIInsights_Future{Future: p.Future.Field(14, nil)}
}
func (p Idea_Future) Votes() IdeaVotes_Future {
	return IdeaVotes_Future{Future: p.Future.Field(16, nil)}
}

type IdeaStatus uint16

// IdeaStatus_TypeID is the unique identifier for the type IdeaStatus.
const IdeaStatus_TypeID = 0xec893de4c6ff71f9

// Values of IdeaStatus.
const (
	IdeaStatus_draft       IdeaStatus = 0
	IdeaStatus_submitted   IdeaStatus = 1
	IdeaStatus_underReview IdeaStatus = 2
	IdeaStatus_approved    IdeaStatus = 3
	IdeaStatus_inProgress  IdeaStatus = 4
	IdeaStatus_testing     IdeaStatus = 5
	IdeaStatus_completed   IdeaStatus = 6
	IdeaStatus_rejected    IdeaStatus = 7
	IdeaStatus_onHold      IdeaStatus = 8
	IdeaStatus_cancelled   IdeaStatus = 9
)

// String returns the enum's constant name.
func (c IdeaStatus) String() string {
	switch c {
	case IdeaStatus_draft:
		return "draft"
	case IdeaStatus_submitted:
		return "submitted"
	case IdeaStatus_underReview:
		return "underReview"
	case IdeaStatus_approved:
		return "approved"
	case IdeaStatus_inProgress:
		return "inProgress"
	case IdeaStatus_testing:
		return "testing"
	case IdeaStatus_completed:
		return "completed"
	case IdeaStatus_rejected:
		return "rejected"
	case IdeaStatus_onHold:
		return "onHold"
	case IdeaStatus_cancelled:
		return "cancelled"

	default:
		return ""
	}
}

// IdeaStatusFromString returns the enum value with a name,
// or the zero value if there's no such value.
func IdeaStatusFromString(c string) IdeaStatus {
	switch c {
	case "draft":
		return IdeaStatus_draft
	case "submitted":
		return IdeaStatus_submitted
	case "underReview":
		return IdeaStatus_underReview
	case "approved":
		return IdeaStatus_approved
	case "inProgress":
		return IdeaStatus_inProgress
	case "testing":
		return IdeaStatus_testing
	case "completed":
		return IdeaStatus_completed
	case "rejected":
		return IdeaStatus_rejected
	case "onHold":
		return IdeaStatus_onHold
	case "cancelled":
		return IdeaStatus_cancelled

	default:
		return 0
	}
}

type IdeaStatus_List = capnp.EnumList[IdeaStatus]

func NewIdeaStatus_List(s *capnp.Segment, sz int32) (IdeaStatus_List, error) {
	return capnp.NewEnumList[IdeaStatus](s, sz)
}

type IdeaStage uint16

// IdeaStage_TypeID is the unique identifier for the type IdeaStage.
const IdeaStage_TypeID = 0xddce315dbed1cc16

// Values of IdeaStage.
const (
	IdeaStage_ideation    IdeaStage = 0
	IdeaStage_validation  IdeaStage = 1
	IdeaStage_planning    IdeaStage = 2
	IdeaStage_development IdeaStage = 3
	IdeaStage_testing     IdeaStage = 4
	IdeaStage_launch      IdeaStage = 5
	IdeaStage_iteration   IdeaStage = 6
	IdeaStage_maintenance IdeaStage = 7
)

// String returns the enum's constant name.
func (c IdeaStage) String() string {
	switch c {
	case IdeaStage_ideation:
		return "ideation"
	case IdeaStage_validation:
		return "validation"
	case IdeaStage_planning:
		return "planning"
	case IdeaStage_development:
		return "development"
	case IdeaStage_testing:
		return "testing"
	case IdeaStage_launch:
		return "launch"
	case IdeaStage_iteration:
		return "iteration"
	case IdeaStage_maintenance:
		return "maintenance"

	default:
		return ""
	}
}

// IdeaStageFromString returns the enum value with a name,
// or the zero value if there's no such value.
func IdeaStageFromString(c string) IdeaStage {
	switch c {
	case "ideation":
		return IdeaStage_ideation
	case "validation":
		return IdeaStage_validation
	case "planning":
		return IdeaStage_planning
	case "development":
		return IdeaStage_development
	case "testing":
		return IdeaStage_testing
	case "launch":
		return IdeaStage_launch
	case "iteration":
		return IdeaStage_iteration
	case "maintenance":
		return IdeaStage_maintenance

	default:
		return 0
	}
}

type IdeaStage_List = capnp.EnumList[IdeaStage]

func NewIdeaStage_List(s *capnp.Segment, sz int32) (IdeaStage_List, error) {
	return capnp.NewEnumList[IdeaStage](s, sz)
}

type IdeaPriority uint16

// IdeaPriority_TypeID is the unique identifier for the type IdeaPriority.
const IdeaPriority_TypeID = 0xde7e9b6a39a182e6

// Values of IdeaPriority.
const (
	IdeaPriority_low      IdeaPriority = 0
	IdeaPriority_medium   IdeaPriority = 1
	IdeaPriority_high     IdeaPriority = 2
	IdeaPriority_critical IdeaPriority = 3
)

// String returns the enum's constant name.
func (c IdeaPriority) String() string {
	switch c {
	case IdeaPriority_low:
		return "low"
	case IdeaPriority_medium:
		return "medium"
	case IdeaPriority_high:
		return "high"
	case IdeaPriority_critical:
		return "critical"

	default:
		return ""
	}
}

// IdeaPriorityFromString returns the enum value with a name,
// or the zero value if there's no such value.
func IdeaPriorityFromString(c string) IdeaPriority {
	switch c {
	case "low":
		return IdeaPriority_low
	case "medium":
		return IdeaPriority_medium
	case "high":
		return IdeaPriority_high
	case "critical":
		return IdeaPriority_critical

	default:
		return 0
	}
}

type IdeaPriority_List = capnp.EnumList[IdeaPriority]

func NewIdeaPriority_List(s *capnp.Segment, sz int32) (IdeaPriority_List, error) {
	return capnp.NewEnumList[IdeaPriority](s, sz)
}

type IdeaContent capnp.Struct

// IdeaContent_TypeID is the unique identifier for the type IdeaContent.
const IdeaContent_TypeID = 0xa9b86a0451bd5a8a

func NewIdeaContent(s *capnp.Segment) (IdeaContent, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 11})
	return IdeaContent(st), err
}

func NewRootIdeaContent(s *capnp.Segment) (IdeaContent, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 11})
	return IdeaContent(st), err
}

func ReadRootIdeaContent(msg *capnp.Message) (IdeaContent, error) {
	root, err := msg.Root()
	return IdeaContent(root.Struct()), err
}

func (s IdeaContent) String() string {
	str, _ := text.Marshal(0xa9b86a0451bd5a8a, capnp.Struct(s))
	return str
}

func (s IdeaContent) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (IdeaContent) DecodeFromPtr(p capnp.Ptr) IdeaContent {
	return IdeaContent(capnp.Struct{}.DecodeFromPtr(p))
}

func (s IdeaContent) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s IdeaContent) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s IdeaContent) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s IdeaContent) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s IdeaContent) ProblemStatement() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s IdeaContent) HasProblemStatement() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s IdeaContent) ProblemStatementBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s IdeaContent) SetProblemStatement(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s IdeaContent) Solution() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s IdeaContent) HasSolution() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s IdeaContent) SolutionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s IdeaContent) SetSolution(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s IdeaContent) Benefits() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return capnp.TextList(p.List()), err
}

func (s IdeaContent) HasBenefits() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s IdeaContent) SetBenefits(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewBenefits sets the benefits field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s IdeaContent) NewBenefits(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s IdeaContent) Requirements() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return capnp.TextList(p.List()), err
}

func (s IdeaContent) HasRequirements() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s IdeaContent) SetRequirements(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(3, v.ToPtr())
}

// NewRequirements sets the requirements field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s IdeaContent) NewRequirements(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(3, l.ToPtr())
	return l, err
}
func (s IdeaContent) TechnicalApproach() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s IdeaContent) HasTechnicalApproach() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s IdeaContent) TechnicalApproachBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s IdeaContent) SetTechnicalApproach(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s IdeaContent) Resources() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return capnp.TextList(p.List()), err
}

func (s IdeaContent) HasResources() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s IdeaContent) SetResources(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(5, v.ToPtr())
}

// NewResources sets the resources field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s IdeaContent) NewResources(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(5, l.ToPtr())
	return l, err
}
func (s IdeaContent) Timeline() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s IdeaContent) HasTimeline() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s IdeaContent) TimelineBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s IdeaContent) SetTimeline(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s IdeaContent) Risks() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return capnp.TextList(p.List()), err
}

func (s IdeaContent) HasRisks() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s IdeaContent) SetRisks(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(7, v.ToPtr())
}

// NewRisks sets the risks field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s IdeaContent) NewRisks(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(7, l.ToPtr())
	return l, err
}
func (s IdeaContent) Mitigation() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return capnp.TextList(p.List()), err
}

func (s IdeaContent) HasMitigation() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s IdeaContent) SetMitigation(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(8, v.ToPtr())
}

// NewMitigation sets the mitigation field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s IdeaContent) NewMitigation(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(8, l.ToPtr())
	return l, err
}
func (s IdeaContent) References() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return capnp.TextList(p.List()), err
}

func (s IdeaContent) HasReferences() bool {
	return capnp.Struct(s).HasPtr(9)
}

func (s IdeaContent) SetReferences(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(9, v.ToPtr())
}

// NewReferences sets the references field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s IdeaContent) NewReferences(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(9, l.ToPtr())
	return l, err
}
func (s IdeaContent) Notes() (string, error) {
	p, err := capnp.Struct(s).Ptr(10)
	return p.Text(), err
}

func (s IdeaContent) HasNotes() bool {
	return capnp.Struct(s).HasPtr(10)
}

func (s IdeaContent) NotesBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(10)
	return p.TextBytes(), err
}

func (s IdeaContent) SetNotes(v string) error {
	return capnp.Struct(s).SetText(10, v)
}

// IdeaContent_List is a list of IdeaContent.
type IdeaContent_List = capnp.StructList[IdeaContent]

// NewIdeaContent creates a new list of IdeaContent.
func NewIdeaContent_List(s *capnp.Segment, sz int32) (IdeaContent_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 11}, sz)
	return capnp.StructList[IdeaContent](l), err
}

// IdeaContent_Future is a wrapper for a IdeaContent promised by a client call.
type IdeaContent_Future struct{ *capnp.Future }

func (f IdeaContent_Future) Struct() (IdeaContent, error) {
	p, err := f.Future.Ptr()
	return IdeaContent(p.Struct()), err
}

type IdeaAttachment capnp.Struct

// IdeaAttachment_TypeID is the unique identifier for the type IdeaAttachment.
const IdeaAttachment_TypeID = 0xe15a47b1c7942a7f

func NewIdeaAttachment(s *capnp.Segment) (IdeaAttachment, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 6})
	return IdeaAttachment(st), err
}

func NewRootIdeaAttachment(s *capnp.Segment) (IdeaAttachment, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 6})
	return IdeaAttachment(st), err
}

func ReadRootIdeaAttachment(msg *capnp.Message) (IdeaAttachment, error) {
	root, err := msg.Root()
	return IdeaAttachment(root.Struct()), err
}

func (s IdeaAttachment) String() string {
	str, _ := text.Marshal(0xe15a47b1c7942a7f, capnp.Struct(s))
	return str
}

func (s IdeaAttachment) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (IdeaAttachment) DecodeFromPtr(p capnp.Ptr) IdeaAttachment {
	return IdeaAttachment(capnp.Struct{}.DecodeFromPtr(p))
}

func (s IdeaAttachment) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s IdeaAttachment) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s IdeaAttachment) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s IdeaAttachment) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s IdeaAttachment) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s IdeaAttachment) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s IdeaAttachment) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s IdeaAttachment) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s IdeaAttachment) Filename() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s IdeaAttachment) HasFilename() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s IdeaAttachment) FilenameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s IdeaAttachment) SetFilename(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s IdeaAttachment) FileType() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s IdeaAttachment) HasFileType() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s IdeaAttachment) FileTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s IdeaAttachment) SetFileType(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s IdeaAttachment) FileSize() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s IdeaAttachment) SetFileSize(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s IdeaAttachment) Url() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s IdeaAttachment) HasUrl() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s IdeaAttachment) UrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s IdeaAttachment) SetUrl(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s IdeaAttachment) Description() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s IdeaAttachment) HasDescription() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s IdeaAttachment) DescriptionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s IdeaAttachment) SetDescription(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s IdeaAttachment) UploadedBy() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s IdeaAttachment) HasUploadedBy() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s IdeaAttachment) UploadedByBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s IdeaAttachment) SetUploadedBy(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s IdeaAttachment) UploadedAt() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s IdeaAttachment) SetUploadedAt(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

// IdeaAttachment_List is a list of IdeaAttachment.
type IdeaAttachment_List = capnp.StructList[IdeaAttachment]

// NewIdeaAttachment creates a new list of IdeaAttachment.
func NewIdeaAttachment_List(s *capnp.Segment, sz int32) (IdeaAttachment_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 6}, sz)
	return capnp.StructList[IdeaAttachment](l), err
}

// IdeaAttachment_Future is a wrapper for a IdeaAttachment promised by a client call.
type IdeaAttachment_Future struct{ *capnp.Future }

func (f IdeaAttachment_Future) Struct() (IdeaAttachment, error) {
	p, err := f.Future.Ptr()
	return IdeaAttachment(p.Struct()), err
}

type IdeaFeasibility capnp.Struct

// IdeaFeasibility_TypeID is the unique identifier for the type IdeaFeasibility.
const IdeaFeasibility_TypeID = 0xa255dd7919106c0c

func NewIdeaFeasibility(s *capnp.Segment) (IdeaFeasibility, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 2})
	return IdeaFeasibility(st), err
}

func NewRootIdeaFeasibility(s *capnp.Segment) (IdeaFeasibility, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 2})
	return IdeaFeasibility(st), err
}

func ReadRootIdeaFeasibility(msg *capnp.Message) (IdeaFeasibility, error) {
	root, err := msg.Root()
	return IdeaFeasibility(root.Struct()), err
}

func (s IdeaFeasibility) String() string {
	str, _ := text.Marshal(0xa255dd7919106c0c, capnp.Struct(s))
	return str
}

func (s IdeaFeasibility) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (IdeaFeasibility) DecodeFromPtr(p capnp.Ptr) IdeaFeasibility {
	return IdeaFeasibility(capnp.Struct{}.DecodeFromPtr(p))
}

func (s IdeaFeasibility) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s IdeaFeasibility) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s IdeaFeasibility) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s IdeaFeasibility) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s IdeaFeasibility) Technical() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(0))
}

func (s IdeaFeasibility) SetTechnical(v float32) {
	capnp.Struct(s).SetUint32(0, math.Float32bits(v))
}

func (s IdeaFeasibility) Business() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s IdeaFeasibility) SetBusiness(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

func (s IdeaFeasibility) Market() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(8))
}

func (s IdeaFeasibility) SetMarket(v float32) {
	capnp.Struct(s).SetUint32(8, math.Float32bits(v))
}

func (s IdeaFeasibility) Overall() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(12))
}

func (s IdeaFeasibility) SetOverall(v float32) {
	capnp.Struct(s).SetUint32(12, math.Float32bits(v))
}

func (s IdeaFeasibility) AssessedBy() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s IdeaFeasibility) HasAssessedBy() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s IdeaFeasibility) AssessedByBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s IdeaFeasibility) SetAssessedBy(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s IdeaFeasibility) AssessedAt() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s IdeaFeasibility) SetAssessedAt(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

func (s IdeaFeasibility) Notes() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s IdeaFeasibility) HasNotes() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s IdeaFeasibility) NotesBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s IdeaFeasibility) SetNotes(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// IdeaFeasibility_List is a list of IdeaFeasibility.
type IdeaFeasibility_List = capnp.StructList[IdeaFeasibility]

// NewIdeaFeasibility creates a new list of IdeaFeasibility.
func NewIdeaFeasibility_List(s *capnp.Segment, sz int32) (IdeaFeasibility_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 2}, sz)
	return capnp.StructList[IdeaFeasibility](l), err
}

// IdeaFeasibility_Future is a wrapper for a IdeaFeasibility promised by a client call.
type IdeaFeasibility_Future struct{ *capnp.Future }

func (f IdeaFeasibility_Future) Struct() (IdeaFeasibility, error) {
	p, err := f.Future.Ptr()
	return IdeaFeasibility(p.Struct()), err
}

type IdeaImpact capnp.Struct

// IdeaImpact_TypeID is the unique identifier for the type IdeaImpact.
const IdeaImpact_TypeID = 0xec606f3b72f718f7

func NewIdeaImpact(s *capnp.Segment) (IdeaImpact, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 2})
	return IdeaImpact(st), err
}

func NewRootIdeaImpact(s *capnp.Segment) (IdeaImpact, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 2})
	return IdeaImpact(st), err
}

func ReadRootIdeaImpact(msg *capnp.Message) (IdeaImpact, error) {
	root, err := msg.Root()
	return IdeaImpact(root.Struct()), err
}

func (s IdeaImpact) String() string {
	str, _ := text.Marshal(0xec606f3b72f718f7, capnp.Struct(s))
	return str
}

func (s IdeaImpact) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (IdeaImpact) DecodeFromPtr(p capnp.Ptr) IdeaImpact {
	return IdeaImpact(capnp.Struct{}.DecodeFromPtr(p))
}

func (s IdeaImpact) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s IdeaImpact) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s IdeaImpact) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s IdeaImpact) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s IdeaImpact) Revenue() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(0))
}

func (s IdeaImpact) SetRevenue(v float32) {
	capnp.Struct(s).SetUint32(0, math.Float32bits(v))
}

func (s IdeaImpact) Users() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s IdeaImpact) SetUsers(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

func (s IdeaImpact) Efficiency() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(8))
}

func (s IdeaImpact) SetEfficiency(v float32) {
	capnp.Struct(s).SetUint32(8, math.Float32bits(v))
}

func (s IdeaImpact) Innovation() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(12))
}

func (s IdeaImpact) SetInnovation(v float32) {
	capnp.Struct(s).SetUint32(12, math.Float32bits(v))
}

func (s IdeaImpact) Overall() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(16))
}

func (s IdeaImpact) SetOverall(v float32) {
	capnp.Struct(s).SetUint32(16, math.Float32bits(v))
}

func (s IdeaImpact) AssessedBy() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s IdeaImpact) HasAssessedBy() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s IdeaImpact) AssessedByBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s IdeaImpact) SetAssessedBy(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s IdeaImpact) AssessedAt() int64 {
	return int64(capnp.Struct(s).Uint64(24))
}

func (s IdeaImpact) SetAssessedAt(v int64) {
	capnp.Struct(s).SetUint64(24, uint64(v))
}

func (s IdeaImpact) Notes() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s IdeaImpact) HasNotes() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s IdeaImpact) NotesBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s IdeaImpact) SetNotes(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// IdeaImpact_List is a list of IdeaImpact.
type IdeaImpact_List = capnp.StructList[IdeaImpact]

// NewIdeaImpact creates a new list of IdeaImpact.
func NewIdeaImpact_List(s *capnp.Segment, sz int32) (IdeaImpact_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 2}, sz)
	return capnp.StructList[IdeaImpact](l), err
}

// IdeaImpact_Future is a wrapper for a IdeaImpact promised by a client call.
type IdeaImpact_Future struct{ *capnp.Future }

func (f IdeaImpact_Future) Struct() (IdeaImpact, error) {
	p, err := f.Future.Ptr()
	return IdeaImpact(p.Struct()), err
}

type IdeaEffort capnp.Struct

// IdeaEffort_TypeID is the unique identifier for the type IdeaEffort.
const IdeaEffort_TypeID = 0xcc1bd4705f3bd585

func NewIdeaEffort(s *capnp.Segment) (IdeaEffort, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 2})
	return IdeaEffort(st), err
}

func NewRootIdeaEffort(s *capnp.Segment) (IdeaEffort, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 2})
	return IdeaEffort(st), err
}

func ReadRootIdeaEffort(msg *capnp.Message) (IdeaEffort, error) {
	root, err := msg.Root()
	return IdeaEffort(root.Struct()), err
}

func (s IdeaEffort) String() string {
	str, _ := text.Marshal(0xcc1bd4705f3bd585, capnp.Struct(s))
	return str
}

func (s IdeaEffort) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (IdeaEffort) DecodeFromPtr(p capnp.Ptr) IdeaEffort {
	return IdeaEffort(capnp.Struct{}.DecodeFromPtr(p))
}

func (s IdeaEffort) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s IdeaEffort) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s IdeaEffort) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s IdeaEffort) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s IdeaEffort) Complexity() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(0))
}

func (s IdeaEffort) SetComplexity(v float32) {
	capnp.Struct(s).SetUint32(0, math.Float32bits(v))
}

func (s IdeaEffort) TimeEstimate() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s IdeaEffort) SetTimeEstimate(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

func (s IdeaEffort) TeamSize() int32 {
	return int32(capnp.Struct(s).Uint32(8))
}

func (s IdeaEffort) SetTeamSize(v int32) {
	capnp.Struct(s).SetUint32(8, uint32(v))
}

func (s IdeaEffort) SkillLevel() SkillLevel {
	return SkillLevel(capnp.Struct(s).Uint16(12))
}

func (s IdeaEffort) SetSkillLevel(v SkillLevel) {
	capnp.Struct(s).SetUint16(12, uint16(v))
}

func (s IdeaEffort) EstimatedBy() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s IdeaEffort) HasEstimatedBy() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s IdeaEffort) EstimatedByBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s IdeaEffort) SetEstimatedBy(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s IdeaEffort) EstimatedAt() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s IdeaEffort) SetEstimatedAt(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

func (s IdeaEffort) Notes() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s IdeaEffort) HasNotes() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s IdeaEffort) NotesBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s IdeaEffort) SetNotes(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// IdeaEffort_List is a list of IdeaEffort.
type IdeaEffort_List = capnp.StructList[IdeaEffort]

// NewIdeaEffort creates a new list of IdeaEffort.
func NewIdeaEffort_List(s *capnp.Segment, sz int32) (IdeaEffort_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 2}, sz)
	return capnp.StructList[IdeaEffort](l), err
}

// IdeaEffort_Future is a wrapper for a IdeaEffort promised by a client call.
type IdeaEffort_Future struct{ *capnp.Future }

func (f IdeaEffort_Future) Struct() (IdeaEffort, error) {
	p, err := f.Future.Ptr()
	return IdeaEffort(p.Struct()), err
}

type SkillLevel uint16

// SkillLevel_TypeID is the unique identifier for the type SkillLevel.
const SkillLevel_TypeID = 0x89491628c64b1814

// Values of SkillLevel.
const (
	SkillLevel_junior       SkillLevel = 0
	SkillLevel_intermediate SkillLevel = 1
	SkillLevel_senior       SkillLevel = 2
	SkillLevel_expert       SkillLevel = 3
)

// String returns the enum's constant name.
func (c SkillLevel) String() string {
	switch c {
	case SkillLevel_junior:
		return "junior"
	case SkillLevel_intermediate:
		return "intermediate"
	case SkillLevel_senior:
		return "senior"
	case SkillLevel_expert:
		return "expert"

	default:
		return ""
	}
}

// SkillLevelFromString returns the enum value with a name,
// or the zero value if there's no such value.
func SkillLevelFromString(c string) SkillLevel {
	switch c {
	case "junior":
		return SkillLevel_junior
	case "intermediate":
		return SkillLevel_intermediate
	case "senior":
		return SkillLevel_senior
	case "expert":
		return SkillLevel_expert

	default:
		return 0
	}
}

type SkillLevel_List = capnp.EnumList[SkillLevel]

func NewSkillLevel_List(s *capnp.Segment, sz int32) (SkillLevel_List, error) {
	return capnp.NewEnumList[SkillLevel](s, sz)
}

type AIInsights capnp.Struct

// AIInsights_TypeID is the unique identifier for the type AIInsights.
const AIInsights_TypeID = 0xc17c3b2d936938c3

func NewAIInsights(s *capnp.Segment) (AIInsights, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 11})
	return AIInsights(st), err
}

func NewRootAIInsights(s *capnp.Segment) (AIInsights, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 11})
	return AIInsights(st), err
}

func ReadRootAIInsights(msg *capnp.Message) (AIInsights, error) {
	root, err := msg.Root()
	return AIInsights(root.Struct()), err
}

func (s AIInsights) String() string {
	str, _ := text.Marshal(0xc17c3b2d936938c3, capnp.Struct(s))
	return str
}

func (s AIInsights) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AIInsights) DecodeFromPtr(p capnp.Ptr) AIInsights {
	return AIInsights(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AIInsights) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AIInsights) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AIInsights) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AIInsights) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AIInsights) SimilarIdeas() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s AIInsights) HasSimilarIdeas() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AIInsights) SetSimilarIdeas(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewSimilarIdeas sets the similarIdeas field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s AIInsights) NewSimilarIdeas(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s AIInsights) RelatedProjects() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.TextList(p.List()), err
}

func (s AIInsights) HasRelatedProjects() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s AIInsights) SetRelatedProjects(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewRelatedProjects sets the relatedProjects field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s AIInsights) NewRelatedProjects(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s AIInsights) SuggestedTags() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return capnp.TextList(p.List()), err
}

func (s AIInsights) HasSuggestedTags() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s AIInsights) SetSuggestedTags(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewSuggestedTags sets the suggestedTags field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s AIInsights) NewSuggestedTags(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s AIInsights) MarketTrends() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return capnp.TextList(p.List()), err
}

func (s AIInsights) HasMarketTrends() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s AIInsights) SetMarketTrends(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(3, v.ToPtr())
}

// NewMarketTrends sets the marketTrends field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s AIInsights) NewMarketTrends(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(3, l.ToPtr())
	return l, err
}
func (s AIInsights) CompetitorAnalysis() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s AIInsights) HasCompetitorAnalysis() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s AIInsights) CompetitorAnalysisBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s AIInsights) SetCompetitorAnalysis(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s AIInsights) TechnicalChallenges() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return capnp.TextList(p.List()), err
}

func (s AIInsights) HasTechnicalChallenges() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s AIInsights) SetTechnicalChallenges(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(5, v.ToPtr())
}

// NewTechnicalChallenges sets the technicalChallenges field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s AIInsights) NewTechnicalChallenges(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(5, l.ToPtr())
	return l, err
}
func (s AIInsights) SuggestedApproaches() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return capnp.TextList(p.List()), err
}

func (s AIInsights) HasSuggestedApproaches() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s AIInsights) SetSuggestedApproaches(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(6, v.ToPtr())
}

// NewSuggestedApproaches sets the suggestedApproaches field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s AIInsights) NewSuggestedApproaches(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(6, l.ToPtr())
	return l, err
}
func (s AIInsights) RequiredSkills() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return capnp.TextList(p.List()), err
}

func (s AIInsights) HasRequiredSkills() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s AIInsights) SetRequiredSkills(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(7, v.ToPtr())
}

// NewRequiredSkills sets the requiredSkills field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s AIInsights) NewRequiredSkills(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(7, l.ToPtr())
	return l, err
}
func (s AIInsights) ImplementationTips() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return capnp.TextList(p.List()), err
}

func (s AIInsights) HasImplementationTips() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s AIInsights) SetImplementationTips(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(8, v.ToPtr())
}

// NewImplementationTips sets the implementationTips field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s AIInsights) NewImplementationTips(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(8, l.ToPtr())
	return l, err
}
func (s AIInsights) ResourceRecommendations() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return capnp.TextList(p.List()), err
}

func (s AIInsights) HasResourceRecommendations() bool {
	return capnp.Struct(s).HasPtr(9)
}

func (s AIInsights) SetResourceRecommendations(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(9, v.ToPtr())
}

// NewResourceRecommendations sets the resourceRecommendations field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s AIInsights) NewResourceRecommendations(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(9, l.ToPtr())
	return l, err
}
func (s AIInsights) GeneratedAt() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s AIInsights) SetGeneratedAt(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s AIInsights) Confidence() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(8))
}

func (s AIInsights) SetConfidence(v float32) {
	capnp.Struct(s).SetUint32(8, math.Float32bits(v))
}

func (s AIInsights) Model() (string, error) {
	p, err := capnp.Struct(s).Ptr(10)
	return p.Text(), err
}

func (s AIInsights) HasModel() bool {
	return capnp.Struct(s).HasPtr(10)
}

func (s AIInsights) ModelBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(10)
	return p.TextBytes(), err
}

func (s AIInsights) SetModel(v string) error {
	return capnp.Struct(s).SetText(10, v)
}

// AIInsights_List is a list of AIInsights.
type AIInsights_List = capnp.StructList[AIInsights]

// NewAIInsights creates a new list of AIInsights.
func NewAIInsights_List(s *capnp.Segment, sz int32) (AIInsights_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 11}, sz)
	return capnp.StructList[AIInsights](l), err
}

// AIInsights_Future is a wrapper for a AIInsights promised by a client call.
type AIInsights_Future struct{ *capnp.Future }

func (f AIInsights_Future) Struct() (AIInsights, error) {
	p, err := f.Future.Ptr()
	return AIInsights(p.Struct()), err
}

type IdeaFeedback capnp.Struct

// IdeaFeedback_TypeID is the unique identifier for the type IdeaFeedback.
const IdeaFeedback_TypeID = 0xe2ab26d5b6b147c6

func NewIdeaFeedback(s *capnp.Segment) (IdeaFeedback, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3})
	return IdeaFeedback(st), err
}

func NewRootIdeaFeedback(s *capnp.Segment) (IdeaFeedback, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3})
	return IdeaFeedback(st), err
}

func ReadRootIdeaFeedback(msg *capnp.Message) (IdeaFeedback, error) {
	root, err := msg.Root()
	return IdeaFeedback(root.Struct()), err
}

func (s IdeaFeedback) String() string {
	str, _ := text.Marshal(0xe2ab26d5b6b147c6, capnp.Struct(s))
	return str
}

func (s IdeaFeedback) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (IdeaFeedback) DecodeFromPtr(p capnp.Ptr) IdeaFeedback {
	return IdeaFeedback(capnp.Struct{}.DecodeFromPtr(p))
}

func (s IdeaFeedback) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s IdeaFeedback) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s IdeaFeedback) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s IdeaFeedback) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s IdeaFeedback) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s IdeaFeedback) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s IdeaFeedback) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s IdeaFeedback) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s IdeaFeedback) AuthorId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s IdeaFeedback) HasAuthorId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s IdeaFeedback) AuthorIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s IdeaFeedback) SetAuthorId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s IdeaFeedback) Type() FeedbackType {
	return FeedbackType(capnp.Struct(s).Uint16(0))
}

func (s IdeaFeedback) SetType(v FeedbackType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s IdeaFeedback) Content() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s IdeaFeedback) HasContent() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s IdeaFeedback) ContentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s IdeaFeedback) SetContent(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s IdeaFeedback) Rating() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s IdeaFeedback) SetRating(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

func (s IdeaFeedback) IsPublic() bool {
	return capnp.Struct(s).Bit(16)
}

func (s IdeaFeedback) SetIsPublic(v bool) {
	capnp.Struct(s).SetBit(16, v)
}

func (s IdeaFeedback) CreatedAt() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s IdeaFeedback) SetCreatedAt(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s IdeaFeedback) UpdatedAt() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s IdeaFeedback) SetUpdatedAt(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

// IdeaFeedback_List is a list of IdeaFeedback.
type IdeaFeedback_List = capnp.StructList[IdeaFeedback]

// NewIdeaFeedback creates a new list of IdeaFeedback.
func NewIdeaFeedback_List(s *capnp.Segment, sz int32) (IdeaFeedback_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3}, sz)
	return capnp.StructList[IdeaFeedback](l), err
}

// IdeaFeedback_Future is a wrapper for a IdeaFeedback promised by a client call.
type IdeaFeedback_Future struct{ *capnp.Future }

func (f IdeaFeedback_Future) Struct() (IdeaFeedback, error) {
	p, err := f.Future.Ptr()
	return IdeaFeedback(p.Struct()), err
}

type FeedbackType uint16

// FeedbackType_TypeID is the unique identifier for the type FeedbackType.
const FeedbackType_TypeID = 0x9a6043844678585d

// Values of FeedbackType.
const (
	FeedbackType_general   FeedbackType = 0
	FeedbackType_technical FeedbackType = 1
	FeedbackType_business  FeedbackType = 2
	FeedbackType_design    FeedbackType = 3
	FeedbackType_usability FeedbackType = 4
	FeedbackType_market    FeedbackType = 5
)

// String returns the enum's constant name.
func (c FeedbackType) String() string {
	switch c {
	case FeedbackType_general:
		return "general"
	case FeedbackType_technical:
		return "technical"
	case FeedbackType_business:
		return "business"
	case FeedbackType_design:
		return "design"
	case FeedbackType_usability:
		return "usability"
	case FeedbackType_market:
		return "market"

	default:
		return ""
	}
}

// FeedbackTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func FeedbackTypeFromString(c string) FeedbackType {
	switch c {
	case "general":
		return FeedbackType_general
	case "technical":
		return FeedbackType_technical
	case "business":
		return FeedbackType_business
	case "design":
		return FeedbackType_design
	case "usability":
		return FeedbackType_usability
	case "market":
		return FeedbackType_market

	default:
		return 0
	}
}

type FeedbackType_List = capnp.EnumList[FeedbackType]

func NewFeedbackType_List(s *capnp.Segment, sz int32) (FeedbackType_List, error) {
	return capnp.NewEnumList[FeedbackType](s, sz)
}

type IdeaVotes capnp.Struct

// IdeaVotes_TypeID is the unique identifier for the type IdeaVotes.
const IdeaVotes_TypeID = 0xc0568649b8efe961

func NewIdeaVotes(s *capnp.Segment) (IdeaVotes, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return IdeaVotes(st), err
}

func NewRootIdeaVotes(s *capnp.Segment) (IdeaVotes, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return IdeaVotes(st), err
}

func ReadRootIdeaVotes(msg *capnp.Message) (IdeaVotes, error) {
	root, err := msg.Root()
	return IdeaVotes(root.Struct()), err
}

func (s IdeaVotes) String() string {
	str, _ := text.Marshal(0xc0568649b8efe961, capnp.Struct(s))
	return str
}

func (s IdeaVotes) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (IdeaVotes) DecodeFromPtr(p capnp.Ptr) IdeaVotes {
	return IdeaVotes(capnp.Struct{}.DecodeFromPtr(p))
}

func (s IdeaVotes) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s IdeaVotes) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s IdeaVotes) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s IdeaVotes) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s IdeaVotes) Upvotes() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s IdeaVotes) SetUpvotes(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s IdeaVotes) Downvotes() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s IdeaVotes) SetDownvotes(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

func (s IdeaVotes) TotalVotes() int32 {
	return int32(capnp.Struct(s).Uint32(8))
}

func (s IdeaVotes) SetTotalVotes(v int32) {
	capnp.Struct(s).SetUint32(8, uint32(v))
}

func (s IdeaVotes) AverageRating() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(12))
}

func (s IdeaVotes) SetAverageRating(v float32) {
	capnp.Struct(s).SetUint32(12, math.Float32bits(v))
}

func (s IdeaVotes) VoterIds() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s IdeaVotes) HasVoterIds() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s IdeaVotes) SetVoterIds(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewVoterIds sets the voterIds field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s IdeaVotes) NewVoterIds(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s IdeaVotes) LastVoteAt() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s IdeaVotes) SetLastVoteAt(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

// IdeaVotes_List is a list of IdeaVotes.
type IdeaVotes_List = capnp.StructList[IdeaVotes]

// NewIdeaVotes creates a new list of IdeaVotes.
func NewIdeaVotes_List(s *capnp.Segment, sz int32) (IdeaVotes_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1}, sz)
	return capnp.StructList[IdeaVotes](l), err
}

// IdeaVotes_Future is a wrapper for a IdeaVotes promised by a client call.
type IdeaVotes_Future struct{ *capnp.Future }

func (f IdeaVotes_Future) Struct() (IdeaVotes, error) {
	p, err := f.Future.Ptr()
	return IdeaVotes(p.Struct()), err
}

const schema_b2c3d4e5f6a70819 = "x\xda\xbc|{t\x1c\xd5\x99\xe7\xbdU\x92Z66" +
	"\xad\xa6\xda\x04;6m\xb3\x01\x83\x03\x89-c\xd6\x08" +
	"8m\xc9\x8f a\x05\xb5Z\x06[\xb1\x13_u]" +
	"u\x97U\x8fvU\xb5le\xf1(!8\x01\x8e}" +
	"\x16\x12{\x02\x19\xc8B\x0e$0C6&\x0b\x1c\xb3" +
	"\x83wy?\xb2\xb0\x07v\xf0\x19<\x83'\x98@\x06" +
	"\x13|\x16;0<\x16\xd2{\xbe\xef\xd6\xe3\xf6C&" +
	"\x9c\x9d\x9d\xe3\x7f\xe4_]\xdd\xbau\xef\xf7\xfc}\xdf" +
	"\xd5\xe2G\xcf\\\xd1\xb2d\xe6\xdf_B\x94\xfc~\xa5" +
	"\xb5\xadz\xe1\x93\xe7\xaf\xd8\xf2\xd3\xfe\xef\x92\x94\xa6T" +
	"\xdb?\xf8\xfd\xc1'\xff\xcb\xcf\x8e\x13B\xb5\x97\xe6\xfd" +
	"F;</A\x88vh\xde\x95\x84VG\x96\xed\xfa" +
	"\xe9\xabgM|\x0f\x07.\x9a\xdd\xfe\x8b\x7fy\xf3\xe5" +
	"'`\xe0\xb1y\x1fk\x1f\xe1\xc0\xf7\xe7\xfd\x98\xd0j" +
	"\xe9\xd3\x87\xfe4\xf0wo\xec$9\x8d\xd2xdk" +
	"K\x82\x90\xa5\x97\x9d\xd9I\xb5\xfe3\xe1\xc7\xde3\xaf" +
	"\xa6\x84V\x8f\xde\x93>\xbae\xcbC?\xa8_\xc0\xd2" +
	"\x03\x99ET{!\x03\x13?\x97\x81\x15\xa4\xcf\xb8\xe2" +
	"\xe9sO\xef\xbd\x01G\x06\xd3\xfe\x1aVp8sB" +
	";\x8a\x03\xdf\xcc\x14\x09\xad\x1ePNy\xe7\x0f\xc6E" +
	"7\x92\xdc\xe94Q\x0d\x06\xdeIZg\xc0\x90\x99\xf3" +
	"Oh\xb3\xe7\xc3\x02f\xcd\xffZ+\xa1U}\xe3\x97" +
	"\xcf:\xb1\xe7\xfc]$u\xba\x12\x0f&ti\xea\x9c" +
	"N\xaa-8\x07~i\xde90\xef\x7f\xbe\xe5\xb4\xd7" +
	"n\xeb\xfc\xc5M0/\xad\xdey\xa5\xfe\xe4\x8b\xe6\x81" +
	"\xbb\x82/[}\xceYT[\x07\xa3\x97\xe6\xce\xc9\xc0" +
	"\x97]\xbacAV;\xf1\x83\x1f5l\xad\xb5\xf0c" +
	"mb!\xcc[Y\x08\x1f\xb6i\xfd\xf65\xd7\xad\xdc" +
	"\xfc\x93\xfa\x0f[z\xc3B\x85j{q\xe4\xcd\x0ba" +
	"o\xffi\xe1%?9\xff/\x7f\xf8W\xb0\x82\xb6x" +
	"\xb1\xb8\x80#\x0b;\xa9v\x1c\x06/=\xb6\xf0\xdf+" +
	"\x84V\xa7\x8d\x16\xaf\xdem\xff\xe9\x0e8\x09\xe9\xccZ" +
	"U\x18\xb3n\xd1\x1c\xaa\xf1E\xf0#[\x84\xeb\xfdO" +
	"kV|r\xfd\x8d\xedw\xc2\xf0\x96x\xc1\xadm\xf0" +
	"\xfe\x1d_~\\\xdb\xf9e\x18\xfd\xdd/\xff\x02&\x9f" +
	"av\xcc\x9e8\xbc\xeeg0Z\x8dW\xdd\xaa\xe0\x0e" +
	"|e\x0e\xd5\xd8W\xe0\xc7M_\xf9\x8f0\xf9\xdd\xd3" +
	"\xfe\xd7\x9e\xe3\xbf\x7f\xe0\xae\x86]~\xff\xabgQ\xad" +
	"u1\xbc\x83.\x86oL\xfc\xfc\xf6\x7f<31\xf3" +
	"\x1e\xb1\xcb\xb5\xdf\x98[\xdcG5\xbe\x18\x17\xbd\x18\xbf" +
	"\xf1\xc6\xe1\x03\xb9\x96-\xfb\xef%)\x8dJ\xab8\x05" +
	"\xe6;\xd8\xf9\xb1v\xa4\x13\x06\x1f\xeet`\xf0\x15\x83" +
	"\xd5oUo:\xf8\xab\x86\x139\xb2\xec\x84vl\x19" +
	"\xfc\xce\xd1e\x93\x84V\xefz\xa2{\xe3\xde\xa1\x07\xf6" +
	"\xe1\xac\xb5\x1b\xa7\x9dw\xd1\xeb\xda\xb2\x8b\xe0\xa7%\x17" +
	"\xfd\x8a\xd0\xea\xd5\xdb/5\xff\xfb\xcf\x95\xfb\xeb\xc6&" +
	"\xe0\xbd/]\xa4P\xed0\x0c^z\xe8\"\xdc\x87\xdf" +
	"\xef\xb8\xe9\xd37\xff\xe6\x93\xfb\xc5\xb6\xc5\xc3[aB" +
	"k\xf9\xc7\xda\xc4r\x18]Y\x8e_70\xf0su" +
	"\xf1\xd0\xae_\xd7+\xdd\xd2C]\xa7Q\xedh\x17\xca" +
	"|\x17\xaa\xe7\xa7\xb7\xd3g\xbe\xdb\xf3\x10\xcc\xdb.m" +
	"D\x0a\x86|\xda\xf5\xb8\xd6z\x09\xccK/Y\xd8F" +
	"h\xf5\xc7G\x0bs\x07\x96\xbc\xb2\xbf~\x15\x14\xc6\xbc" +
	"\xdf}\x1a\xd5Z{\xf0Dz\xfe\x19\xbep\xc5\xaf\xc6" +
	"\x9e=\xf5\xe3\xfdB\xa3c\xc1\xc0\xa3>\xdc3\x87j" +
	"\xc7`\xf4\xd2\xa3=U\xf8Dv\xf4\x7f\xef\xef\xfd\xfe" +
	"U\x8f\xd6K\x06L\xae\xcdZ\xfd\xb6\xb6`5\x8c\x9e" +
	"\xb7\x1a\xf5\xff\x89\xe5\xc6\x8f.\xb8\xe4\x9a\xc7\x84\x90\xd6" +
	"\x9d\xe0\xee5'\xb4[\xd7\xc0\xe8\xbdk~\x0b\x1b\xf2" +
	"\x02\xfd\xb1\xfb/\xd9\xff\xf3X\xbd\x0a\xe2\xc9l\xe8\xfb" +
	"\x07\x8d\xf7\xc1O\xac\xef\x9f\x09\xfd\xb4g\xd1\x9ff\xac" +
	"\xca=Qo\xb0z\xafx][w\x05\x0c\xcb]\x01" +
	"\x87\x9d\x9d\xfd\x8f\xad\xbf\xf9\xf5}O\xc0\x9c\xaad." +
	"PMv^q\x16\xd5\xf6\xc2\xe8\xa57_\x81\x0b\xbe" +
	"\xf6o\xfbv\xf7\xb7?\xfbd\xa3!\\\xfb\xb6\xf6\xd1" +
	"Z4\x84kA0\x0e\xff\xce\xbcQ?s\xd3\xd3\x0d" +
	"\xd2\xb6\xa9\xffu\xcd\xe8\x87\x81\xbc\x1f\xec\xca\xbe\xfe\xc7" +
	"{\x87?\x18z\x0e\x16\xd0*-\x00E~w\xbfB" +
	"\xb5[\xfbq\x0f\xfaq\x7f\x9f5\x92?\x18x\xfao" +
	"\x7f\xd3\xb0\x80{\xaf|]{\xf0J\x18y\xff\x95I" +
	"\x18\xb9\xf3\xe0%\xdf*\xbf\xfc\xc5\xe7\x9b\xe9\xa8\xc6\x06" +
	"Nh\xd6\x00\x8c6\x06P4w\xff\xddO\xaf}\xfb" +
	"\x9d?\xbeTo\xb8qo\xa7\x0d~\xac\xcd\x1a\x84\x9f" +
	"R\x83 \x13g\xfe\xea\x17\x8b\xd2\xcf|\x84\x83\xdb\xa4" +
	"\xc13Q\xde\x06\x1f\xd7Z\xf3(o\xf9\xbfo\x01#" +
	"o^\xb4\xf0\xe9\xb3\xaf{\xb9a+v\xaf\x7f[\xbb" +
	"u=\xfc\xce\xde\xf5p\x16\x93+\xae\xbf.u\xf5\xf7" +
	"\x0e5=\xdf\x17\xd6\x9f\xd0\x0e\xe1\xe0\x83\xeba\x0d\xa7" +
	"\xffq\xe8\xa1\xff`\x1d\xfa\x87\x06\x9br\xff\x86N\xaa" +
	"=\xb6\x01F\x1e\xd8\x00\xd3\xfe:\xf1\xe8\x87\xd3\x9e\x7f" +
	"\xfe\xd5\x06=\xfat\x83B\xb5i\xc30\xb2u\x18F" +
	"v\xcd\xbd\xbb\xf5G\x9ff\x0e\xd7\xcb:\x9c\x85\xd6=" +
	"\xfc\xba\xd6?\x8c\xcek\x18e\xe1\xf4\xe7_\xfao\x9b" +
	"\x96\xfc\xcf\xc3\x0d.\xe9\xe07\xde\xd6\x8e|\x03~\xe7" +
	"\xf07\x9e\x01\xb5\xbf\xf6\xce\x8b\xb7\xfc\xd5_\xfcS\x83" +
	"\x89\xdf\xb0Q\xa1\x1a\xdf\x88\x07\xb2\x11\x84ar\xd1\x9e" +
	"g\xee\xff\xda\xf0\x91z}\x00+\xbc\xf4\x86\x8d\xa7Q" +
	"\xed\xd6\x8d(\x0c\x1b\x9f\x81\x15<\xfd\xb5\xfb\x1f:x" +
	"\xce\xdf\xbc^\x7f\xc4(\xbc[\xbf\xa9Pm\xc77\xe1" +
	"\xc7\x89o\xe2\xf0S\xdb\x87\xf7\xdd\xd8\xb7\xfbwb\xf6" +
	"\xf8\xf3px\xff\xe6\xb3\xa8\xb6i3\xfc\xb8a3~" +
	"\xdfW_\xb9\xfb\x8f\xc3\x0b\x9f\xfe]\xe3\x0e\xb3\xd3\xa8" +
	"\xf6\x18\xc3\x1df\xb0\xec\x15\xdfs\x7f\xeb~_\xfbC" +
	"\xbd\xf0\xa0E9\xca\x14\xaa\xbd\x0f\xa3\x97\x1eg(\xc3" +
	"\x1f\x9c\xf1\x81{\x89\xb3\xf9\x1d\xe1k\xea$\xf3b\xfd" +
	"\x84\xb6Z\x87\xd1\xdd:\xae\xfa\xa3\xad\xd5\xa7\xdf\xb8\xec" +
	"\x86w\x1a\xb6y\xd6\xe8\x09m\xc1(z\xe8\xd1\x0f\x08" +
	"\xad\xfe\xe5\x1b\xdf\xff\xc3\x95\xff\xe3\xfac0\xed\xb4x" +
	"\x15xx\x07F?\xd6\x9e\x83\xb1K\x9f\x1a\xfd\x82\x0a" +
	"\x8a\xbci\xdf\xef2\xbb\xc6\x8f7\xdd\x8b\xee-\xd3\xa9" +
	"\x96\xdb\x82\xdb\xb2\x05\xdd\xe33O\xb5\xed\xbf\xfd/\xaa" +
	"'\xea\xbe\x10\x95\xd4\x1a\x9bC\xb5\x1dc\xb8\xd1c\xe8" +
	"jN|\xeb\xf4\xdd\x8b\xad\xcb?\x14\x1f\x18\xef\x07:" +
	"\xd3\x8b\xed\x13\xdaj\x1b_c\xffV!\xd5\xe8\xdf\x99" +
	"U\xafP\xe2\x16\xf3\xbe\xaaT<\xee~\xa5\xc0\xcav" +
	"\xb9k\xa8\xc4-N\xc8\x00\xa5\xb9\x19T!$5\xaf" +
	"\x93\x10JS\xb3\x16\x11B\x95\xd4\xccE\x84dL\xa3" +
	"X\xf2\x93:s\xc7\x92\xac\xe2;\xf1<>gV0" +
	"\xcf\xca\x12\xb3\xed,7\x87&\xca\x1c&;\x03'\xeb" +
	"\xee\xc1\xc9.\xee\xc1\xc9\x96\xb8\x84P5uA\x17!" +
	"\xb4%u6\x80\xad\xf8\xbe\xc9\"\xb7\xb9\xcb\xcc\xc9\xb2" +
	"\xebl\xe1\x05\xbf\xcal\xdb\xa9\xd8\x05N2\x16\xb7}" +
	"/\xeb2[w\xacI\xafR.;\xae\x9f1t\xce" +
	"\xbch\x19\xaa\xb4\x8c~n\x8dp\xb7{\x9c\x19&\x1b" +
	"\xc9\x18\xa6\xe1O\xe0j\xd4\x16BZ(!\xa9[\xb7" +
	"\x10\x92\xbbE\xa5\xb9\xbb\x14Ji\x9a\x02vg\x1f!" +
	"\xb9;T\x9a\xbbO\xa1)\x85\xa6q\xe9\xf7\xc2\xc0{" +
	"T\x9a{@\xa1)UIS\x95\x90\xd4\xfd\x00\xeeS" +
	"i\xeey\x85\xa6Z\xe6\xa7i\x0b!\xa9\xe7\xe0\xd7\x9f" +
	"Ui\xeee\x85\xa6Z\xd54m%$\xf5\x12\x80/" +
	"\xaa4\xf7\xaaB\xab%\xa7\xe2z\x03\xdc%\xc9\xab9" +
	"\x1f\xa3\xd3\x89B\xa7\x13Z\xf5\x0d\x8b\x7f\xdb\xb19!" +
	"\x84\xce \x0a\x9dAhu\x9b\xe3\x8e\x19v\xf1r\x92" +
	"\x84\xdf\xa1\x1dq\x08@(\xed \xb4:\xce\x0a\xcc7" +
	"\x1c\x9b$W\xb1\x09\x8f\x9eJ\xe8\x80JiG\xecv" +
	"\x09\x05\xb0jx\x83\xdcr|\x9c\x9c\x12\x85\x82\x98\x99" +
	"N\xf0\xbb\xd2\x0b\xa3]\x94\x84b\xc0uF\x0d\x93_" +
	"ex\xc6\x88\x91\x0c71\x90\x8f\xae\x1a\xf9\xe8!$" +
	"[\xae\x8c\x98F!\x09\xc70Yv\x8dq\xe6\xf3X" +
	"F\xe0\xac\x82i\xf3c\x86if\xd6\xf2qn\xc2|" +
	"\x1d8\xdfyb\xbe\x05[p>\x9c]M\xcd\xea\"" +
	"$\xbb\xa5b\x1b\x8e[5l\x9f\xbb\x16\xd7I\xd2`" +
	">\xcfz\x1c\xd0,\xdf^\xe6\xae\x1f\xbf&\x90\x9c\xe8" +
	"\x032\xf8_x\xcd\xe6\xf0\xec\xb5\x9b\x959\x84\xe4w" +
	")*\xcd\xdf\xa2(4\x15\x9c\xbf\xb6WYDH\xfe" +
	"&\xc0o\x03\\QP\x04\xb4[\x95\x11B\xf2\xb7\x00" +
	"~\x17\xe0\xaa\x8aR\xa0\xdd\xa9t\x11\x92\xbf\x0d\xf0{" +
	"\x00oiAA\xd0\xeeV:\x09\xc9\xdf\x01\xf8}\x8a" +
	"Bi+\x8a\x82v/\x0e\xbf\x0b\xe0}0\xbc\x8d\xa6" +
	"i\x1b!\xda/\x95>B\xf2\xf7\x01\xbe\x1f\xf0Dk" +
	"\x1a\xc3\x98\x07q\x9a}\x80?\x02x{[\x9a\xb6\x13" +
	"\xa2=\xac\xf4\x10\x92\x7f\x00\xf0\x17\x01\x9f\x96H\xd3i" +
	"\xe0\xba\x10\x7f\x16\xf07\x00\x9f\xde\x9e\xa6\xd3\x09\xd1\x8e" +
	"\xe0g\xbd\x0a\xf8\x87\x80\x9f2-MO\x81\x08\x02\xdf" +
	"\xfb\x9e\xa2\xd2AU\xa1\xa9\x19\xf3\xd3t\x068V\x84" +
	"?\x81\xe1\xed\x80\xcf\xa4i:\x13|\x97:HH\xbe" +
	"EUi\xbe\x03\xf0S\x954=\x15\x92\x1d\x15^\xdb" +
	"\x0ex\x1a\xf0\xe4\xf44M\x82\x0fW\x87\x09\xc9w\x00" +
	"~>\xe0\x1d\xa7\xa4i\x07\xc4\xb6*\xcc\x7f.\xe0\x17" +
	"\x02\x9eZ\x90\xa6)\x88tq\xfe\xc5\x80_\x0a\xf8i" +
	"g\xa5\xe9i`\xc8\xd4\x1f\x12\x92\xbf\x14\xf0\xcb\x01\xd7" +
	"\xd44\xd5\x08\xd1V\xe3\xf8U\x80\x0f\x00\x9enI\xd3" +
	"4!Z?\xe2k\x01_\x0f\xf8\xac\xd64\x9dE\x88" +
	"\xb6N\xddBH~\x08\xf0\xcd\x80\x9f\xfe\xef\xd2\xf4t" +
	"B\xb4M\xb8\xce\x8d\x80\x97\x00\xff\xc2\x8c4\xfd\x02\xc4" +
	"M\xf8]\x9b\x017U\x85\xaa\x86\x1e\xeaJ\xd2f\x16" +
	"\x8f\x14G\xe7^\xc15\xca>I\x18\x8e\x1d\xa2Y6" +
	"\xce|\xe6\x86\xff\xcd\x14\x1c\xd3\x89\xfe\x97\xf5|\xe6W" +
	"<\x9a\x8c3\x16Bi\x92\xd0j\xd95\x1c\xd7\xf0'" +
	"@1\x93q\xd6(\x9ef\x9cm6\x8f&\x99\xb4\xd0" +
	"\xc4I\x9a\x1f\xc5\x98B\xf3'A\x0f{\xf5h\x00\xfc" +
	"\xde\xa9\x84&}V\xac\xc7\xaa\x05\xe6\xf3\xa2\xe3N\xc8" +
	"\x06\xc1\xf0\x06P\x9fe\xc3\xe1\xf9\xcc\xf5W1\x9fP" +
	"N[\x89B[\x09\x9d\xe4\xb6\xbe\x8a\xf9\xd1\xff\xab\x96" +
	"ar\xcfwl\xa2riqQ\xfc\x19\x98\xa5\xb2\xeb" +
	"\x14]\xeey0{G\x9cs\x06\xc6\x8d\x19\xabm6" +
	"brB\xf5\xe8\xdd\xe0r\xbe\xc6mN]\xe6\xf3^" +
	"\x9d3\xeaE\xcf\x0a.g>\xd7\xbb\x09\xf5\xa3uT" +
	"\xcaz\x03f2\xcf\xef.\xf8\x06I\x8e\x1b\xfeD\x04" +
	"\x1b^\xb7[(\x19\xe3D\xe5\xd1\xfb&\xc7\xb9\xeb\xc1" +
	"\x89\xb6\x10\x85\xb6\xc8\x06\xb2\xde\xc4\x08\x0b\xe3\x1a\x19<" +
	":\xc9\xa2\x9d%,Z\x17Z\xb4\xd9\x8b\xd0\xa2\xa5\xfa" +
	"\x08I\x98\xce\xb6\xac\xc5u\xa3b%KF\xb1T-" +
	"\xb8\x86o\x14\x98I\x08\x89_cq\xcfcE\x1e\xbc" +
	"f\x95\xe1\xf2\x82\xdf\xcf=/\xc1\x8a\xe8Y\xd3\x91/" +
	"\xdb1\x87\x90\xdcv\x95\xe6\xae\x8b\x8dY\xea\xbb\xe0x" +
	"\xbe\xa3\xd2\xdc\xae\xd8\x92\xa5n\x18!$w\xbdJs" +
	"{b3\x96\xba\xb9\x87\x90\xdc.\x95\xe6nQ(\x15" +
	"&,\xb5w\x90\x90\xdc\x1e\x95\xe6\xee\xa8\x91\xfc\xaa\xc7" +
	"m\x9d\xbb\xbd\xba,(./\x18e\x83\xdb$\xe1\xf7" +
	"F#'\x0b\x8e\xeds\xdb\x8fF\x81\x93\xf3|f\x11" +
	"Z\x8e\xf6\xbdY 2\xe0\x1a\x16\xcb\xba\x13\xdd\x15\xbf" +
	"\xd4\x18\x8dt\x0ao\xd3EH\x86[\xcc03\x0e\xab" +
	"\xf8\xa5\xec6f\x9a<\xf6\x02\xaa\xe4l\xd6p\xae\x8f" +
	"\xb0\xc2\x18\x04$\xa41\"\x19\xc4\x09\x97\xf5\xe1\xe1," +
	"\x11\x11\xc9y\x83\x18\x91\x9c\xdd\x15G$U\x9f\x17J" +
	"\xb6Q`\x84\x9a\xd5\x91\x8ag\xd8Bv\xb3:\xf7\x8c" +
	"\xa2]\xadxl\x04\xa2\x0cB'\xb2\x16s\xc7\xe4\xc5" +
	"L!/N\x06\x15\x00\x96tn\xe4\x9a\xa6\xd1\xbf&" +
	"$?\x83\xaa4\x7f\x06\x95\\\xd3,\x0aF*\x0d\xf8" +
	"|*\xb9\xa6y\xf4\xdb\x84\xe4\xe7\x02~.\x95\\\xd3" +
	"\xd9\xf4ZB\xf2_\x02|1\x95\\\xd3\x05\x14\\\xd9" +
	"\xf9\x80/\x07\xbc5\xf0M\xcb\xa8KH\xfeB\xc0W" +
	"\x00\xde\xf6\xa8\xf0M\x97Q0\x9a\x97\x02~9\xe0\x89" +
	"\x84\xf0M\xab\xf1\xbd\xab\x00\x1f\x00\xbc\xbd]\xf8\xa6~" +
	"|\xefZ\xc0\xd7\x03>\xadU\xf8\xa6u\xf8\xde!\xc0" +
	"7S\x85V\x0b\x8eU6\xb9oP\xc7\x1e\xe0n\x81" +
	"\xdb`\x96x\x1c\x119>3{uNT\xe6E\x0a" +
	"\x18\xfc\x0e'Y\x1d\xd4?~`\xd8\x03hM\xa8\xe7" +
	"\xe1\x03\x12=\xd1\xd9\x84\xb7\xdade\x92\xf0\xb8^\x83" +
	"\x0er\x8b\x91\x8ca\x1bv1\x9e\xc7\xbb\xd2\xce\x17J" +
	"\x9c$\xf5\x8a\xc9#\xe3\xb2\x8d\xf31s\xa2\xbb@\xb2" +
	"\xbe\x81f#\x1co9\xb6_2'\xbaiA<\x88" +
	"\xdf\x0bvf]Yg$\xe1s\xbdA\xdc\xe5@u" +
	"\x08\x8c\xb4\xed\xf3\xa2\xcb|Cu\xec:\xcd^\x14k" +
	"v\xa4\xd8\xa0\xae\xd7\xa84w\xbd\x14\xa5\xeet\x09\xc9" +
	"]\xa7\xd2\xdcMR\x94\xba{8V\xecT\x0b\x0d4" +
	"\xbb/\xd6\xec\x1aG6\xc9\xd1\xe4\xc6\x06\xb7\xe0\xd8\xa3" +
	"F\xb1\xe2\x92\x0c\x06\x8bqh\xcaGJ\x8e3\xb6\x8e" +
	"\xa8\xae\x19\x81\xf0\xc5\xf9\x09\x1b\xbd\xc5\xc9\xd4{\x9d\xc7" +
	"]T\xc3\xc5\x91\xccw\xd3952\x16\xca\xfcj\x0a" +
	"q\xcb\x0a\xc0\xd7\xca2\xdfK;kd/\x94\xf9~" +
	"\x0a\xf1\xd5\xe5\x80\x0f\xd1\xc8\x94i9\x9c&\x16\xc9\xd6" +
	"\x16!\xf2\xebh\x9f,\x92Q8\xb6\x89B\xfc\xb0\x11" +
	"\xf0\x12\x8a\xbc\"D\x9e#\xae\x03^F\x91o\x15\"" +
	"o\xa1h\x9b\x80oG\x91\xef\x10\"_\xc1\xf9}\xc0" +
	"\xbf\x03\xf8tU\x84c;p\xfc5\x80_\x0f\xf8)" +
	")\x11\x8e\xedD\x15\xbc\x0e\xf0\x9b\xe8\xd4\xf1\x86\xb0{" +
	"S\xc4\x19I\xd719M\xc6\xb4P\x10W\x80\x91\xec" +
	"\xb5G\x1d\xe1m#\xfe!\xf0\xb6\x7f\xae\xf7,\xbb|" +
	"\x94\xbb`\xe8\x0b\x1cS\x92\x90\xb3\x0b\xe61<\xf0\xad" +
	"\xe3\xb5\xa9\x06\xf3\xfc\xb5N\xd1 \x09\xbb;\x9e\x09\xbf" +
	"\xe1*\xee\x92\x8c1jH\"\xd7\xcc\x80\x83J\xaf\xe1" +
	"\x0cR\x10\xd3P\x85\x83\x9d\x1bi\xc8\x83\xe0\xa8\x1eP" +
	"i\xeeQ\xc9\xf7\x1d\x00\x19\x7fD\xa5\xb9g%\xdf\xf7" +
	"T\x17!\xb9G\x83\x9c-\xf4}\xcf\x812=\xa9\xd2" +
	"\xdc\x8b\xb1\xef{\x01\xd4\xe6y\x95\xe6^\x01iQD" +
	"\x1ew\x10\xc0\x97U\x9a{-\x16\x95\xd4\xe1NBr" +
	"\xaf\xa84\xf7\x86Be\x0f\x11\xd91\xc9S\x84X\xe0" +
	"\x1e\xc2\xffN:\xe3\xe0_\xe2_a\x9e\xc7=\x8f\xeb" +
	"D\xed\x99\x88\xb4+\x06\xe3M\xcc\xd8\x8e\xcf\xbd\xc6\xfc" +
	"\xad\xa9\xbb\xc9\xfb,\xe1W<\xc9\xff\x09\x87z\xb1\x08" +
	"N\x96\x88t\x0b\x1d_K\xeal\xe1\xff\x16\xf4\x11\x92" +
	"\xd1]6\xeag\x19\x9ek\xd6\xb1/wL=6\xc4" +
	"T\xaf\x16\x98]\xe0&FjU\x86A\x14\xd7\xe50" +
	"\xa6\xa5\xb9\xf7\xe3\xaeex\x10^y\x82s\x90= " +
	"x\x96vP\x83\xb4l\x0dR\x88w\x00>W\xb6\x06" +
	"\xb3\xe9\x8dSx@\xc0\xcf\x05\xfcB\xd9\x03.\xc1y" +
	"\x16\x03~\xa9\xec\x01/FO\xb7\x1c\xf0Uh\x0e\xda" +
	"\x849\xe8\xc6\xf1\xb1\x15\x0a=`/\xfdI\x8dY\x09" +
	"=\xe0:|\xefz\xc0u4\x07\xd3\x849`\xa8\xde" +
	"\x9b\x017\xd1\x032\xfb*\x83o\x1b Y\xb1%\xb1" +
	"\xd9e\xf6j\xdd\xf0\x9b>X\xc5M\xeeS\x1e\xec\xa2" +
	"\xa4f\x05f\xf73\x9b\x15)\x17\xcc\x87W\xfbl%" +
	"h8\xc9r\xe17\xeb\xde\xd4K\x92\xf50\xbe\xa7\xd9" +
	"\xf8\xe0%\x83\xdcs*n\x01\"|\xe9!|O7" +
	"\xb5\x999\xe1\x1b\x85\xba\x15\xac\xde^v\\\x92\x81\xe4" +
	"\x815\xa8\xbbR\xa7\xee+\xb3\"x\x04\xc98?\x92" +
	"\x8c\xfa\x13\x0d%c\x09\x1a\xda\xf8DC\xc9\xb8\x18\xf1" +
	"\xe5\xa1?\x88$#\x87'=\x10\x9eD$\x19\x06\xfd" +
	"a\x8d!\x0f%\xa3\x82\x86\xdf\x0f\x0ds$\x19\xbbq" +
	"\xfe]\x80\xdf\"K\xc6^\xf4O7\x01~\x9f,\x19" +
	"\xf7b\x0cw\x0f\xe0O\xca\x92\xf1\x18\xe2\x8f\x02\xfe*" +
	":\x8a\xe9\xc2Q\x1c\xc2y^\x06\xfc5\x90\x98\xb2\xeb" +
	"\x8c\x98\xdc\xcaS\x9f\xf9\xdc\xe2\xb6/\xb37\x8eY\xa9" +
	"gtF\xb8\xcdG\x0d\x1f\x8dO]\xbe\xe7\xf2\xad\x15" +
	"\xc3\xe5\x16Ir\xdbo\xc8\x06CKF\xcd\xeer\xd9" +
	"uX\x81\x96\xa4`\x1fO\x9e\x13\xda\xf8k\x86\xc5M" +
	"\xa3\x86\xc6\xca\xb8\x867\xd60\xd02|\xa3\xc8|\x83" +
	"\xa8\x8e\xdd\xb82t1\x059{\x0c\x9eMa\xf0\xe4" +
	"\xe8\xe2j\xc8\x032~H>\x0a\xc3\x8f\xc1=\x15\xac" +
	"\xa3\x92\xba@\x84\xfa\xe7\xf5\xa0\xa9\x83\xe4\xacjq\x9f" +
	"Y\xcc\x1b\x03\xbb%2\x89\x95\x0e\xc9\xd86/\xf8\xd5" +
	"\x82c\xd8#\xcc\x83\x8f\x9a,\x97\x98\xed;V\xd6\xe4" +
	"z\x91\xbbM\xe9\xcf!\xc3\xe2\xf9\x84\xe9\xa0\xe8\xce\x88" +
	"\xbc\xd4j\xf0R\xabT\x9a\x1b\x90\xbcT?\xf8\x9e\xcb" +
	"U\x9a\x1b\x92\xbcT\x0e2\xb4\x01\x95\xe66*A\xba" +
	"=dX\x90n\xc7Q\x9a\x0e/99\xfd\xd04\xd4" +
	"\xbc:\xa0\x14\x9d\x8a\xeb\x91:/\xda\x15\xf0\x99\x8fH" +
	"\xeb{\xb8Gr\xad\xe1\xfa\x0e\x0cJ\xae5\xf4\xa2O" +
	"\xf5\xc5^4T\xa7\xd4\x0b]2\x1d\xda\xdaH\x87\x86" +
	"\x8a\x94:\xd4\x15\xfb\xd6\xac\xe5\xd8:\x9b\xa0\x1dq\xa9" +
	"HD\x17\x93~\x85{M\x9fT\xb7q\xdd\x86g\x84" +
	"6{\xea\x97*.\xfc\xa2\x88}\xea\x9efG]\xa3" +
	"\xf9\xa4\x1e\xf3+\xee\x94\xbf\xe6U\xec)~\xad\x99P" +
	"pf\xad\xcc\x96\x98m\x0b\xc2Svv\x10\xfa\xb6\x80" +
	"\x8aw\xc8&m&\xc6\xac\xb1\x13\x0cMZ\x0ac\xc7" +
	"\xc8\x09\xd2\xc0\xa2\xcd\xc6\xe1qv\xd8\xd2!,\xda<" +
	"\xb4\\\xb1o\x0cHi\xedl\xdaCH~~d1" +
	"\xdbZ\x84E\xbb\x18\xc7\xc7>0A\x85E\xebF<" +
	"\xf6\x81\xed\x8a\xb0h\xbdhI\xa3\x88;5\x8d\x0a\x8b" +
	"&Y\xd8\x8d\xf4\xf3RgI\x7f\xa2\x0c1l\xd4\x0c" +
	"\x12\xc4\xb0\x867\x80\x9c2(C\xc8\xd1\xd4q`\x11" +
	"\x9d%\x02\xda\x1e\x10\x88\xf0]\xcd\x82\xdc)\xe8\xa0\x80" +
	"yYI\x92N\xc5\xf6\x1b\x09\xa0\xba\xa3\x15\xf4\xb8i" +
	"\xf8T\xa6\xc7\x05\xbf0\xab\x0f\x8dN\xaa\x0b\xccG@" +
	"\x89#\x91m#\xdb\x13P\xe6S:BT\xd3r$" +
	".T\x9dSC\xcd\x86\xe2\xd2\xaav\x122\xa8\xaa4" +
	"?C\x95\xa4e\x9a:R\xc3\xcc\x86\x0e0\x85\xcc\xe6" +
	"\x0c\xc0\xcfP\xe3Di\x96\xda\x15\x12\xb6sax+" +
	"\x15\xd22\x1bf\xcf\xa7\x01\x9f\x0fx\x9b\"\xa4e\x1e" +
	"\x12\xb9s\x01?\x17\xf0D\x8b\x90\x96\xb3\x91\x80\xfd\x12" +
	"\xe0\x8bU)Q\xba\x00\xf1\xf3\x01_\x0e\xf8\xb46!" +
	"-\xcb\x90\x80\xbd\x10\xf0\x15\x80OO\x08\xffw\x99\xea" +
	"\x86\xc4/\x12\xb9\xa7\xb4\x8bDi\x1d.\x7f\x00\xf0\x8d" +
	"H\\O\x13\xc4\xf5\x06\xfc\xdc\xf5\x80\xfbH\\O\x17" +
	"\xc4\xf5V\x15\xb4\xc3\x04\xfcz$\xaeO\x11\xc4\xf5N" +
	"\x1c\x7f\x1d\xe07!q=C\x10\xd7\xbbq\x1f\xae\x07" +
	"|\x0f\x12\xd73\x05q}3\xe2\xbb\x00\xbf\x05\x89\xeb" +
	"S\x05q\xbd\x17\xd7\xbf\x07\xf0;\x90\xb8N\x0a\xe2\xfa" +
	"v\xdc\x9f\xdb\x00\xdf\x8f\xc4u\x87 \xae\x1f\xc4\xfd\xdc" +
	"\x07\xf8#H\\SA\\?\x8c\xdf\xf5\x00\xe0\x8f\"" +
	"q\xad\x08\xe2\xfa\x00\xee\xdb#\x80?\x8b\xc4\xb5*\x88" +
	"\xeb\xa7p\x7f\x9e\x04\xfcE$\xae[\x04q\xfd\x02\x8e" +
	"\x7f\x1e\xf0W\x00?\xa35M\xcf D;\x88\xf8\xcb" +
	"\x80\xbf\x06\xf8\xec\xb64\x9dM\x88v\x18\x89\xf1W\x01" +
	"\x7f\x0b\xf09\x8b\xd3`\x96\xb47\xf1\xbb\xde\x00\xfc]" +
	"\xc0\xbfxj\x9a~\x91\x10\xed\x18\xae\xf3-\xc0\xdf\xab" +
	"%\xc63\xbe\xe1\x9b\x9f\xa1\xde\x93^\xc5\xb2\x98;\xd1" +
	"H\x86G\x15\xd8\x80\xee\xf6\x90\x12J\xc6\x05\xf0\xa6$" +
	"yT\xf5\x0e\x9e\xa2\x9e;n/\xa11k\x19\xe4 " +
	"5\x18\xf3<\xa3hsN\xd4\x98\xb4\xac\x16\x1c\xd3d" +
	"#\x0eR\x1eN\x83]\x898\xcd\x8e\xb8%($\xac" +
	"}\x9f\x15J\x16'\x09)\x9e\xea\x88\x0b\xed\x82\xf5n" +
	"\xca\xbd\x8f\x06\xb9-I\x80\x0d\xea\x88\x9b\x9e\x02Wc" +
	"XeV\x80wF\xf5\xec\xe0\x01\x1f\x1du\\x\x10" +
	"\xb5`D\xecy\xaf\xed\x19\xc5\x12Q}H\xd3\xa3\xee" +
	"\x97\xe0\xf1h\xc0\x88JqaG\\\xe3\x17+\xcd\x8c" +
	"c\xac\xd5\x117\xda\x04^X\xaf\xf0\x1a\xb6\xbfIE" +
	" \xce\x0f3\xb5\x95\x81\x7fS\x96^2\xd2W\x05\xa5" +
	"\xd2\x01\xee\x1a\x0e\xd5\x91\xa1\x8fB\x1f\x06\x01\xcdf\x95" +
	"\xe6L)\xf41 \xf4\xd1U\x9a+\x839m\x17\xa1" +
	"\x8f\xb5\x88\x90\\I\xa59?\xf2\xbc\xa9\xad\x10\xae\x95" +
	"U\x9a\xbbF\xf9\xb3\xaa#\xa1s\x8b\x1a|\x02\xa9\xfd" +
	"\x8c(\xae\x8e@\x1b\x08\xa3d\x95cJ\xff\xa5\xe8k" +
	"\x8eu\x12\x92{K\xa5\xb9\xf7b\xc2\xf08\xc4\\\xef" +
	"\xaa4\xf7\x89D\x18~\x04\xe0\x87*\xcd\xb7`j\xd4" +
	"!<\x03\xc5\xa46\x8eGZR\xc25\xcc\xc4\xd4(" +
	"N\xbe[O\x0b\\\x03:\xfa3\x00\xff\x12\x95\\\xc3" +
	"\x02\x1c\x1f\xd3\xcf\x09M\xb8\x86z\xfa\xb9=-\\\xc3" +
	"2L\xb2#\xfa9\xe3\x97\xb8\x05\xdb\x14u\x8e\x06\xdb" +
	"d2\xbbXa\xc5\x9aJy\xb3\xea9\xf2K_w" +
	"|j\x8c\x1ax\xf6\xaa\x1dg\xaa\xe5\x8aW\xfa\xba\xe3" +
	"\x1b4xfK\x85$\xc1\xf5\xae2H\xb2\xc8\xbd8" +
	"\xf5.\x07\x85p\x1a\xbbz\x9a\x8c\xdbJ\xc3Cd>" +
	"\xcb\x97\x98K\x12\x86]\x8c\xebVABL\xb2\xde\x95" +
	"e\xbf\xd7\xfe\xcc\xec\xf7\xaa$\xe8^]\xbbBO\xcc" +
	"\xdaFRz;\x88\xeem*\xcd\xdd#\x05\xe8w\x0f" +
	"\x13\x92\xbbK\xa5\xb9}R\x80\xfeK\x97\x90\xdc}*" +
	"\xcd\xed\x8fi\xae\x07\xfb\x82\xf0\xfeE\x89\xe6\x92\xb9\xaf" +
	"\xc9JYX\x81\x887w\xb6\xd9\x80@\xee\x17b\xc8" +
	"\xd4_\xe5\xf8\x98\xaf\x85 \x1b\xe7.+\xf2Ad\x8e" +
	"\xedb\xc4m\xc1/\xbb\xbdz\xb3\x8c\x14t\xfe*\x98" +
	"[b\xb8\x9a\xeePwo\xaf\xede\x8cb\xc9\xc7-" +
	"\xba0\x0a\x8e6\xa1,n\x8c\xd2\xf708\xaa`I" +
	"\"N\xdf\xc3\xe8h7\x122\x98\xbe\xdf#\xd3\x03w" +
	"\xe3<w\x01\xfe\xa8L\x0f\x1c@\xdd\xc04\xfdy\x99" +
	"\x1ex\x8e\xfe\x0c\xdc-\xe0o\xc9\xf4\xc0\x9b\x88\xbf\x05" +
	"x\x8b\"\xd1\x03T\xf96!\x83\x10\xc3\xcdU$v" +
	"`\xb6\x02\xd3\xcf\x05|\xb9\"\xb1\x03\xcb\x94\xc7!&" +
	"\x07|HQ(\x0d\xc8\x81\x1c\xf6$\x0c\x00\xbc\x11\x8b" +
	"\xfa\x8a\x08\x8e6(\xe0\xb4\xd7\x03\xae\x03>c\xba\x08" +
	"\x8e\x186\x13l\x04\xbc\xa4\x80\xad2,\xc3dn\xc8" +
	"\xfd4d\xe1&X\xe5\x01*\x1c\xa7\xd7p\\^\xa5" +
	"\x08\x0a\x02&~\xa8\x89O\x13\x1c\xe7\x90K\x92\xdc\xd6" +
	"\x1b\xc3s\xc7*s\xdf\xf0\xa9\xe3v\x83rx\xaa\x11" +
	"\xa7\xf51\xf9\xb0\xb2\x04\xb9\xb8\x9d(60\x01\xd1\xeb" +
	"\xa9\x1e0\x14\x89\x12\xf7\xa6 9t\x92\xc5\x86\x93\x86" +
	"\xe7\x06x)\x8b\xdb\xd4G+0d\xa8\xe5&s\x08" +
	"\xbaC\x19\xe4\x05\xc7\xb2\xb8\xad\xe3\xd8\xc6\x0d\x11uB" +
	"\x9f\x93\x84.\x090\x96Ptn\x13\xb5\x10\x15\xb72" +
	"\x96\xa3s\xb3\x91\xc6\xa8\xad\xf7\x0e:\xaac\xd5y\xaa" +
	"9\x84\xe46\xaa4W\x92l\x00_\x14\xbb/\x1a\x98" +
	"\x00\xa3/vTQ1h+X\x10S\x94\x8d\xa6L" +
	"\xc8\x9a\xd4\xfc\xa7\xca\xb1\xa6Jt\x07\x13\x8e)\x93/" +
	"\xa2\xad\xe7\x02\xd1&\x84\xbd^\xaa\xa8\xe6\xb6`57" +
	"+\xa6O\x9a\x9c\xe9\x93\x16\xb3Y\x91\xbb\x19\xa6[\x86" +
	"-\xda\x1d>\x83\xd7\xee\xe7Vb\x84\xbbu\xc6\xb2+" +
	"6\x96\x91\xad\\\x14\xf7{EN\xf0\xce\x11\xa9\xe1K" +
	"\xa5b\xa3\xee\xed\x93\x1a\xbeZ\x14a,\xef\x1f\x94\x08" +
	"\x92\xd0X>\x0c\xc6r\xbfJsO*4\x0b.:" +
	"\x8e$\xc3BL\xd4\xdc\x18\xc6\xae\x01\xf1M\x12\x8e\x0d" +
	"\xe1U\xd4\x88\x1e\xc4f[\x1c\xc3\xe6z\xb7/\x97\xd1" +
	"\x0c{\xdc\xa8\xcff\xa3\x10I\x1d\xe7\x8d\xe6R:\x92" +
	"\xb5\x9c\x8d\xf3dH\x88\xcd\xc5\xcf\xee\x17\x84X\xaf8" +
	"\x93nA\x88]&\xb8\xff\x8b\x05\xf7\xbfl\x84\x10\xda" +
	"\x96Z\xd2IH\xdciFH\xd23\x0ac\xf0\x11\x9e" +
	"#\x12\xd8\xaa\xc5 \x99\xc5\xc2w\xb5,\xfd<\xc2]" +
	"x\xb3E\x12\xdc\xf63\x8e_\x92\x09\xb3\xbap&\x12" +
	"\x99\xa0o\xa2\xb3\xa6o\xa2S\xf4M\x0c\x13\x92)V" +
	"\xb8\xe7\x07\x12#\x84\xa4\xeaU\xca\xdc\xed\xd6-\xa2\xc2" +
	"\x7f\x9a\xcbJ\x7f\xd0\x91\"\xea\xffR\xb04'\x0e\x96" +
	"\"\x85:\x0e\x11\xd4;*\xcd}(9\xd5\xf7AP" +
	"\xdeS\xe9`L\xba\xa4>\xed\x91#\xa8\xd0KP\x0a" +
	"\xc2\xf7\x09d\xe82\xe3\xd2\x8a\x1co\x1cX\x85\x81\xd2" +
	"L\x0c\x88\xe2z\x7fB\x15Nb\x162.1\xa3\xd3" +
	"\xde\"\xbcD\x1d\xa3\xf3ys\xaf\xba\xe8=\xce\xbd\xa2" +
	"6\xe7\xb0`\xd8<;\x0a\xe2\xfaZ\x1b\xf7gF\xf5" +
	"S\x19\x8c\xa1D \x9c\xe7\xe3V\xef\x18\xc1\xd3\x9f\x10" +
	"\xa7\xbfU\x18\x0cC\x08'\xefD\xe1\xdc\xd4\x83\xc2\xb9" +
	"n\x98\x10\x9aH\xe5\xe0Y{\xaa\xffZB\xe8\xb4T" +
	"/\xfco:\x12\xaeU\x9d\x8fs\xd3)\x0b\x19\x0c:" +
	"5&\xcb\xae\xa3W\x0a~\xe0\xa2\x0c\x9b\xd0b\xc6c" +
	"&\xf7\xc2\xae\xd2\xaaS\x06Kn8D\xb5\xbd*\xdf" +
	"\xce\x0b\x15\xdf\x18'\x94W\x0b\xae\xe3yk*\xb6R" +
	"\x00u`&\xf1\xb9Uv\\\xe6\xd2\x09\xd8\x1b\xab\x12" +
	"\xc8\xfeT\x81\xdd\xea\x0cflu\xd4\xebp\xb3\x02\xe6" +
	"\x96f\x05L\x99eU\xdb\x84\x14\xca\x01[\x18\xd9\x1d" +
	"\x1c\x91j\x95\xa1\xb1:\x0c\xe0\xab*\xcd\xbd%\x150" +
	"\xdf\x04a\x7fM\xa5\xb9w\xa2\x9e\x8c\xed\x06Q\xfd\x89" +
	"\x9a\xde\xd4\xd5\x1e\xe4b\xa0\xe9q\xd8\xc7\x99\x957\xbe" +
	"\x8dAw\x94z\x81\x97]\xcb!?3i2\xbeJ" +
	"\x15\x88\x14\xf7|\xc3\x12\x1eR\xaalJ\xe8g\x966" +
	"e\xc9Y\xc5&\xf2\x85l\x89\xeb\x95\xc0t\xc4nr" +
	"\x8b\xe4\x11\xc3|nP\xf2\x88\xa1\xf5\x8f<\xe2v\xc9" +
	"MV\xba\x82\x84n\x97\x02\xeePp\xe6$Y\\\xc5" +
	"&j\xbb\xe0NN\xcbgG\\\xce\xc6$& \xba" +
	"\xed\x13\xf4\xbfM\xa5\x0dh\xa2\xd6GA\xed\x06lU" +
	"\x1d\x82\xb0m\xb3\xdc\xaa\xba\x09{:\xe30/\x0cj" +
	"\x19\x86\x85\x9b\x017\xe5VU\x03{Ou\xc0\xcbr" +
	"\xab\xaa\x85aa\x09p_jU\xdd\x8a\xd3\x9b\x00o" +
	"\x97[U+\x18]\xfa\x80\x7fGnU\xdd\x81\xad\xa7" +
	"\xdb\x01\xbfNnU\xfd.\xe2\xd7D\x9d\xb6!A\xbc" +
	"\x17\xe7\xd9\x03\xf8\x1d\x8aD\xf9\xdd\x8e\xcb\xbf-j\x85" +
	"\x0d)\xbf\x07q=\xd8\x0a\xfb\xbc\"Q~\xcf\xe1<" +
	"q\xcb\xebLEP~G \xc6\xce\xbf\x06\xf8;\x80" +
	"\x9f:]P~Gq=o\x00\xfe.\xe0\xc9S\x04" +
	"\xe5w\x0c{^\xdf\x89Zd;f\x08\xca/n\x91" +
	"\x15=\xaf)EP~3\x91J\x8b\x18\xd4\xd4i\xaa" +
	"\xa0\xfcf!\x1eS\xa5Z\x8b\xa0\xfc\xe6!\xc5\x16S" +
	"\xa5\xe9\xcd\x82\xf2;\x1b)\xb6\x98*\x9d5]P~" +
	"\x17 \xc5\x16\xf5\xc8\xfe+\xf6\x9e\x86\x04Dt\xc1'" +
	"\xd0\xce\xf1 \xb3E\xe5O\xc6\x97\xc2\xc4\xe3I\x8c\xc5" +
	"\xa4\xee\xbe\x86\xe6\xd3\xe8.B \xdf\x16\xdb\x8e\x95h" +
	"\xa2\xbaR\x02\xc9\xcb\xcc\xf5\xebX\xb2\x93\xf5\xa5F\xc4" +
	"\x9d\xda\x98E\x88\x9e\x84\x01\x97dE\x8e\x12\xbee\xd2" +
	"\xe2\xbek\x14 \xba\x8a\xaej\x84\xc5\x19\xeeC>\x1a" +
	"4\x9dF\xd7I\xc26\x18Q\xa1\xf1jx\xb1\xe8." +
	"]\xf0]\xff\x96\x1c\x96\x1c']\xd9]\xf1K\xc9\xba" +
	"\xc2f\x10[\x0bW\x89]\x1bjj\x81(lB\xd8" +
	"\x94-:N\xd1\xe4\xd9\xa2\xe1\x97*#U\xcb\x00\x07" +
	"\xe6\x8c\x12\xeaO\xea\x86Wp\\=\xe3\x99\xac06" +
	"U\x0e\xd2\xcf3\xf8\xdf?'\x0d\xe9\x93\x09\xb3\xc0a" +
	"Y=M\x08\xb3\xc1\x980\xfb\x8c\xc6\xd2\xcf\xd5B:" +
	"U\xc8\x97\xcf`\x88#m\x9a(\xcc\\0\x8c\x9bv" +
	"\x9e\xd8\xb4\xb3\xc5\xa6\xcd\x1b$d\xb2l\x82\x18\xe8Q" +
	"W!Q=Ony\xc1\x8e\x1d\xbd\xc2kZ_\xa6" +
	"\xbe\x83\x92\xc7\xf7\x93\xc6S\x13\x95\xa1\xf3zjNm" +
	"\x90\x90\xa0\xd9\xa6j\xd8,\xec\xa6\x9atl\x8c\xe3'" +
	"\xcb\xdc\xd6\x0d\xbbX\xf5*\x1e\xfcX\xf3jYZ@" +
	"Xz\x13\xf6\xa8S\x97\x18\x8d4\xb9\xf4\xf2\xed \x07" +
	"zDr\x8d\x0f\xff0\x88?^\x91\\\xe3\xc1-R" +
	"X\x11\x94\x18S\x87o\x8c#\x88\xe8\xd2\xcbQ7\x0e" +
	"\xac\xabe\xd7\xb0\x98;\xd1M\x12\x15\xbfD\x93\xf1\x95" +
	"\xe5\xc0\xf2`\x07\xef\x80\xeb\x90\xec\xb8\xa1\xd7\xd8\x94\xe8" +
	"\xf2T\xa0{am\x9ebi^\x10w\xd1\xe0\xe8\xd6" +
	"Y\xd8`\xce<o\x9b\xe3\xea$y9\xf3\xe2\xfe\x05" +
	"\x7f\x9b\xb3\x86\x15|\x87\xba\xa2\xc3\\\x97\xdaT\\^" +
	"\x80\xb3\x9d \x99\xd5r\x8f\xdd\x94\xf1\\\x1e\x9bVa" +
	"\x8b\xe7\xe3\xaem\x10y\xd5:!Z9\x91W\xf5\x8f" +
	"\xe0\xc9\xf6\x8a[N\xdd]\x18\xbab\x96\x95\xc0,\xab" +
	"\x0a\x93\x06\xe9Uu\x9c\x99\x86\x1etFTQ\x10\x0d" +
	"\xbbH\xeaC\xd9I\x1f\xa2&\xbb\x985Y\xc5.\x94" +
	"\xaa\x86\x1f\x04\xac\xd4\xaeZ\xcc\x00\xa5a$a\x17\xf8" +
	"\x94\xfdt\x03a\x09\xe5_\xad[\xbd\xee\x05\xddA=" +
	"\xc4\xa6\x18\xee\xce\x8fD\xf0\xa59Rs](\x83\x07" +
	"\xfb$\xc9\x0a\xad\xc7\xe1\xbe8`\x0d\xad\xc7\x9b\x80\xbd" +
	"\xa1\xd2\xdc\xbb \x82\xaa\x10\xc1cgIi\\\xd0\xdd" +
	"\x99:>\"\x91\xdem\xad\"\xdc\xfdhXN\xd9\xc2" +
	"\xea6\x85\xdcl\x10R\xaa\x19\xb5)Uu\xd409" +
	"\xf8[\x99Z\x06\x0c{\xc9\xeb\xb00\x1a\x0e\x0cS\xa2" +
	"\"5\xc76g\xf7+e\xd3az]\xa7_\x0c6" +
	"\xe1A\x1b\xdb\"\x83J\xce\xe7\xdc\xe3\x90(:\xbc(" +
	"\xee_\x8c\xd4\xfcH\x8f\x94(\x84]\xc3ov\xc9j" +
	"\xde\x11\xa8y\x9f\xb4\xf1aJq|P\xda\xf8\xa0w" +
	"6\xf5\xd1\xa0\xb4\xf1\xf2\x0e\x83\xee;\xb5f?\x8cP" +
	"\xa2\xbfX\x10\x84 u\xde \xeb\x0an9n\xden" +
	"\xbc\xae\xf2ySS\xb5\xbe\x95\xc8_\xe9\xa0\xad\x81s" +
	"\xab3\xa5\xc3MLi\x8f\xcc\xc7\x07\xa6\xf4\xee\x9ef" +
	"\x1c\xd3`3\x8e\xa93&\xe9\xc3\xe2{\xea\xc1\x918" +
	"=\x0c\x0c\xe0\xd0\x04Qq\x87\xa2?5\x10\xec\x10\xd3" +
	"u\x97{^\xec?K\xcc\xb0{\xe3\xbew\xc8\x7f\x99" +
	"_q\xa5\xbc%c;v\x81K\x19>~n]\x86" +
	"\x7fr\x0an\xd01)o\xbc\xc77\"\xee\xf1\x0d\xa3" +
	"\x1d\xc1hd\xdc\xe0\xdb\xb8\x0b\xef\xf0]c\xa4B\x12" +
	"\xbe\xe3\x0a{\xc5\x0c\x9b\xa8\xdc\xadg\xfc\xeaR\xa3|" +
	"\x18\xbd\xd5\xb18\x7f-\x09\\x\x14\x1f\xfdLfa" +
	"\xc2\xec\xa8\x15K\x011\x0b\x13fG3\x91\xda\x8f\xcb" +
	"[av4\x1b\xd9\x96\xb8\xbc\x15R\xfe\x0bp|\\" +
	"\xde\x0a\xd3\xa3\x0b\xb0\xa4\x10\x97\xb7\x12m\xc2\xc2,\xc3" +
	"[\x1dQ_\x0d\x0d(\xffn\xac4\xac\x08\xdbd\xaa" +
	":\x1fe\x15\xd3\xff:u|Q\xb7J\x1a\x8eT\xb7" +
	"b\xa6\xe9l[e\xb84\xb8\x08\xc4\x90\x19\x8f\x9d\x17" +
	"\xb2\xdd\xdd\xb4\\v\x9dqf\x92\x9a\x8bS\xdd\x9eg" +
	"\xd0\xa2-\x8eL\xf5\xa5I\xa7\xb8i\x95\xaf\x14\x8b\x94" +
	"{>\x061\x10\xc3\x87\x0fu\xe6\xb3A,\xee\xda\xbe" +
	"\x1c\xb4\xe2\xeaVo\xf7)\xf6\xb6\xe4K,\xe9\xcaU" +
	"0#\xb8\xe3@\xc47En;\xfa\xfb!\xf5yq" +
	"\x9d\xa9\xeb\xcd`\x19\xbc\xce\xd0\xf543t\x9dR\x8b" +
	"Y\xe8L\x0e\x0d\xcb\x96.\xf0&G\x86%\xa3\x16\xb6" +
	"\xad\x1d\xed\x89]L\x90\x0e\xa7\x8e\x0dK\x9c`\x9b*" +
	"\x0c\xdd\xfb\xc31'\x18\xfa\x92\xd4\xa7\x9d\x92\xa1\x9bt" +
	"\xf98\xb7+1\xf3\x0f\xe6\xc5\x8b\xa8\x15>:j\x14" +
	"\x0c,\x0e\xc4|\x8ba\xdb\xcex\xd8\x1b\xf9\xff\xabG" +
	"\xbc!\x90\x89\x83\xe4s\x055\"(XC\xdc\x8e\xe2" +
	"#\xa8\xc4\xac\x0f#\x99M\xc3\x18\xc9l\x10$\\N" +
	"D2H)\xb7\xa7z\xbb\x90\x84\xeb\x1e\x0c;\xc7\xab" +
	"^e\xc42|\xd1+^\x81\x10\x7f\x90\x8f\x93\x84\xc1" +
	"\xb7U\x19\x0a\xaa\xe8\x16\x97c\xed0\xba\xa9i3w" +
	"9\x98\x1a\x1c\x1cu\xa17\x09\xbf\xeb\xd9\x94\xfe\xac\xc8" +
	"\x05\xe1\xcb\x96G\xa4\xca\x04V\xa7\xe3\x1b\x18!\xa9\xb2" +
	"\x13\xd5\xfaz\xc0\xf7\xc8f\xe3f\xfa_\x09\xc9\xef\x01" +
	"\xfc\x0e\xd9l\xdc\x8eU\xeb\xdb\xa2\x0abt\xff\x17\x1b" +
	"\x95\xb1\xd1\xf7\x01\xd9l\xdc\x8f\xe6g\x1f\xe0\x8f\xc8\x95" +
	"\xc2\x87\xf1\xbd\x8f\x00\xfe\xac\xdcH\xfc\x14\xbe\xf7Y\xc0" +
	"_\x96\x1b\x89_\xc2\xc6\xe3\x17\xa3\x86\xe1\xb0Tx\x08" +
	"\xed\xc9+\x80\xbf!7\x12\x1fA\xfc5\xc0\xdf\xc1\x1b" +
	"'m\x82U9\x8a\xe43V(\xdf\x03|FB\xb0" +
	"*\xc7\xd1\xec\xbd\x0b\xf8'\x80\xcfl\x17\xac\xcaG\xf8" +
	"\xbd\x1f\x86\x15\xcd0;\xf7\xe8\xca\xe0\xa4h\xeck\xa2" +
	"g\xbd\xc1\xd1\xaa^C}8,/\xae\xaa\xa03\x8f" +
	"\x05\x1ecb\xefk\xdc&Y,\xaa\xc5\xd3\xe2\x83^" +
	"\xabL\xb1r\x87\x02!]\x03\x13\xaaC\x1d;_p" +
	"\\\x1e]\xb9\x88\xdaz(\xbe%_pT\x97K\x0f" +
	"\x91\xb9-\x88\x87k\\\x9e\xddZ\xe1\xb6\xa4\x92\x10y" +
	"\x17\x82~\xa3\x10\x0bX\xe40\xbd\x0fa\x8f\xf9\x867" +
	"\xca\x0a$Y\xf39e\xee\x1a\x8e\x9e\xf7I\x82\xb9\xd2" +
	"u\x1aDW\xdb`ze\xda`%3\x0b$[\xc1" +
	"\x0a\xecIC\x14\xe4\x04\x06\\\x07\xf3&q\x8fB\xba" +
	":\xd6\x17_\x13\x0bM\xe3\xcea\xe9\x96X\x18\xa0\xec" +
	"\xee\x94\xef\x84\x06A\xe0\xcd\x90\xeb\xdd\xa4\xd2\xdcmR" +
	"\x10x\xeb`\x1c\xf3\xc0\x0e\x04\xef%4\x19\xff\xf1\x95" +
	"\xa8G+x*\xd5\x0fjo.U]>\xear\xaf" +
	"4D\x92\xce\x18\x8f\xa3b\xbe\xbdl\xb8\xdck\x1e\x9f" +
	"\xd5\xa9wt\x8dD\xb5\xbd\xfa\xbb\x02#5\x1e:T" +
	"\xf1\xfa\x06\x94P\xc5\xeb\xef?\x86*~\x19\xaar\xdc" +
	"\xf9\x1a\xaax/\xe2\xd2\xa5\xb2\xd6\xf0RY\xed\xed\x8f" +
	"P\xc5\x19\x9a\x9c\xf8\xf2X\xa8\xe2\x16\xe2e\xc0\xaf\x91" +
	"U|\x02\xe7\x89MT\xa8\xe2;q|l\xa2B\x15" +
	"\xbf\x19\xd7\x8fw\x0en\x93n\x97\x0c\x91\x04gV\xfd" +
	"\x85\x8fFT\xdc\xf7\xc8\xf0\xa1:\xfcdwJz\xed" +
	"q\xc3\x9f\xe2\xd9 \xb7\x9c\xf1\x93\xddE\x89\xee\xb0\xd0" +
	"f\xd7K\x9a>;\xd9\xed\x92\xe0\xf7\x82\x08\xb1\xf6\xf7" +
	"N~\xf3\xa4\xdeadp\xc9\xf5\x9d%]\xf2\xa1\x86" +
	"\xb2\xc4\xb0\xeb:\xbe(\x18(\x94\xc6Q\xc6\xe2\xb3\x0e" +
	"tJ\xb3\xf0>G\x09p\x9f\xc6\xf9\xab\xb6\x15k\x83" +
	"\xb1\x0c\x84}\xb7\x13\xf8\xda\xf8\x02a\x18e\xee@\xf3" +
	"\x1f\xcbF\xd8w\xbb\x13\xcdvt\x810\xea\xd2\xde\x8d" +
	"\xf3\xc7\xf7T\"\x12\x1ee\xe9\x16\xc0\xefBYj\x13" +
	"\xb2t'\xca\x1e6\xc0\xecCw\xd1*\xdc\xc5/\xd1" +
	"\x8d\xdc\x07\xf8~\xd9]<\x88\xeby l\x98i^" +
	"\x09\x0f\xffP\xd6\x14u\xf0\xe8\x0f\xdf\x08.\xb6\xa1\x98" +
	"\x19\xf0\xc6\xaa\x94\xffE\xb5\xcb\xe8\x0f/\x05s\xff?" +
	"\xd5\xd0\xc3\xec\x84\x06\x9e\xc2\xa5\\6\xfa\xa1O\x1bw" +
	"\xcc\xf1\x1a\xe7\xc3\xc4\x9f\x9a1\x08\xfe\x99\x14\xda\x11\xff" +
	"\x89\xc2\xf0\x92\x82\xe3\x8eAj/y\x91\xff\x1b\x00\x00" +
	"\xff\xff\\\xff\xc3\xd0"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_b2c3d4e5f6a70819,
		Nodes: []uint64{
			0x814d9e6a402cc434,
			0x837922dc9e8c3562,
			0x85e4d350feb6fd68,
			0x87b66a6ae914a8e9,
			0x89491628c64b1814,
			0x8a3669ebec0b02bd,
			0x8c2c94f2222b5c64,
			0x90a7329ce01298ae,
			0x9387f2133f217d3c,
			0x9a6043844678585d,
			0x9b92962c9a3b27de,
			0xa0fe6e8d57676609,
			0xa1088a88fc40469f,
			0xa255dd7919106c0c,
			0xa4b4e6f194d209a5,
			0xa80d071edb9da607,
			0xa9b86a0451bd5a8a,
			0xafd590ff5fff524b,
			0xb0b454955c41c3a4,
			0xb102a6bf6c3c7857,
			0xb1fcabe5fd907de6,
			0xb28c543003a65050,
			0xb64281c7019dfd62,
			0xb8d831501c63e997,
			0xb8fa0ec86baf4057,
			0xc0568649b8efe961,
			0xc17c3b2d936938c3,
			0xc1fb3ff6729701cd,
			0xc351440cfe2a0042,
			0xc3acb2ca05db193f,
			0xc4c8084d8d4abb82,
			0xc65d1e648a6ce3dd,
			0xc954f75a49c24db0,
			0xcabbc650870f69c8,
			0xcc1bd4705f3bd585,
			0xd1f3ecea829ed38d,
			0xd1f9c7142aa7af1e,
			0xd48425c627366ce9,
			0xd98357118488407f,
			0xdad96d7bb654f316,
			0xdccccc09f8c007b2,
			0xdd1ffd9305a51c3a,
			0xddce315dbed1cc16,
			0xde7e9b6a39a182e6,
			0xe15a47b1c7942a7f,
			0xe2ab26d5b6b147c6,
			0xe38d4a8ab05a080e,
			0xe3c6275af3a5d82f,
			0xeb138672df728340,
			0xec606f3b72f718f7,
			0xec893de4c6ff71f9,
			0xed88cb4feb86e496,
			0xf1768c1fe3b05d82,
			0xf2ff7e9db806c5c7,
			0xf8486d308d165ff2,
		},
		Compressed: true,
	})
}
