// Code generated by capnpc-go. DO NOT EDIT.

package models

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	math "math"
)

type Project capnp.Struct

// Project_TypeID is the unique identifier for the type Project.
const Project_TypeID = 0x8a3669ebec0b02bd

func NewProject(s *capnp.Segment) (Project, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 12})
	return Project(st), err
}

func NewRootProject(s *capnp.Segment) (Project, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 56, PointerCount: 12})
	return Project(st), err
}

func ReadRootProject(msg *capnp.Message) (Project, error) {
	root, err := msg.Root()
	return Project(root.Struct()), err
}

func (s Project) String() string {
	str, _ := text.Marshal(0x8a3669ebec0b02bd, capnp.Struct(s))
	return str
}

func (s Project) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Project) DecodeFromPtr(p capnp.Ptr) Project {
	return Project(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Project) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Project) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Project) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Project) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Project) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Project) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Project) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Project) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Project) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Project) HasName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Project) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Project) SetName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Project) Description() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Project) HasDescription() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Project) DescriptionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Project) SetDescription(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Project) Avatar() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Project) HasAvatar() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Project) AvatarBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Project) SetAvatar(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Project) Color() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s Project) HasColor() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Project) ColorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s Project) SetColor(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s Project) Status() ProjectStatus {
	return ProjectStatus(capnp.Struct(s).Uint16(0))
}

func (s Project) SetStatus(v ProjectStatus) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s Project) Priority() ProjectPriority {
	return ProjectPriority(capnp.Struct(s).Uint16(2))
}

func (s Project) SetPriority(v ProjectPriority) {
	capnp.Struct(s).SetUint16(2, uint16(v))
}

func (s Project) Owner() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s Project) HasOwner() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Project) OwnerBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s Project) SetOwner(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s Project) Members() (ProjectMember_List, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return ProjectMember_List(p.List()), err
}

func (s Project) HasMembers() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s Project) SetMembers(v ProjectMember_List) error {
	return capnp.Struct(s).SetPtr(6, v.ToPtr())
}

// NewMembers sets the members field to a newly
// allocated ProjectMember_List, preferring placement in s's segment.
func (s Project) NewMembers(n int32) (ProjectMember_List, error) {
	l, err := NewProjectMember_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return ProjectMember_List{}, err
	}
	err = capnp.Struct(s).SetPtr(6, l.ToPtr())
	return l, err
}
func (s Project) TeamIds() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return capnp.TextList(p.List()), err
}

func (s Project) HasTeamIds() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s Project) SetTeamIds(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(7, v.ToPtr())
}

// NewTeamIds sets the teamIds field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s Project) NewTeamIds(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(7, l.ToPtr())
	return l, err
}
func (s Project) Tags() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return capnp.TextList(p.List()), err
}

func (s Project) HasTags() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s Project) SetTags(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(8, v.ToPtr())
}

// NewTags sets the tags field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s Project) NewTags(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(8, l.ToPtr())
	return l, err
}
func (s Project) Category() (string, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return p.Text(), err
}

func (s Project) HasCategory() bool {
	return capnp.Struct(s).HasPtr(9)
}

func (s Project) CategoryBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return p.TextBytes(), err
}

func (s Project) SetCategory(v string) error {
	return capnp.Struct(s).SetText(9, v)
}

func (s Project) IsPublic() bool {
	return capnp.Struct(s).Bit(32)
}

func (s Project) SetIsPublic(v bool) {
	capnp.Struct(s).SetBit(32, v)
}

func (s Project) StartDate() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s Project) SetStartDate(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s Project) EndDate() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s Project) SetEndDate(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

func (s Project) Milestones() (Milestone_List, error) {
	p, err := capnp.Struct(s).Ptr(10)
	return Milestone_List(p.List()), err
}

func (s Project) HasMilestones() bool {
	return capnp.Struct(s).HasPtr(10)
}

func (s Project) SetMilestones(v Milestone_List) error {
	return capnp.Struct(s).SetPtr(10, v.ToPtr())
}

// NewMilestones sets the milestones field to a newly
// allocated Milestone_List, preferring placement in s's segment.
func (s Project) NewMilestones(n int32) (Milestone_List, error) {
	l, err := NewMilestone_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Milestone_List{}, err
	}
	err = capnp.Struct(s).SetPtr(10, l.ToPtr())
	return l, err
}
func (s Project) Progress() (ProjectProgress, error) {
	p, err := capnp.Struct(s).Ptr(11)
	return ProjectProgress(p.Struct()), err
}

func (s Project) HasProgress() bool {
	return capnp.Struct(s).HasPtr(11)
}

func (s Project) SetProgress(v ProjectProgress) error {
	return capnp.Struct(s).SetPtr(11, capnp.Struct(v).ToPtr())
}

// NewProgress sets the progress field to a newly
// allocated ProjectProgress struct, preferring placement in s's segment.
func (s Project) NewProgress() (ProjectProgress, error) {
	ss, err := NewProjectProgress(capnp.Struct(s).Segment())
	if err != nil {
		return ProjectProgress{}, err
	}
	err = capnp.Struct(s).SetPtr(11, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Project) AiEnabled() bool {
	return capnp.Struct(s).Bit(33)
}

func (s Project) SetAiEnabled(v bool) {
	capnp.Struct(s).SetBit(33, v)
}

func (s Project) AutoGenerateIdeas() bool {
	return capnp.Struct(s).Bit(34)
}

func (s Project) SetAutoGenerateIdeas(v bool) {
	capnp.Struct(s).SetBit(34, v)
}

func (s Project) CreatedAt() int64 {
	return int64(capnp.Struct(s).Uint64(24))
}

func (s Project) SetCreatedAt(v int64) {
	capnp.Struct(s).SetUint64(24, uint64(v))
}

func (s Project) UpdatedAt() int64 {
	return int64(capnp.Struct(s).Uint64(32))
}

func (s Project) SetUpdatedAt(v int64) {
	capnp.Struct(s).SetUint64(32, uint64(v))
}

func (s Project) LastActivity() int64 {
	return int64(capnp.Struct(s).Uint64(40))
}

func (s Project) SetLastActivity(v int64) {
	capnp.Struct(s).SetUint64(40, uint64(v))
}

func (s Project) IsArchived() bool {
	return capnp.Struct(s).Bit(35)
}

func (s Project) SetIsArchived(v bool) {
	capnp.Struct(s).SetBit(35, v)
}

func (s Project) Version() int32 {
	return int32(capnp.Struct(s).Uint32(48))
}

func (s Project) SetVersion(v int32) {
	capnp.Struct(s).SetUint32(48, uint32(v))
}

// Project_List is a list of Project.
type Project_List = capnp.StructList[Project]

// NewProject creates a new list of Project.
func NewProject_List(s *capnp.Segment, sz int32) (Project_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 56, PointerCount: 12}, sz)
	return capnp.StructList[Project](l), err
}

// Project_Future is a wrapper for a Project promised by a client call.
type Project_Future struct{ *capnp.Future }

func (f Project_Future) Struct() (Project, error) {
	p, err := f.Future.Ptr()
	return Project(p.Struct()), err
}
func (p Project_Future) Progress() ProjectProgress_Future {
	return ProjectProgress_Future{Future: p.Future.Field(11, nil)}
}

type ProjectStatus uint16

// ProjectStatus_TypeID is the unique identifier for the type ProjectStatus.
const ProjectStatus_TypeID = 0xa4b4e6f194d209a5

// Values of ProjectStatus.
const (
	ProjectStatus_draft     ProjectStatus = 0
	ProjectStatus_active    ProjectStatus = 1
	ProjectStatus_onHold    ProjectStatus = 2
	ProjectStatus_completed ProjectStatus = 3
	ProjectStatus_cancelled ProjectStatus = 4
	ProjectStatus_archived  ProjectStatus = 5
)

// String returns the enum's constant name.
func (c ProjectStatus) String() string {
	switch c {
	case ProjectStatus_draft:
		return "draft"
	case ProjectStatus_active:
		return "active"
	case ProjectStatus_onHold:
		return "onHold"
	case ProjectStatus_completed:
		return "completed"
	case ProjectStatus_cancelled:
		return "cancelled"
	case ProjectStatus_archived:
		return "archived"

	default:
		return ""
	}
}

// ProjectStatusFromString returns the enum value with a name,
// or the zero value if there's no such value.
func ProjectStatusFromString(c string) ProjectStatus {
	switch c {
	case "draft":
		return ProjectStatus_draft
	case "active":
		return ProjectStatus_active
	case "onHold":
		return ProjectStatus_onHold
	case "completed":
		return ProjectStatus_completed
	case "cancelled":
		return ProjectStatus_cancelled
	case "archived":
		return ProjectStatus_archived

	default:
		return 0
	}
}

type ProjectStatus_List = capnp.EnumList[ProjectStatus]

func NewProjectStatus_List(s *capnp.Segment, sz int32) (ProjectStatus_List, error) {
	return capnp.NewEnumList[ProjectStatus](s, sz)
}

type ProjectPriority uint16

// ProjectPriority_TypeID is the unique identifier for the type ProjectPriority.
const ProjectPriority_TypeID = 0x8c2c94f2222b5c64

// Values of ProjectPriority.
const (
	ProjectPriority_low      ProjectPriority = 0
	ProjectPriority_medium   ProjectPriority = 1
	ProjectPriority_high     ProjectPriority = 2
	ProjectPriority_critical ProjectPriority = 3
)

// String returns the enum's constant name.
func (c ProjectPriority) String() string {
	switch c {
	case ProjectPriority_low:
		return "low"
	case ProjectPriority_medium:
		return "medium"
	case ProjectPriority_high:
		return "high"
	case ProjectPriority_critical:
		return "critical"

	default:
		return ""
	}
}

// ProjectPriorityFromString returns the enum value with a name,
// or the zero value if there's no such value.
func ProjectPriorityFromString(c string) ProjectPriority {
	switch c {
	case "low":
		return ProjectPriority_low
	case "medium":
		return ProjectPriority_medium
	case "high":
		return ProjectPriority_high
	case "critical":
		return ProjectPriority_critical

	default:
		return 0
	}
}

type ProjectPriority_List = capnp.EnumList[ProjectPriority]

func NewProjectPriority_List(s *capnp.Segment, sz int32) (ProjectPriority_List, error) {
	return capnp.NewEnumList[ProjectPriority](s, sz)
}

type ProjectMember capnp.Struct

// ProjectMember_TypeID is the unique identifier for the type ProjectMember.
const ProjectMember_TypeID = 0xc3acb2ca05db193f

func NewProjectMember(s *capnp.Segment) (ProjectMember, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3})
	return ProjectMember(st), err
}

func NewRootProjectMember(s *capnp.Segment) (ProjectMember, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3})
	return ProjectMember(st), err
}

func ReadRootProjectMember(msg *capnp.Message) (ProjectMember, error) {
	root, err := msg.Root()
	return ProjectMember(root.Struct()), err
}

func (s ProjectMember) String() string {
	str, _ := text.Marshal(0xc3acb2ca05db193f, capnp.Struct(s))
	return str
}

func (s ProjectMember) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ProjectMember) DecodeFromPtr(p capnp.Ptr) ProjectMember {
	return ProjectMember(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ProjectMember) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ProjectMember) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ProjectMember) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ProjectMember) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ProjectMember) UserId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ProjectMember) HasUserId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ProjectMember) UserIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ProjectMember) SetUserId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ProjectMember) Role() ProjectRole {
	return ProjectRole(capnp.Struct(s).Uint16(0))
}

func (s ProjectMember) SetRole(v ProjectRole) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s ProjectMember) Permissions() (ProjectPermissions, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return ProjectPermissions(p.Struct()), err
}

func (s ProjectMember) HasPermissions() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ProjectMember) SetPermissions(v ProjectPermissions) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewPermissions sets the permissions field to a newly
// allocated ProjectPermissions struct, preferring placement in s's segment.
func (s ProjectMember) NewPermissions() (ProjectPermissions, error) {
	ss, err := NewProjectPermissions(capnp.Struct(s).Segment())
	if err != nil {
		return ProjectPermissions{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s ProjectMember) JoinedAt() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s ProjectMember) SetJoinedAt(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s ProjectMember) InvitedBy() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ProjectMember) HasInvitedBy() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ProjectMember) InvitedByBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ProjectMember) SetInvitedBy(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ProjectMember) LastActive() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s ProjectMember) SetLastActive(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

// ProjectMember_List is a list of ProjectMember.
type ProjectMember_List = capnp.StructList[ProjectMember]

// NewProjectMember creates a new list of ProjectMember.
func NewProjectMember_List(s *capnp.Segment, sz int32) (ProjectMember_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3}, sz)
	return capnp.StructList[ProjectMember](l), err
}

// ProjectMember_Future is a wrapper for a ProjectMember promised by a client call.
type ProjectMember_Future struct{ *capnp.Future }

func (f ProjectMember_Future) Struct() (ProjectMember, error) {
	p, err := f.Future.Ptr()
	return ProjectMember(p.Struct()), err
}
func (p ProjectMember_Future) Permissions() ProjectPermissions_Future {
	return ProjectPermissions_Future{Future: p.Future.Field(1, nil)}
}

type ProjectRole uint16

// ProjectRole_TypeID is the unique identifier for the type ProjectRole.
const ProjectRole_TypeID = 0xe3c6275af3a5d82f

// Values of ProjectRole.
const (
	ProjectRole_viewer      ProjectRole = 0
	ProjectRole_contributor ProjectRole = 1
	ProjectRole_maintainer  ProjectRole = 2
	ProjectRole_owner       ProjectRole = 3
)

// String returns the enum's constant name.
func (c ProjectRole) String() string {
	switch c {
	case ProjectRole_viewer:
		return "viewer"
	case ProjectRole_contributor:
		return "contributor"
	case ProjectRole_maintainer:
		return "maintainer"
	case ProjectRole_owner:
		return "owner"

	default:
		return ""
	}
}

// ProjectRoleFromString returns the enum value with a name,
// or the zero value if there's no such value.
func ProjectRoleFromString(c string) ProjectRole {
	switch c {
	case "viewer":
		return ProjectRole_viewer
	case "contributor":
		return ProjectRole_contributor
	case "maintainer":
		return ProjectRole_maintainer
	case "owner":
		return ProjectRole_owner

	default:
		return 0
	}
}

type ProjectRole_List = capnp.EnumList[ProjectRole]

func NewProjectRole_List(s *capnp.Segment, sz int32) (ProjectRole_List, error) {
	return capnp.NewEnumList[ProjectRole](s, sz)
}

type ProjectPermissions capnp.Struct

// ProjectPermissions_TypeID is the unique identifier for the type ProjectPermissions.
const ProjectPermissions_TypeID = 0xa80d071edb9da607

func NewProjectPermissions(s *capnp.Segment) (ProjectPermissions, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return ProjectPermissions(st), err
}

func NewRootProjectPermissions(s *capnp.Segment) (ProjectPermissions, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return ProjectPermissions(st), err
}

func ReadRootProjectPermissions(msg *capnp.Message) (ProjectPermissions, error) {
	root, err := msg.Root()
	return ProjectPermissions(root.Struct()), err
}

func (s ProjectPermissions) String() string {
	str, _ := text.Marshal(0xa80d071edb9da607, capnp.Struct(s))
	return str
}

func (s ProjectPermissions) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ProjectPermissions) DecodeFromPtr(p capnp.Ptr) ProjectPermissions {
	return ProjectPermissions(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ProjectPermissions) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ProjectPermissions) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ProjectPermissions) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ProjectPermissions) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ProjectPermissions) CanViewProject() bool {
	return capnp.Struct(s).Bit(0)
}

func (s ProjectPermissions) SetCanViewProject(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s ProjectPermissions) CanEditProject() bool {
	return capnp.Struct(s).Bit(1)
}

func (s ProjectPermissions) SetCanEditProject(v bool) {
	capnp.Struct(s).SetBit(1, v)
}

func (s ProjectPermissions) CanDeleteProject() bool {
	return capnp.Struct(s).Bit(2)
}

func (s ProjectPermissions) SetCanDeleteProject(v bool) {
	capnp.Struct(s).SetBit(2, v)
}

func (s ProjectPermissions) CanManageMembers() bool {
	return capnp.Struct(s).Bit(3)
}

func (s ProjectPermissions) SetCanManageMembers(v bool) {
	capnp.Struct(s).SetBit(3, v)
}

func (s ProjectPermissions) CanCreateIdeas() bool {
	return capnp.Struct(s).Bit(4)
}

func (s ProjectPermissions) SetCanCreateIdeas(v bool) {
	capnp.Struct(s).SetBit(4, v)
}

func (s ProjectPermissions) CanEditIdeas() bool {
	return capnp.Struct(s).Bit(5)
}

func (s ProjectPermissions) SetCanEditIdeas(v bool) {
	capnp.Struct(s).SetBit(5, v)
}

func (s ProjectPermissions) CanDeleteIdeas() bool {
	return capnp.Struct(s).Bit(6)
}

func (s ProjectPermissions) SetCanDeleteIdeas(v bool) {
	capnp.Struct(s).SetBit(6, v)
}

func (s ProjectPermissions) CanManageResources() bool {
	return capnp.Struct(s).Bit(7)
}

func (s ProjectPermissions) SetCanManageResources(v bool) {
	capnp.Struct(s).SetBit(7, v)
}

func (s ProjectPermissions) CanViewAnalytics() bool {
	return capnp.Struct(s).Bit(8)
}

func (s ProjectPermissions) SetCanViewAnalytics(v bool) {
	capnp.Struct(s).SetBit(8, v)
}

func (s ProjectPermissions) CanExportData() bool {
	return capnp.Struct(s).Bit(9)
}

func (s ProjectPermissions) SetCanExportData(v bool) {
	capnp.Struct(s).SetBit(9, v)
}

// ProjectPermissions_List is a list of ProjectPermissions.
type ProjectPermissions_List = capnp.StructList[ProjectPermissions]

// NewProjectPermissions creates a new list of ProjectPermissions.
func NewProjectPermissions_List(s *capnp.Segment, sz int32) (ProjectPermissions_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[ProjectPermissions](l), err
}

// ProjectPermissions_Future is a wrapper for a ProjectPermissions promised by a client call.
type ProjectPermissions_Future struct{ *capnp.Future }

func (f ProjectPermissions_Future) Struct() (ProjectPermissions, error) {
	p, err := f.Future.Ptr()
	return ProjectPermissions(p.Struct()), err
}

type Milestone capnp.Struct

// Milestone_TypeID is the unique identifier for the type Milestone.
const Milestone_TypeID = 0xc954f75a49c24db0

func NewMilestone(s *capnp.Segment) (Milestone, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 4})
	return Milestone(st), err
}

func NewRootMilestone(s *capnp.Segment) (Milestone, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 40, PointerCount: 4})
	return Milestone(st), err
}

func ReadRootMilestone(msg *capnp.Message) (Milestone, error) {
	root, err := msg.Root()
	return Milestone(root.Struct()), err
}

func (s Milestone) String() string {
	str, _ := text.Marshal(0xc954f75a49c24db0, capnp.Struct(s))
	return str
}

func (s Milestone) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Milestone) DecodeFromPtr(p capnp.Ptr) Milestone {
	return Milestone(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Milestone) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Milestone) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Milestone) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Milestone) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Milestone) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Milestone) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Milestone) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Milestone) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Milestone) Title() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Milestone) HasTitle() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Milestone) TitleBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Milestone) SetTitle(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Milestone) Description() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Milestone) HasDescription() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Milestone) DescriptionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Milestone) SetDescription(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Milestone) DueDate() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s Milestone) SetDueDate(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s Milestone) Status() MilestoneStatus {
	return MilestoneStatus(capnp.Struct(s).Uint16(8))
}

func (s Milestone) SetStatus(v MilestoneStatus) {
	capnp.Struct(s).SetUint16(8, uint16(v))
}

func (s Milestone) AssigneeId() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Milestone) HasAssigneeId() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Milestone) AssigneeIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Milestone) SetAssigneeId(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Milestone) CompletedAt() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s Milestone) SetCompletedAt(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

func (s Milestone) CreatedAt() int64 {
	return int64(capnp.Struct(s).Uint64(24))
}

func (s Milestone) SetCreatedAt(v int64) {
	capnp.Struct(s).SetUint64(24, uint64(v))
}

func (s Milestone) UpdatedAt() int64 {
	return int64(capnp.Struct(s).Uint64(32))
}

func (s Milestone) SetUpdatedAt(v int64) {
	capnp.Struct(s).SetUint64(32, uint64(v))
}

// Milestone_List is a list of Milestone.
type Milestone_List = capnp.StructList[Milestone]

// NewMilestone creates a new list of Milestone.
func NewMilestone_List(s *capnp.Segment, sz int32) (Milestone_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 40, PointerCount: 4}, sz)
	return capnp.StructList[Milestone](l), err
}

// Milestone_Future is a wrapper for a Milestone promised by a client call.
type Milestone_Future struct{ *capnp.Future }

func (f Milestone_Future) Struct() (Milestone, error) {
	p, err := f.Future.Ptr()
	return Milestone(p.Struct()), err
}

type MilestoneStatus uint16

// MilestoneStatus_TypeID is the unique identifier for the type MilestoneStatus.
const MilestoneStatus_TypeID = 0xdad96d7bb654f316

// Values of MilestoneStatus.
const (
	MilestoneStatus_planned    MilestoneStatus = 0
	MilestoneStatus_inProgress MilestoneStatus = 1
	MilestoneStatus_completed  MilestoneStatus = 2
	MilestoneStatus_overdue    MilestoneStatus = 3
	MilestoneStatus_cancelled  MilestoneStatus = 4
)

// String returns the enum's constant name.
func (c MilestoneStatus) String() string {
	switch c {
	case MilestoneStatus_planned:
		return "planned"
	case MilestoneStatus_inProgress:
		return "inProgress"
	case MilestoneStatus_completed:
		return "completed"
	case MilestoneStatus_overdue:
		return "overdue"
	case MilestoneStatus_cancelled:
		return "cancelled"

	default:
		return ""
	}
}

// MilestoneStatusFromString returns the enum value with a name,
// or the zero value if there's no such value.
func MilestoneStatusFromString(c string) MilestoneStatus {
	switch c {
	case "planned":
		return MilestoneStatus_planned
	case "inProgress":
		return MilestoneStatus_inProgress
	case "completed":
		return MilestoneStatus_completed
	case "overdue":
		return MilestoneStatus_overdue
	case "cancelled":
		return MilestoneStatus_cancelled

	default:
		return 0
	}
}

type MilestoneStatus_List = capnp.EnumList[MilestoneStatus]

func NewMilestoneStatus_List(s *capnp.Segment, sz int32) (MilestoneStatus_List, error) {
	return capnp.NewEnumList[MilestoneStatus](s, sz)
}

type ProjectProgress capnp.Struct

// ProjectProgress_TypeID is the unique identifier for the type ProjectProgress.
const ProjectProgress_TypeID = 0x9b92962c9a3b27de

func NewProjectProgress(s *capnp.Segment) (ProjectProgress, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 0})
	return ProjectProgress(st), err
}

func NewRootProjectProgress(s *capnp.Segment) (ProjectProgress, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 0})
	return ProjectProgress(st), err
}

func ReadRootProjectProgress(msg *capnp.Message) (ProjectProgress, error) {
	root, err := msg.Root()
	return ProjectProgress(root.Struct()), err
}

func (s ProjectProgress) String() string {
	str, _ := text.Marshal(0x9b92962c9a3b27de, capnp.Struct(s))
	return str
}

func (s ProjectProgress) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ProjectProgress) DecodeFromPtr(p capnp.Ptr) ProjectProgress {
	return ProjectProgress(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ProjectProgress) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ProjectProgress) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ProjectProgress) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ProjectProgress) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ProjectProgress) CompletionPercentage() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(0))
}

func (s ProjectProgress) SetCompletionPercentage(v float32) {
	capnp.Struct(s).SetUint32(0, math.Float32bits(v))
}

func (s ProjectProgress) TotalIdeas() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s ProjectProgress) SetTotalIdeas(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

func (s ProjectProgress) CompletedIdeas() int32 {
	return int32(capnp.Struct(s).Uint32(8))
}

func (s ProjectProgress) SetCompletedIdeas(v int32) {
	capnp.Struct(s).SetUint32(8, uint32(v))
}

func (s ProjectProgress) InProgressIdeas() int32 {
	return int32(capnp.Struct(s).Uint32(12))
}

func (s ProjectProgress) SetInProgressIdeas(v int32) {
	capnp.Struct(s).SetUint32(12, uint32(v))
}

func (s ProjectProgress) DaysElapsed() int32 {
	return int32(capnp.Struct(s).Uint32(16))
}

func (s ProjectProgress) SetDaysElapsed(v int32) {
	capnp.Struct(s).SetUint32(16, uint32(v))
}

func (s ProjectProgress) DaysRemaining() int32 {
	return int32(capnp.Struct(s).Uint32(20))
}

func (s ProjectProgress) SetDaysRemaining(v int32) {
	capnp.Struct(s).SetUint32(20, uint32(v))
}

func (s ProjectProgress) IsOnSchedule() bool {
	return capnp.Struct(s).Bit(192)
}

func (s ProjectProgress) SetIsOnSchedule(v bool) {
	capnp.Struct(s).SetBit(192, v)
}

func (s ProjectProgress) WeeklyActivity() int32 {
	return int32(capnp.Struct(s).Uint32(28))
}

func (s ProjectProgress) SetWeeklyActivity(v int32) {
	capnp.Struct(s).SetUint32(28, uint32(v))
}

func (s ProjectProgress) MonthlyActivity() int32 {
	return int32(capnp.Struct(s).Uint32(32))
}

func (s ProjectProgress) SetMonthlyActivity(v int32) {
	capnp.Struct(s).SetUint32(32, uint32(v))
}

func (s ProjectProgress) LastUpdated() int64 {
	return int64(capnp.Struct(s).Uint64(40))
}

func (s ProjectProgress) SetLastUpdated(v int64) {
	capnp.Struct(s).SetUint64(40, uint64(v))
}

// ProjectProgress_List is a list of ProjectProgress.
type ProjectProgress_List = capnp.StructList[ProjectProgress]

// NewProjectProgress creates a new list of ProjectProgress.
func NewProjectProgress_List(s *capnp.Segment, sz int32) (ProjectProgress_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 48, PointerCount: 0}, sz)
	return capnp.StructList[ProjectProgress](l), err
}

// ProjectProgress_Future is a wrapper for a ProjectProgress promised by a client call.
type ProjectProgress_Future struct{ *capnp.Future }

func (f ProjectProgress_Future) Struct() (ProjectProgress, error) {
	p, err := f.Future.Ptr()
	return ProjectProgress(p.Struct()), err
}
