// Code generated by capnpc-go. DO NOT EDIT.

package models

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	math "math"
)

type Team capnp.Struct

// Team_TypeID is the unique identifier for the type Team.
const Team_TypeID = 0xd1f9c7142aa7af1e

func NewTeam(s *capnp.Segment) (Team, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 13})
	return Team(st), err
}

func NewRootTeam(s *capnp.Segment) (Team, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 13})
	return Team(st), err
}

func ReadRootTeam(msg *capnp.Message) (Team, error) {
	root, err := msg.Root()
	return Team(root.Struct()), err
}

func (s Team) String() string {
	str, _ := text.Marshal(0xd1f9c7142aa7af1e, capnp.Struct(s))
	return str
}

func (s Team) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Team) DecodeFromPtr(p capnp.Ptr) Team {
	return Team(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Team) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Team) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Team) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Team) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Team) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Team) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Team) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Team) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Team) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Team) HasName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Team) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Team) SetName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Team) Description() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Team) HasDescription() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Team) DescriptionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Team) SetDescription(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Team) Avatar() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Team) HasAvatar() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Team) AvatarBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Team) SetAvatar(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Team) Color() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s Team) HasColor() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Team) ColorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s Team) SetColor(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s Team) Type() TeamType {
	return TeamType(capnp.Struct(s).Uint16(0))
}

func (s Team) SetType(v TeamType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s Team) Visibility() TeamVisibility {
	return TeamVisibility(capnp.Struct(s).Uint16(2))
}

func (s Team) SetVisibility(v TeamVisibility) {
	capnp.Struct(s).SetUint16(2, uint16(v))
}

func (s Team) OwnerId() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s Team) HasOwnerId() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Team) OwnerIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s Team) SetOwnerId(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s Team) Members() (TeamMember_List, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return TeamMember_List(p.List()), err
}

func (s Team) HasMembers() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s Team) SetMembers(v TeamMember_List) error {
	return capnp.Struct(s).SetPtr(6, v.ToPtr())
}

// NewMembers sets the members field to a newly
// allocated TeamMember_List, preferring placement in s's segment.
func (s Team) NewMembers(n int32) (TeamMember_List, error) {
	l, err := NewTeamMember_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return TeamMember_List{}, err
	}
	err = capnp.Struct(s).SetPtr(6, l.ToPtr())
	return l, err
}
func (s Team) MaxMembers() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s Team) SetMaxMembers(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

func (s Team) Departments() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return capnp.TextList(p.List()), err
}

func (s Team) HasDepartments() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s Team) SetDepartments(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(7, v.ToPtr())
}

// NewDepartments sets the departments field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s Team) NewDepartments(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(7, l.ToPtr())
	return l, err
}
func (s Team) Tags() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return capnp.TextList(p.List()), err
}

func (s Team) HasTags() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s Team) SetTags(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(8, v.ToPtr())
}

// NewTags sets the tags field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s Team) NewTags(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(8, l.ToPtr())
	return l, err
}
func (s Team) ProjectIds() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return capnp.TextList(p.List()), err
}

func (s Team) HasProjectIds() bool {
	return capnp.Struct(s).HasPtr(9)
}

func (s Team) SetProjectIds(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(9, v.ToPtr())
}

// NewProjectIds sets the projectIds field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s Team) NewProjectIds(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(9, l.ToPtr())
	return l, err
}
func (s Team) ActiveProjects() int32 {
	return int32(capnp.Struct(s).Uint32(8))
}

func (s Team) SetActiveProjects(v int32) {
	capnp.Struct(s).SetUint32(8, uint32(v))
}

func (s Team) Metrics() (TeamMetrics, error) {
	p, err := capnp.Struct(s).Ptr(10)
	return TeamMetrics(p.Struct()), err
}

func (s Team) HasMetrics() bool {
	return capnp.Struct(s).HasPtr(10)
}

func (s Team) SetMetrics(v TeamMetrics) error {
	return capnp.Struct(s).SetPtr(10, capnp.Struct(v).ToPtr())
}

// NewMetrics sets the metrics field to a newly
// allocated TeamMetrics struct, preferring placement in s's segment.
func (s Team) NewMetrics() (TeamMetrics, error) {
	ss, err := NewTeamMetrics(capnp.Struct(s).Segment())
	if err != nil {
		return TeamMetrics{}, err
	}
	err = capnp.Struct(s).SetPtr(10, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Team) Settings() (TeamSettings, error) {
	p, err := capnp.Struct(s).Ptr(11)
	return TeamSettings(p.Struct()), err
}

func (s Team) HasSettings() bool {
	return capnp.Struct(s).HasPtr(11)
}

func (s Team) SetSettings(v TeamSettings) error {
	return capnp.Struct(s).SetPtr(11, capnp.Struct(v).ToPtr())
}

// NewSettings sets the settings field to a newly
// allocated TeamSettings struct, preferring placement in s's segment.
func (s Team) NewSettings() (TeamSettings, error) {
	ss, err := NewTeamSettings(capnp.Struct(s).Segment())
	if err != nil {
		return TeamSettings{}, err
	}
	err = capnp.Struct(s).SetPtr(11, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Team) Channels() (TeamChannel_List, error) {
	p, err := capnp.Struct(s).Ptr(12)
	return TeamChannel_List(p.List()), err
}

func (s Team) HasChannels() bool {
	return capnp.Struct(s).HasPtr(12)
}

func (s Team) SetChannels(v TeamChannel_List) error {
	return capnp.Struct(s).SetPtr(12, v.ToPtr())
}

// NewChannels sets the channels field to a newly
// allocated TeamChannel_List, preferring placement in s's segment.
func (s Team) NewChannels(n int32) (TeamChannel_List, error) {
	l, err := NewTeamChannel_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return TeamChannel_List{}, err
	}
	err = capnp.Struct(s).SetPtr(12, l.ToPtr())
	return l, err
}
func (s Team) CreatedAt() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s Team) SetCreatedAt(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

func (s Team) UpdatedAt() int64 {
	return int64(capnp.Struct(s).Uint64(24))
}

func (s Team) SetUpdatedAt(v int64) {
	capnp.Struct(s).SetUint64(24, uint64(v))
}

func (s Team) LastActivity() int64 {
	return int64(capnp.Struct(s).Uint64(32))
}

func (s Team) SetLastActivity(v int64) {
	capnp.Struct(s).SetUint64(32, uint64(v))
}

func (s Team) IsArchived() bool {
	return capnp.Struct(s).Bit(96)
}

func (s Team) SetIsArchived(v bool) {
	capnp.Struct(s).SetBit(96, v)
}

func (s Team) Version() int32 {
	return int32(capnp.Struct(s).Uint32(40))
}

func (s Team) SetVersion(v int32) {
	capnp.Struct(s).SetUint32(40, uint32(v))
}

// Team_List is a list of Team.
type Team_List = capnp.StructList[Team]

// NewTeam creates a new list of Team.
func NewTeam_List(s *capnp.Segment, sz int32) (Team_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 48, PointerCount: 13}, sz)
	return capnp.StructList[Team](l), err
}

// Team_Future is a wrapper for a Team promised by a client call.
type Team_Future struct{ *capnp.Future }

func (f Team_Future) Struct() (Team, error) {
	p, err := f.Future.Ptr()
	return Team(p.Struct()), err
}
func (p Team_Future) Metrics() TeamMetrics_Future {
	return TeamMetrics_Future{Future: p.Future.Field(10, nil)}
}
func (p Team_Future) Settings() TeamSettings_Future {
	return TeamSettings_Future{Future: p.Future.Field(11, nil)}
}

type TeamType uint16

// TeamType_TypeID is the unique identifier for the type TeamType.
const TeamType_TypeID = 0xcabbc650870f69c8

// Values of TeamType.
const (
	TeamType_development     TeamType = 0
	TeamType_design          TeamType = 1
	TeamType_product         TeamType = 2
	TeamType_marketing       TeamType = 3
	TeamType_sales           TeamType = 4
	TeamType_support         TeamType = 5
	TeamType_operations      TeamType = 6
	TeamType_executive       TeamType = 7
	TeamType_crossFunctional TeamType = 8
	TeamType_temporary       TeamType = 9
	TeamType_community       TeamType = 10
)

// String returns the enum's constant name.
func (c TeamType) String() string {
	switch c {
	case TeamType_development:
		return "development"
	case TeamType_design:
		return "design"
	case TeamType_product:
		return "product"
	case TeamType_marketing:
		return "marketing"
	case TeamType_sales:
		return "sales"
	case TeamType_support:
		return "support"
	case TeamType_operations:
		return "operations"
	case TeamType_executive:
		return "executive"
	case TeamType_crossFunctional:
		return "crossFunctional"
	case TeamType_temporary:
		return "temporary"
	case TeamType_community:
		return "community"

	default:
		return ""
	}
}

// TeamTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func TeamTypeFromString(c string) TeamType {
	switch c {
	case "development":
		return TeamType_development
	case "design":
		return TeamType_design
	case "product":
		return TeamType_product
	case "marketing":
		return TeamType_marketing
	case "sales":
		return TeamType_sales
	case "support":
		return TeamType_support
	case "operations":
		return TeamType_operations
	case "executive":
		return TeamType_executive
	case "crossFunctional":
		return TeamType_crossFunctional
	case "temporary":
		return TeamType_temporary
	case "community":
		return TeamType_community

	default:
		return 0
	}
}

type TeamType_List = capnp.EnumList[TeamType]

func NewTeamType_List(s *capnp.Segment, sz int32) (TeamType_List, error) {
	return capnp.NewEnumList[TeamType](s, sz)
}

type TeamVisibility uint16

// TeamVisibility_TypeID is the unique identifier for the type TeamVisibility.
const TeamVisibility_TypeID = 0xb28c543003a65050

// Values of TeamVisibility.
const (
	TeamVisibility_private  TeamVisibility = 0
	TeamVisibility_internal TeamVisibility = 1
	TeamVisibility_public   TeamVisibility = 2
)

// String returns the enum's constant name.
func (c TeamVisibility) String() string {
	switch c {
	case TeamVisibility_private:
		return "private"
	case TeamVisibility_internal:
		return "internal"
	case TeamVisibility_public:
		return "public"

	default:
		return ""
	}
}

// TeamVisibilityFromString returns the enum value with a name,
// or the zero value if there's no such value.
func TeamVisibilityFromString(c string) TeamVisibility {
	switch c {
	case "private":
		return TeamVisibility_private
	case "internal":
		return TeamVisibility_internal
	case "public":
		return TeamVisibility_public

	default:
		return 0
	}
}

type TeamVisibility_List = capnp.EnumList[TeamVisibility]

func NewTeamVisibility_List(s *capnp.Segment, sz int32) (TeamVisibility_List, error) {
	return capnp.NewEnumList[TeamVisibility](s, sz)
}

type TeamMember capnp.Struct

// TeamMember_TypeID is the unique identifier for the type TeamMember.
const TeamMember_TypeID = 0xf8486d308d165ff2

func NewTeamMember(s *capnp.Segment) (TeamMember, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 6})
	return TeamMember(st), err
}

func NewRootTeamMember(s *capnp.Segment) (TeamMember, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 6})
	return TeamMember(st), err
}

func ReadRootTeamMember(msg *capnp.Message) (TeamMember, error) {
	root, err := msg.Root()
	return TeamMember(root.Struct()), err
}

func (s TeamMember) String() string {
	str, _ := text.Marshal(0xf8486d308d165ff2, capnp.Struct(s))
	return str
}

func (s TeamMember) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TeamMember) DecodeFromPtr(p capnp.Ptr) TeamMember {
	return TeamMember(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TeamMember) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TeamMember) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TeamMember) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TeamMember) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TeamMember) UserId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s TeamMember) HasUserId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TeamMember) UserIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s TeamMember) SetUserId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s TeamMember) Role() TeamRole {
	return TeamRole(capnp.Struct(s).Uint16(0))
}

func (s TeamMember) SetRole(v TeamRole) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s TeamMember) Permissions() (TeamPermissions, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return TeamPermissions(p.Struct()), err
}

func (s TeamMember) HasPermissions() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s TeamMember) SetPermissions(v TeamPermissions) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewPermissions sets the permissions field to a newly
// allocated TeamPermissions struct, preferring placement in s's segment.
func (s TeamMember) NewPermissions() (TeamPermissions, error) {
	ss, err := NewTeamPermissions(capnp.Struct(s).Segment())
	if err != nil {
		return TeamPermissions{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s TeamMember) Title() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s TeamMember) HasTitle() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s TeamMember) TitleBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s TeamMember) SetTitle(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s TeamMember) Department() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s TeamMember) HasDepartment() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s TeamMember) DepartmentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s TeamMember) SetDepartment(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s TeamMember) Status() MemberStatus {
	return MemberStatus(capnp.Struct(s).Uint16(2))
}

func (s TeamMember) SetStatus(v MemberStatus) {
	capnp.Struct(s).SetUint16(2, uint16(v))
}

func (s TeamMember) JoinedAt() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s TeamMember) SetJoinedAt(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s TeamMember) InvitedBy() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s TeamMember) HasInvitedBy() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s TeamMember) InvitedByBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s TeamMember) SetInvitedBy(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s TeamMember) LastActive() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s TeamMember) SetLastActive(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

func (s TeamMember) ContributionScore() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s TeamMember) SetContributionScore(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

func (s TeamMember) ProjectsInvolved() int32 {
	return int32(capnp.Struct(s).Uint32(24))
}

func (s TeamMember) SetProjectsInvolved(v int32) {
	capnp.Struct(s).SetUint32(24, uint32(v))
}

func (s TeamMember) Availability() (MemberAvailability, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return MemberAvailability(p.Struct()), err
}

func (s TeamMember) HasAvailability() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s TeamMember) SetAvailability(v MemberAvailability) error {
	return capnp.Struct(s).SetPtr(5, capnp.Struct(v).ToPtr())
}

// NewAvailability sets the availability field to a newly
// allocated MemberAvailability struct, preferring placement in s's segment.
func (s TeamMember) NewAvailability() (MemberAvailability, error) {
	ss, err := NewMemberAvailability(capnp.Struct(s).Segment())
	if err != nil {
		return MemberAvailability{}, err
	}
	err = capnp.Struct(s).SetPtr(5, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s TeamMember) Workload() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(28))
}

func (s TeamMember) SetWorkload(v float32) {
	capnp.Struct(s).SetUint32(28, math.Float32bits(v))
}

// TeamMember_List is a list of TeamMember.
type TeamMember_List = capnp.StructList[TeamMember]

// NewTeamMember creates a new list of TeamMember.
func NewTeamMember_List(s *capnp.Segment, sz int32) (TeamMember_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 6}, sz)
	return capnp.StructList[TeamMember](l), err
}

// TeamMember_Future is a wrapper for a TeamMember promised by a client call.
type TeamMember_Future struct{ *capnp.Future }

func (f TeamMember_Future) Struct() (TeamMember, error) {
	p, err := f.Future.Ptr()
	return TeamMember(p.Struct()), err
}
func (p TeamMember_Future) Permissions() TeamPermissions_Future {
	return TeamPermissions_Future{Future: p.Future.Field(1, nil)}
}
func (p TeamMember_Future) Availability() MemberAvailability_Future {
	return MemberAvailability_Future{Future: p.Future.Field(5, nil)}
}

type TeamRole uint16

// TeamRole_TypeID is the unique identifier for the type TeamRole.
const TeamRole_TypeID = 0xc351440cfe2a0042

// Values of TeamRole.
const (
	TeamRole_member  TeamRole = 0
	TeamRole_lead    TeamRole = 1
	TeamRole_manager TeamRole = 2
	TeamRole_admin   TeamRole = 3
	TeamRole_owner   TeamRole = 4
)

// String returns the enum's constant name.
func (c TeamRole) String() string {
	switch c {
	case TeamRole_member:
		return "member"
	case TeamRole_lead:
		return "lead"
	case TeamRole_manager:
		return "manager"
	case TeamRole_admin:
		return "admin"
	case TeamRole_owner:
		return "owner"

	default:
		return ""
	}
}

// TeamRoleFromString returns the enum value with a name,
// or the zero value if there's no such value.
func TeamRoleFromString(c string) TeamRole {
	switch c {
	case "member":
		return TeamRole_member
	case "lead":
		return TeamRole_lead
	case "manager":
		return TeamRole_manager
	case "admin":
		return TeamRole_admin
	case "owner":
		return TeamRole_owner

	default:
		return 0
	}
}

type TeamRole_List = capnp.EnumList[TeamRole]

func NewTeamRole_List(s *capnp.Segment, sz int32) (TeamRole_List, error) {
	return capnp.NewEnumList[TeamRole](s, sz)
}

type MemberStatus uint16

// MemberStatus_TypeID is the unique identifier for the type MemberStatus.
const MemberStatus_TypeID = 0xdccccc09f8c007b2

// Values of MemberStatus.
const (
	MemberStatus_active    MemberStatus = 0
	MemberStatus_inactive  MemberStatus = 1
	MemberStatus_onLeave   MemberStatus = 2
	MemberStatus_pending   MemberStatus = 3
	MemberStatus_suspended MemberStatus = 4
)

// String returns the enum's constant name.
func (c MemberStatus) String() string {
	switch c {
	case MemberStatus_active:
		return "active"
	case MemberStatus_inactive:
		return "inactive"
	case MemberStatus_onLeave:
		return "onLeave"
	case MemberStatus_pending:
		return "pending"
	case MemberStatus_suspended:
		return "suspended"

	default:
		return ""
	}
}

// MemberStatusFromString returns the enum value with a name,
// or the zero value if there's no such value.
func MemberStatusFromString(c string) MemberStatus {
	switch c {
	case "active":
		return MemberStatus_active
	case "inactive":
		return MemberStatus_inactive
	case "onLeave":
		return MemberStatus_onLeave
	case "pending":
		return MemberStatus_pending
	case "suspended":
		return MemberStatus_suspended

	default:
		return 0
	}
}

type MemberStatus_List = capnp.EnumList[MemberStatus]

func NewMemberStatus_List(s *capnp.Segment, sz int32) (MemberStatus_List, error) {
	return capnp.NewEnumList[MemberStatus](s, sz)
}

type TeamPermissions capnp.Struct

// TeamPermissions_TypeID is the unique identifier for the type TeamPermissions.
const TeamPermissions_TypeID = 0xf2ff7e9db806c5c7

func NewTeamPermissions(s *capnp.Segment) (TeamPermissions, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return TeamPermissions(st), err
}

func NewRootTeamPermissions(s *capnp.Segment) (TeamPermissions, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return TeamPermissions(st), err
}

func ReadRootTeamPermissions(msg *capnp.Message) (TeamPermissions, error) {
	root, err := msg.Root()
	return TeamPermissions(root.Struct()), err
}

func (s TeamPermissions) String() string {
	str, _ := text.Marshal(0xf2ff7e9db806c5c7, capnp.Struct(s))
	return str
}

func (s TeamPermissions) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TeamPermissions) DecodeFromPtr(p capnp.Ptr) TeamPermissions {
	return TeamPermissions(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TeamPermissions) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TeamPermissions) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TeamPermissions) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TeamPermissions) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TeamPermissions) CanViewTeam() bool {
	return capnp.Struct(s).Bit(0)
}

func (s TeamPermissions) SetCanViewTeam(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s TeamPermissions) CanEditTeam() bool {
	return capnp.Struct(s).Bit(1)
}

func (s TeamPermissions) SetCanEditTeam(v bool) {
	capnp.Struct(s).SetBit(1, v)
}

func (s TeamPermissions) CanDeleteTeam() bool {
	return capnp.Struct(s).Bit(2)
}

func (s TeamPermissions) SetCanDeleteTeam(v bool) {
	capnp.Struct(s).SetBit(2, v)
}

func (s TeamPermissions) CanManageMembers() bool {
	return capnp.Struct(s).Bit(3)
}

func (s TeamPermissions) SetCanManageMembers(v bool) {
	capnp.Struct(s).SetBit(3, v)
}

func (s TeamPermissions) CanInviteMembers() bool {
	return capnp.Struct(s).Bit(4)
}

func (s TeamPermissions) SetCanInviteMembers(v bool) {
	capnp.Struct(s).SetBit(4, v)
}

func (s TeamPermissions) CanRemoveMembers() bool {
	return capnp.Struct(s).Bit(5)
}

func (s TeamPermissions) SetCanRemoveMembers(v bool) {
	capnp.Struct(s).SetBit(5, v)
}

func (s TeamPermissions) CanCreateProjects() bool {
	return capnp.Struct(s).Bit(6)
}

func (s TeamPermissions) SetCanCreateProjects(v bool) {
	capnp.Struct(s).SetBit(6, v)
}

func (s TeamPermissions) CanManageProjects() bool {
	return capnp.Struct(s).Bit(7)
}

func (s TeamPermissions) SetCanManageProjects(v bool) {
	capnp.Struct(s).SetBit(7, v)
}

func (s TeamPermissions) CanViewAnalytics() bool {
	return capnp.Struct(s).Bit(8)
}

func (s TeamPermissions) SetCanViewAnalytics(v bool) {
	capnp.Struct(s).SetBit(8, v)
}

func (s TeamPermissions) CanManageSettings() bool {
	return capnp.Struct(s).Bit(9)
}

func (s TeamPermissions) SetCanManageSettings(v bool) {
	capnp.Struct(s).SetBit(9, v)
}

func (s TeamPermissions) CanExportData() bool {
	return capnp.Struct(s).Bit(10)
}

func (s TeamPermissions) SetCanExportData(v bool) {
	capnp.Struct(s).SetBit(10, v)
}

// TeamPermissions_List is a list of TeamPermissions.
type TeamPermissions_List = capnp.StructList[TeamPermissions]

// NewTeamPermissions creates a new list of TeamPermissions.
func NewTeamPermissions_List(s *capnp.Segment, sz int32) (TeamPermissions_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[TeamPermissions](l), err
}

// TeamPermissions_Future is a wrapper for a TeamPermissions promised by a client call.
type TeamPermissions_Future struct{ *capnp.Future }

func (f TeamPermissions_Future) Struct() (TeamPermissions, error) {
	p, err := f.Future.Ptr()
	return TeamPermissions(p.Struct()), err
}

type MemberAvailability capnp.Struct

// MemberAvailability_TypeID is the unique identifier for the type MemberAvailability.
const MemberAvailability_TypeID = 0x85e4d350feb6fd68

func NewMemberAvailability(s *capnp.Segment) (MemberAvailability, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return MemberAvailability(st), err
}

func NewRootMemberAvailability(s *capnp.Segment) (MemberAvailability, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return MemberAvailability(st), err
}

func ReadRootMemberAvailability(msg *capnp.Message) (MemberAvailability, error) {
	root, err := msg.Root()
	return MemberAvailability(root.Struct()), err
}

func (s MemberAvailability) String() string {
	str, _ := text.Marshal(0x85e4d350feb6fd68, capnp.Struct(s))
	return str
}

func (s MemberAvailability) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MemberAvailability) DecodeFromPtr(p capnp.Ptr) MemberAvailability {
	return MemberAvailability(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MemberAvailability) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MemberAvailability) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MemberAvailability) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MemberAvailability) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MemberAvailability) HoursPerWeek() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(0))
}

func (s MemberAvailability) SetHoursPerWeek(v float32) {
	capnp.Struct(s).SetUint32(0, math.Float32bits(v))
}

func (s MemberAvailability) Timezone() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s MemberAvailability) HasTimezone() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MemberAvailability) TimezoneBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s MemberAvailability) SetTimezone(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s MemberAvailability) WorkingHours() (WorkingHours, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return WorkingHours(p.Struct()), err
}

func (s MemberAvailability) HasWorkingHours() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s MemberAvailability) SetWorkingHours(v WorkingHours) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewWorkingHours sets the workingHours field to a newly
// allocated WorkingHours struct, preferring placement in s's segment.
func (s MemberAvailability) NewWorkingHours() (WorkingHours, error) {
	ss, err := NewWorkingHours(capnp.Struct(s).Segment())
	if err != nil {
		return WorkingHours{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s MemberAvailability) VacationDays() (VacationPeriod_List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return VacationPeriod_List(p.List()), err
}

func (s MemberAvailability) HasVacationDays() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s MemberAvailability) SetVacationDays(v VacationPeriod_List) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewVacationDays sets the vacationDays field to a newly
// allocated VacationPeriod_List, preferring placement in s's segment.
func (s MemberAvailability) NewVacationDays(n int32) (VacationPeriod_List, error) {
	l, err := NewVacationPeriod_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return VacationPeriod_List{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s MemberAvailability) IsRemote() bool {
	return capnp.Struct(s).Bit(32)
}

func (s MemberAvailability) SetIsRemote(v bool) {
	capnp.Struct(s).SetBit(32, v)
}

func (s MemberAvailability) Location() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s MemberAvailability) HasLocation() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s MemberAvailability) LocationBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s MemberAvailability) SetLocation(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

// MemberAvailability_List is a list of MemberAvailability.
type MemberAvailability_List = capnp.StructList[MemberAvailability]

// NewMemberAvailability creates a new list of MemberAvailability.
func NewMemberAvailability_List(s *capnp.Segment, sz int32) (MemberAvailability_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[MemberAvailability](l), err
}

// MemberAvailability_Future is a wrapper for a MemberAvailability promised by a client call.
type MemberAvailability_Future struct{ *capnp.Future }

func (f MemberAvailability_Future) Struct() (MemberAvailability, error) {
	p, err := f.Future.Ptr()
	return MemberAvailability(p.Struct()), err
}
func (p MemberAvailability_Future) WorkingHours() WorkingHours_Future {
	return WorkingHours_Future{Future: p.Future.Field(1, nil)}
}

type WorkingHours capnp.Struct

// WorkingHours_TypeID is the unique identifier for the type WorkingHours.
const WorkingHours_TypeID = 0xb102a6bf6c3c7857

func NewWorkingHours(s *capnp.Segment) (WorkingHours, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 7})
	return WorkingHours(st), err
}

func NewRootWorkingHours(s *capnp.Segment) (WorkingHours, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 7})
	return WorkingHours(st), err
}

func ReadRootWorkingHours(msg *capnp.Message) (WorkingHours, error) {
	root, err := msg.Root()
	return WorkingHours(root.Struct()), err
}

func (s WorkingHours) String() string {
	str, _ := text.Marshal(0xb102a6bf6c3c7857, capnp.Struct(s))
	return str
}

func (s WorkingHours) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (WorkingHours) DecodeFromPtr(p capnp.Ptr) WorkingHours {
	return WorkingHours(capnp.Struct{}.DecodeFromPtr(p))
}

func (s WorkingHours) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s WorkingHours) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s WorkingHours) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s WorkingHours) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s WorkingHours) Monday() (DaySchedule, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return DaySchedule(p.Struct()), err
}

func (s WorkingHours) HasMonday() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s WorkingHours) SetMonday(v DaySchedule) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewMonday sets the monday field to a newly
// allocated DaySchedule struct, preferring placement in s's segment.
func (s WorkingHours) NewMonday() (DaySchedule, error) {
	ss, err := NewDaySchedule(capnp.Struct(s).Segment())
	if err != nil {
		return DaySchedule{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s WorkingHours) Tuesday() (DaySchedule, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return DaySchedule(p.Struct()), err
}

func (s WorkingHours) HasTuesday() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s WorkingHours) SetTuesday(v DaySchedule) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewTuesday sets the tuesday field to a newly
// allocated DaySchedule struct, preferring placement in s's segment.
func (s WorkingHours) NewTuesday() (DaySchedule, error) {
	ss, err := NewDaySchedule(capnp.Struct(s).Segment())
	if err != nil {
		return DaySchedule{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s WorkingHours) Wednesday() (DaySchedule, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return DaySchedule(p.Struct()), err
}

func (s WorkingHours) HasWednesday() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s WorkingHours) SetWednesday(v DaySchedule) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewWednesday sets the wednesday field to a newly
// allocated DaySchedule struct, preferring placement in s's segment.
func (s WorkingHours) NewWednesday() (DaySchedule, error) {
	ss, err := NewDaySchedule(capnp.Struct(s).Segment())
	if err != nil {
		return DaySchedule{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s WorkingHours) Thursday() (DaySchedule, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return DaySchedule(p.Struct()), err
}

func (s WorkingHours) HasThursday() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s WorkingHours) SetThursday(v DaySchedule) error {
	return capnp.Struct(s).SetPtr(3, capnp.Struct(v).ToPtr())
}

// NewThursday sets the thursday field to a newly
// allocated DaySchedule struct, preferring placement in s's segment.
func (s WorkingHours) NewThursday() (DaySchedule, error) {
	ss, err := NewDaySchedule(capnp.Struct(s).Segment())
	if err != nil {
		return DaySchedule{}, err
	}
	err = capnp.Struct(s).SetPtr(3, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s WorkingHours) Friday() (DaySchedule, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return DaySchedule(p.Struct()), err
}

func (s WorkingHours) HasFriday() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s WorkingHours) SetFriday(v DaySchedule) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewFriday sets the friday field to a newly
// allocated DaySchedule struct, preferring placement in s's segment.
func (s WorkingHours) NewFriday() (DaySchedule, error) {
	ss, err := NewDaySchedule(capnp.Struct(s).Segment())
	if err != nil {
		return DaySchedule{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s WorkingHours) Saturday() (DaySchedule, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return DaySchedule(p.Struct()), err
}

func (s WorkingHours) HasSaturday() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s WorkingHours) SetSaturday(v DaySchedule) error {
	return capnp.Struct(s).SetPtr(5, capnp.Struct(v).ToPtr())
}

// NewSaturday sets the saturday field to a newly
// allocated DaySchedule struct, preferring placement in s's segment.
func (s WorkingHours) NewSaturday() (DaySchedule, error) {
	ss, err := NewDaySchedule(capnp.Struct(s).Segment())
	if err != nil {
		return DaySchedule{}, err
	}
	err = capnp.Struct(s).SetPtr(5, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s WorkingHours) Sunday() (DaySchedule, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return DaySchedule(p.Struct()), err
}

func (s WorkingHours) HasSunday() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s WorkingHours) SetSunday(v DaySchedule) error {
	return capnp.Struct(s).SetPtr(6, capnp.Struct(v).ToPtr())
}

// NewSunday sets the sunday field to a newly
// allocated DaySchedule struct, preferring placement in s's segment.
func (s WorkingHours) NewSunday() (DaySchedule, error) {
	ss, err := NewDaySchedule(capnp.Struct(s).Segment())
	if err != nil {
		return DaySchedule{}, err
	}
	err = capnp.Struct(s).SetPtr(6, capnp.Struct(ss).ToPtr())
	return ss, err
}

// WorkingHours_List is a list of WorkingHours.
type WorkingHours_List = capnp.StructList[WorkingHours]

// NewWorkingHours creates a new list of WorkingHours.
func NewWorkingHours_List(s *capnp.Segment, sz int32) (WorkingHours_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 7}, sz)
	return capnp.StructList[WorkingHours](l), err
}

// WorkingHours_Future is a wrapper for a WorkingHours promised by a client call.
type WorkingHours_Future struct{ *capnp.Future }

func (f WorkingHours_Future) Struct() (WorkingHours, error) {
	p, err := f.Future.Ptr()
	return WorkingHours(p.Struct()), err
}
func (p WorkingHours_Future) Monday() DaySchedule_Future {
	return DaySchedule_Future{Future: p.Future.Field(0, nil)}
}
func (p WorkingHours_Future) Tuesday() DaySchedule_Future {
	return DaySchedule_Future{Future: p.Future.Field(1, nil)}
}
func (p WorkingHours_Future) Wednesday() DaySchedule_Future {
	return DaySchedule_Future{Future: p.Future.Field(2, nil)}
}
func (p WorkingHours_Future) Thursday() DaySchedule_Future {
	return DaySchedule_Future{Future: p.Future.Field(3, nil)}
}
func (p WorkingHours_Future) Friday() DaySchedule_Future {
	return DaySchedule_Future{Future: p.Future.Field(4, nil)}
}
func (p WorkingHours_Future) Saturday() DaySchedule_Future {
	return DaySchedule_Future{Future: p.Future.Field(5, nil)}
}
func (p WorkingHours_Future) Sunday() DaySchedule_Future {
	return DaySchedule_Future{Future: p.Future.Field(6, nil)}
}

type DaySchedule capnp.Struct

// DaySchedule_TypeID is the unique identifier for the type DaySchedule.
const DaySchedule_TypeID = 0xd1f3ecea829ed38d

func NewDaySchedule(s *capnp.Segment) (DaySchedule, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return DaySchedule(st), err
}

func NewRootDaySchedule(s *capnp.Segment) (DaySchedule, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return DaySchedule(st), err
}

func ReadRootDaySchedule(msg *capnp.Message) (DaySchedule, error) {
	root, err := msg.Root()
	return DaySchedule(root.Struct()), err
}

func (s DaySchedule) String() string {
	str, _ := text.Marshal(0xd1f3ecea829ed38d, capnp.Struct(s))
	return str
}

func (s DaySchedule) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (DaySchedule) DecodeFromPtr(p capnp.Ptr) DaySchedule {
	return DaySchedule(capnp.Struct{}.DecodeFromPtr(p))
}

func (s DaySchedule) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s DaySchedule) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s DaySchedule) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s DaySchedule) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s DaySchedule) IsWorkingDay() bool {
	return capnp.Struct(s).Bit(0)
}

func (s DaySchedule) SetIsWorkingDay(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s DaySchedule) StartTime() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s DaySchedule) HasStartTime() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s DaySchedule) StartTimeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s DaySchedule) SetStartTime(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s DaySchedule) EndTime() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s DaySchedule) HasEndTime() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s DaySchedule) EndTimeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s DaySchedule) SetEndTime(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s DaySchedule) Breaks() (TimeSlot_List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return TimeSlot_List(p.List()), err
}

func (s DaySchedule) HasBreaks() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s DaySchedule) SetBreaks(v TimeSlot_List) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewBreaks sets the breaks field to a newly
// allocated TimeSlot_List, preferring placement in s's segment.
func (s DaySchedule) NewBreaks(n int32) (TimeSlot_List, error) {
	l, err := NewTimeSlot_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return TimeSlot_List{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}

// DaySchedule_List is a list of DaySchedule.
type DaySchedule_List = capnp.StructList[DaySchedule]

// NewDaySchedule creates a new list of DaySchedule.
func NewDaySchedule_List(s *capnp.Segment, sz int32) (DaySchedule_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[DaySchedule](l), err
}

// DaySchedule_Future is a wrapper for a DaySchedule promised by a client call.
type DaySchedule_Future struct{ *capnp.Future }

func (f DaySchedule_Future) Struct() (DaySchedule, error) {
	p, err := f.Future.Ptr()
	return DaySchedule(p.Struct()), err
}

type TimeSlot capnp.Struct

// TimeSlot_TypeID is the unique identifier for the type TimeSlot.
const TimeSlot_TypeID = 0xb0b454955c41c3a4

func NewTimeSlot(s *capnp.Segment) (TimeSlot, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return TimeSlot(st), err
}

func NewRootTimeSlot(s *capnp.Segment) (TimeSlot, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return TimeSlot(st), err
}

func ReadRootTimeSlot(msg *capnp.Message) (TimeSlot, error) {
	root, err := msg.Root()
	return TimeSlot(root.Struct()), err
}

func (s TimeSlot) String() string {
	str, _ := text.Marshal(0xb0b454955c41c3a4, capnp.Struct(s))
	return str
}

func (s TimeSlot) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TimeSlot) DecodeFromPtr(p capnp.Ptr) TimeSlot {
	return TimeSlot(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TimeSlot) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TimeSlot) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TimeSlot) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TimeSlot) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TimeSlot) StartTime() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s TimeSlot) HasStartTime() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TimeSlot) StartTimeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s TimeSlot) SetStartTime(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s TimeSlot) EndTime() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s TimeSlot) HasEndTime() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s TimeSlot) EndTimeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s TimeSlot) SetEndTime(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s TimeSlot) Description() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s TimeSlot) HasDescription() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s TimeSlot) DescriptionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s TimeSlot) SetDescription(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

// TimeSlot_List is a list of TimeSlot.
type TimeSlot_List = capnp.StructList[TimeSlot]

// NewTimeSlot creates a new list of TimeSlot.
func NewTimeSlot_List(s *capnp.Segment, sz int32) (TimeSlot_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[TimeSlot](l), err
}

// TimeSlot_Future is a wrapper for a TimeSlot promised by a client call.
type TimeSlot_Future struct{ *capnp.Future }

func (f TimeSlot_Future) Struct() (TimeSlot, error) {
	p, err := f.Future.Ptr()
	return TimeSlot(p.Struct()), err
}

type VacationPeriod capnp.Struct

// VacationPeriod_TypeID is the unique identifier for the type VacationPeriod.
const VacationPeriod_TypeID = 0xb8d831501c63e997

func NewVacationPeriod(s *capnp.Segment) (VacationPeriod, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return VacationPeriod(st), err
}

func NewRootVacationPeriod(s *capnp.Segment) (VacationPeriod, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return VacationPeriod(st), err
}

func ReadRootVacationPeriod(msg *capnp.Message) (VacationPeriod, error) {
	root, err := msg.Root()
	return VacationPeriod(root.Struct()), err
}

func (s VacationPeriod) String() string {
	str, _ := text.Marshal(0xb8d831501c63e997, capnp.Struct(s))
	return str
}

func (s VacationPeriod) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (VacationPeriod) DecodeFromPtr(p capnp.Ptr) VacationPeriod {
	return VacationPeriod(capnp.Struct{}.DecodeFromPtr(p))
}

func (s VacationPeriod) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s VacationPeriod) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s VacationPeriod) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s VacationPeriod) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s VacationPeriod) StartDate() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s VacationPeriod) SetStartDate(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s VacationPeriod) EndDate() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s VacationPeriod) SetEndDate(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s VacationPeriod) Type() LeaveType {
	return LeaveType(capnp.Struct(s).Uint16(16))
}

func (s VacationPeriod) SetType(v LeaveType) {
	capnp.Struct(s).SetUint16(16, uint16(v))
}

func (s VacationPeriod) Description() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s VacationPeriod) HasDescription() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s VacationPeriod) DescriptionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s VacationPeriod) SetDescription(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// VacationPeriod_List is a list of VacationPeriod.
type VacationPeriod_List = capnp.StructList[VacationPeriod]

// NewVacationPeriod creates a new list of VacationPeriod.
func NewVacationPeriod_List(s *capnp.Segment, sz int32) (VacationPeriod_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1}, sz)
	return capnp.StructList[VacationPeriod](l), err
}

// VacationPeriod_Future is a wrapper for a VacationPeriod promised by a client call.
type VacationPeriod_Future struct{ *capnp.Future }

func (f VacationPeriod_Future) Struct() (VacationPeriod, error) {
	p, err := f.Future.Ptr()
	return VacationPeriod(p.Struct()), err
}

type LeaveType uint16

// LeaveType_TypeID is the unique identifier for the type LeaveType.
const LeaveType_TypeID = 0xc4c8084d8d4abb82

// Values of LeaveType.
const (
	LeaveType_vacation    LeaveType = 0
	LeaveType_sick        LeaveType = 1
	LeaveType_personal    LeaveType = 2
	LeaveType_maternity   LeaveType = 3
	LeaveType_paternity   LeaveType = 4
	LeaveType_bereavement LeaveType = 5
	LeaveType_other       LeaveType = 6
)

// String returns the enum's constant name.
func (c LeaveType) String() string {
	switch c {
	case LeaveType_vacation:
		return "vacation"
	case LeaveType_sick:
		return "sick"
	case LeaveType_personal:
		return "personal"
	case LeaveType_maternity:
		return "maternity"
	case LeaveType_paternity:
		return "paternity"
	case LeaveType_bereavement:
		return "bereavement"
	case LeaveType_other:
		return "other"

	default:
		return ""
	}
}

// LeaveTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func LeaveTypeFromString(c string) LeaveType {
	switch c {
	case "vacation":
		return LeaveType_vacation
	case "sick":
		return LeaveType_sick
	case "personal":
		return LeaveType_personal
	case "maternity":
		return LeaveType_maternity
	case "paternity":
		return LeaveType_paternity
	case "bereavement":
		return LeaveType_bereavement
	case "other":
		return LeaveType_other

	default:
		return 0
	}
}

type LeaveType_List = capnp.EnumList[LeaveType]

func NewLeaveType_List(s *capnp.Segment, sz int32) (LeaveType_List, error) {
	return capnp.NewEnumList[LeaveType](s, sz)
}

type TeamMetrics capnp.Struct

// TeamMetrics_TypeID is the unique identifier for the type TeamMetrics.
const TeamMetrics_TypeID = 0xed88cb4feb86e496

func NewTeamMetrics(s *capnp.Segment) (TeamMetrics, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 72, PointerCount: 0})
	return TeamMetrics(st), err
}

func NewRootTeamMetrics(s *capnp.Segment) (TeamMetrics, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 72, PointerCount: 0})
	return TeamMetrics(st), err
}

func ReadRootTeamMetrics(msg *capnp.Message) (TeamMetrics, error) {
	root, err := msg.Root()
	return TeamMetrics(root.Struct()), err
}

func (s TeamMetrics) String() string {
	str, _ := text.Marshal(0xed88cb4feb86e496, capnp.Struct(s))
	return str
}

func (s TeamMetrics) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TeamMetrics) DecodeFromPtr(p capnp.Ptr) TeamMetrics {
	return TeamMetrics(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TeamMetrics) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TeamMetrics) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TeamMetrics) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TeamMetrics) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TeamMetrics) ProjectsCompleted() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s TeamMetrics) SetProjectsCompleted(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s TeamMetrics) ProjectsInProgress() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s TeamMetrics) SetProjectsInProgress(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

func (s TeamMetrics) AverageProjectDuration() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(8))
}

func (s TeamMetrics) SetAverageProjectDuration(v float32) {
	capnp.Struct(s).SetUint32(8, math.Float32bits(v))
}

func (s TeamMetrics) IdeasGenerated() int32 {
	return int32(capnp.Struct(s).Uint32(12))
}

func (s TeamMetrics) SetIdeasGenerated(v int32) {
	capnp.Struct(s).SetUint32(12, uint32(v))
}

func (s TeamMetrics) IdeasImplemented() int32 {
	return int32(capnp.Struct(s).Uint32(16))
}

func (s TeamMetrics) SetIdeasImplemented(v int32) {
	capnp.Struct(s).SetUint32(16, uint32(v))
}

func (s TeamMetrics) InnovationScore() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(20))
}

func (s TeamMetrics) SetInnovationScore(v float32) {
	capnp.Struct(s).SetUint32(20, math.Float32bits(v))
}

func (s TeamMetrics) CollaborationScore() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(24))
}

func (s TeamMetrics) SetCollaborationScore(v float32) {
	capnp.Struct(s).SetUint32(24, math.Float32bits(v))
}

func (s TeamMetrics) CommunicationFrequency() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(28))
}

func (s TeamMetrics) SetCommunicationFrequency(v float32) {
	capnp.Struct(s).SetUint32(28, math.Float32bits(v))
}

func (s TeamMetrics) Velocity() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(32))
}

func (s TeamMetrics) SetVelocity(v float32) {
	capnp.Struct(s).SetUint32(32, math.Float32bits(v))
}

func (s TeamMetrics) Productivity() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(36))
}

func (s TeamMetrics) SetProductivity(v float32) {
	capnp.Struct(s).SetUint32(36, math.Float32bits(v))
}

func (s TeamMetrics) Satisfaction() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(40))
}

func (s TeamMetrics) SetSatisfaction(v float32) {
	capnp.Struct(s).SetUint32(40, math.Float32bits(v))
}

func (s TeamMetrics) PeriodStart() int64 {
	return int64(capnp.Struct(s).Uint64(48))
}

func (s TeamMetrics) SetPeriodStart(v int64) {
	capnp.Struct(s).SetUint64(48, uint64(v))
}

func (s TeamMetrics) PeriodEnd() int64 {
	return int64(capnp.Struct(s).Uint64(56))
}

func (s TeamMetrics) SetPeriodEnd(v int64) {
	capnp.Struct(s).SetUint64(56, uint64(v))
}

func (s TeamMetrics) LastCalculated() int64 {
	return int64(capnp.Struct(s).Uint64(64))
}

func (s TeamMetrics) SetLastCalculated(v int64) {
	capnp.Struct(s).SetUint64(64, uint64(v))
}

// TeamMetrics_List is a list of TeamMetrics.
type TeamMetrics_List = capnp.StructList[TeamMetrics]

// NewTeamMetrics creates a new list of TeamMetrics.
func NewTeamMetrics_List(s *capnp.Segment, sz int32) (TeamMetrics_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 72, PointerCount: 0}, sz)
	return capnp.StructList[TeamMetrics](l), err
}

// TeamMetrics_Future is a wrapper for a TeamMetrics promised by a client call.
type TeamMetrics_Future struct{ *capnp.Future }

func (f TeamMetrics_Future) Struct() (TeamMetrics, error) {
	p, err := f.Future.Ptr()
	return TeamMetrics(p.Struct()), err
}

type TeamSettings capnp.Struct

// TeamSettings_TypeID is the unique identifier for the type TeamSettings.
const TeamSettings_TypeID = 0xeb138672df728340

func NewTeamSettings(s *capnp.Segment) (TeamSettings, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return TeamSettings(st), err
}

func NewRootTeamSettings(s *capnp.Segment) (TeamSettings, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return TeamSettings(st), err
}

func ReadRootTeamSettings(msg *capnp.Message) (TeamSettings, error) {
	root, err := msg.Root()
	return TeamSettings(root.Struct()), err
}

func (s TeamSettings) String() string {
	str, _ := text.Marshal(0xeb138672df728340, capnp.Struct(s))
	return str
}

func (s TeamSettings) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TeamSettings) DecodeFromPtr(p capnp.Ptr) TeamSettings {
	return TeamSettings(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TeamSettings) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TeamSettings) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TeamSettings) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TeamSettings) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TeamSettings) DefaultNotifications() bool {
	return capnp.Struct(s).Bit(0)
}

func (s TeamSettings) SetDefaultNotifications(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s TeamSettings) AllowDirectMessages() bool {
	return capnp.Struct(s).Bit(1)
}

func (s TeamSettings) SetAllowDirectMessages(v bool) {
	capnp.Struct(s).SetBit(1, v)
}

func (s TeamSettings) RequireApproval() bool {
	return capnp.Struct(s).Bit(2)
}

func (s TeamSettings) SetRequireApproval(v bool) {
	capnp.Struct(s).SetBit(2, v)
}

func (s TeamSettings) AutoAssignProjects() bool {
	return capnp.Struct(s).Bit(3)
}

func (s TeamSettings) SetAutoAssignProjects(v bool) {
	capnp.Struct(s).SetBit(3, v)
}

func (s TeamSettings) AiEnabled() bool {
	return capnp.Struct(s).Bit(4)
}

func (s TeamSettings) SetAiEnabled(v bool) {
	capnp.Struct(s).SetBit(4, v)
}

func (s TeamSettings) AutoSuggestMembers() bool {
	return capnp.Struct(s).Bit(5)
}

func (s TeamSettings) SetAutoSuggestMembers(v bool) {
	capnp.Struct(s).SetBit(5, v)
}

func (s TeamSettings) DataRetention() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s TeamSettings) SetDataRetention(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

func (s TeamSettings) AllowExternalSharing() bool {
	return capnp.Struct(s).Bit(6)
}

func (s TeamSettings) SetAllowExternalSharing(v bool) {
	capnp.Struct(s).SetBit(6, v)
}

func (s TeamSettings) Integrations() (TeamIntegration_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return TeamIntegration_List(p.List()), err
}

func (s TeamSettings) HasIntegrations() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TeamSettings) SetIntegrations(v TeamIntegration_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewIntegrations sets the integrations field to a newly
// allocated TeamIntegration_List, preferring placement in s's segment.
func (s TeamSettings) NewIntegrations(n int32) (TeamIntegration_List, error) {
	l, err := NewTeamIntegration_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return TeamIntegration_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// TeamSettings_List is a list of TeamSettings.
type TeamSettings_List = capnp.StructList[TeamSettings]

// NewTeamSettings creates a new list of TeamSettings.
func NewTeamSettings_List(s *capnp.Segment, sz int32) (TeamSettings_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[TeamSettings](l), err
}

// TeamSettings_Future is a wrapper for a TeamSettings promised by a client call.
type TeamSettings_Future struct{ *capnp.Future }

func (f TeamSettings_Future) Struct() (TeamSettings, error) {
	p, err := f.Future.Ptr()
	return TeamSettings(p.Struct()), err
}

type TeamIntegration capnp.Struct

// TeamIntegration_TypeID is the unique identifier for the type TeamIntegration.
const TeamIntegration_TypeID = 0xa0fe6e8d57676609

func NewTeamIntegration(s *capnp.Segment) (TeamIntegration, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return TeamIntegration(st), err
}

func NewRootTeamIntegration(s *capnp.Segment) (TeamIntegration, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return TeamIntegration(st), err
}

func ReadRootTeamIntegration(msg *capnp.Message) (TeamIntegration, error) {
	root, err := msg.Root()
	return TeamIntegration(root.Struct()), err
}

func (s TeamIntegration) String() string {
	str, _ := text.Marshal(0xa0fe6e8d57676609, capnp.Struct(s))
	return str
}

func (s TeamIntegration) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TeamIntegration) DecodeFromPtr(p capnp.Ptr) TeamIntegration {
	return TeamIntegration(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TeamIntegration) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TeamIntegration) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TeamIntegration) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TeamIntegration) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TeamIntegration) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s TeamIntegration) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TeamIntegration) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s TeamIntegration) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s TeamIntegration) Enabled() bool {
	return capnp.Struct(s).Bit(0)
}

func (s TeamIntegration) SetEnabled(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s TeamIntegration) Configuration() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s TeamIntegration) HasConfiguration() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s TeamIntegration) ConfigurationBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s TeamIntegration) SetConfiguration(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s TeamIntegration) WebhookUrl() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s TeamIntegration) HasWebhookUrl() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s TeamIntegration) WebhookUrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s TeamIntegration) SetWebhookUrl(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s TeamIntegration) LastSync() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s TeamIntegration) SetLastSync(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

// TeamIntegration_List is a list of TeamIntegration.
type TeamIntegration_List = capnp.StructList[TeamIntegration]

// NewTeamIntegration creates a new list of TeamIntegration.
func NewTeamIntegration_List(s *capnp.Segment, sz int32) (TeamIntegration_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3}, sz)
	return capnp.StructList[TeamIntegration](l), err
}

// TeamIntegration_Future is a wrapper for a TeamIntegration promised by a client call.
type TeamIntegration_Future struct{ *capnp.Future }

func (f TeamIntegration_Future) Struct() (TeamIntegration, error) {
	p, err := f.Future.Ptr()
	return TeamIntegration(p.Struct()), err
}

type TeamChannel capnp.Struct

// TeamChannel_TypeID is the unique identifier for the type TeamChannel.
const TeamChannel_TypeID = 0xb1fcabe5fd907de6

func NewTeamChannel(s *capnp.Segment) (TeamChannel, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 5})
	return TeamChannel(st), err
}

func NewRootTeamChannel(s *capnp.Segment) (TeamChannel, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 5})
	return TeamChannel(st), err
}

func ReadRootTeamChannel(msg *capnp.Message) (TeamChannel, error) {
	root, err := msg.Root()
	return TeamChannel(root.Struct()), err
}

func (s TeamChannel) String() string {
	str, _ := text.Marshal(0xb1fcabe5fd907de6, capnp.Struct(s))
	return str
}

func (s TeamChannel) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TeamChannel) DecodeFromPtr(p capnp.Ptr) TeamChannel {
	return TeamChannel(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TeamChannel) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TeamChannel) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TeamChannel) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TeamChannel) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TeamChannel) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s TeamChannel) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TeamChannel) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s TeamChannel) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s TeamChannel) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s TeamChannel) HasName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s TeamChannel) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s TeamChannel) SetName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s TeamChannel) Description() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s TeamChannel) HasDescription() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s TeamChannel) DescriptionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s TeamChannel) SetDescription(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s TeamChannel) Type() ChannelType {
	return ChannelType(capnp.Struct(s).Uint16(0))
}

func (s TeamChannel) SetType(v ChannelType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s TeamChannel) IsPrivate() bool {
	return capnp.Struct(s).Bit(16)
}

func (s TeamChannel) SetIsPrivate(v bool) {
	capnp.Struct(s).SetBit(16, v)
}

func (s TeamChannel) Members() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return capnp.TextList(p.List()), err
}

func (s TeamChannel) HasMembers() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s TeamChannel) SetMembers(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(3, v.ToPtr())
}

// NewMembers sets the members field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s TeamChannel) NewMembers(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(3, l.ToPtr())
	return l, err
}
func (s TeamChannel) CreatedBy() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s TeamChannel) HasCreatedBy() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s TeamChannel) CreatedByBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s TeamChannel) SetCreatedBy(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s TeamChannel) CreatedAt() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s TeamChannel) SetCreatedAt(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s TeamChannel) LastActivity() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s TeamChannel) SetLastActivity(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

func (s TeamChannel) MessageCount() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s TeamChannel) SetMessageCount(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

// TeamChannel_List is a list of TeamChannel.
type TeamChannel_List = capnp.StructList[TeamChannel]

// NewTeamChannel creates a new list of TeamChannel.
func NewTeamChannel_List(s *capnp.Segment, sz int32) (TeamChannel_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 5}, sz)
	return capnp.StructList[TeamChannel](l), err
}

// TeamChannel_Future is a wrapper for a TeamChannel promised by a client call.
type TeamChannel_Future struct{ *capnp.Future }

func (f TeamChannel_Future) Struct() (TeamChannel, error) {
	p, err := f.Future.Ptr()
	return TeamChannel(p.Struct()), err
}

type ChannelType uint16

// ChannelType_TypeID is the unique identifier for the type ChannelType.
const ChannelType_TypeID = 0x837922dc9e8c3562

// Values of ChannelType.
const (
	ChannelType_general       ChannelType = 0
	ChannelType_project       ChannelType = 1
	ChannelType_announcements ChannelType = 2
	ChannelType_random        ChannelType = 3
	ChannelType_support       ChannelType = 4
	ChannelType_ideas         ChannelType = 5
)

// String returns the enum's constant name.
func (c ChannelType) String() string {
	switch c {
	case ChannelType_general:
		return "general"
	case ChannelType_project:
		return "project"
	case ChannelType_announcements:
		return "announcements"
	case ChannelType_random:
		return "random"
	case ChannelType_support:
		return "support"
	case ChannelType_ideas:
		return "ideas"

	default:
		return ""
	}
}

// ChannelTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func ChannelTypeFromString(c string) ChannelType {
	switch c {
	case "general":
		return ChannelType_general
	case "project":
		return ChannelType_project
	case "announcements":
		return ChannelType_announcements
	case "random":
		return ChannelType_random
	case "support":
		return ChannelType_support
	case "ideas":
		return ChannelType_ideas

	default:
		return 0
	}
}

type ChannelType_List = capnp.EnumList[ChannelType]

func NewChannelType_List(s *capnp.Segment, sz int32) (ChannelType_List, error) {
	return capnp.NewEnumList[ChannelType](s, sz)
}
