// Code generated by capnpc-go. DO NOT EDIT.

package models

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
)

type User capnp.Struct

// User_TypeID is the unique identifier for the type User.
const User_TypeID = 0xa1088a88fc40469f

func NewUser(s *capnp.Segment) (User, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 6})
	return User(st), err
}

func NewRootUser(s *capnp.Segment) (User, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 6})
	return User(st), err
}

func ReadRootUser(msg *capnp.Message) (User, error) {
	root, err := msg.Root()
	return User(root.Struct()), err
}

func (s User) String() string {
	str, _ := text.Marshal(0xa1088a88fc40469f, capnp.Struct(s))
	return str
}

func (s User) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (User) DecodeFromPtr(p capnp.Ptr) User {
	return User(capnp.Struct{}.DecodeFromPtr(p))
}

func (s User) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s User) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s User) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s User) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s User) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s User) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s User) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s User) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s User) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s User) HasName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s User) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s User) SetName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s User) Email() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s User) HasEmail() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s User) EmailBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s User) SetEmail(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s User) Avatar() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s User) HasAvatar() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s User) AvatarBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s User) SetAvatar(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s User) Role() UserRole {
	return UserRole(capnp.Struct(s).Uint16(0))
}

func (s User) SetRole(v UserRole) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s User) AuthInfo() (AuthInfo, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return AuthInfo(p.Struct()), err
}

func (s User) HasAuthInfo() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s User) SetAuthInfo(v AuthInfo) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewAuthInfo sets the authInfo field to a newly
// allocated AuthInfo struct, preferring placement in s's segment.
func (s User) NewAuthInfo() (AuthInfo, error) {
	ss, err := NewAuthInfo(capnp.Struct(s).Segment())
	if err != nil {
		return AuthInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s User) CreatedAt() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s User) SetCreatedAt(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s User) UpdatedAt() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s User) SetUpdatedAt(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

func (s User) Preferences() (UserPreferences, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return UserPreferences(p.Struct()), err
}

func (s User) HasPreferences() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s User) SetPreferences(v UserPreferences) error {
	return capnp.Struct(s).SetPtr(5, capnp.Struct(v).ToPtr())
}

// NewPreferences sets the preferences field to a newly
// allocated UserPreferences struct, preferring placement in s's segment.
func (s User) NewPreferences() (UserPreferences, error) {
	ss, err := NewUserPreferences(capnp.Struct(s).Segment())
	if err != nil {
		return UserPreferences{}, err
	}
	err = capnp.Struct(s).SetPtr(5, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s User) IsActive() bool {
	return capnp.Struct(s).Bit(16)
}

func (s User) SetIsActive(v bool) {
	capnp.Struct(s).SetBit(16, v)
}

func (s User) LastLoginAt() int64 {
	return int64(capnp.Struct(s).Uint64(24))
}

func (s User) SetLastLoginAt(v int64) {
	capnp.Struct(s).SetUint64(24, uint64(v))
}

func (s User) EmailVerified() bool {
	return capnp.Struct(s).Bit(17)
}

func (s User) SetEmailVerified(v bool) {
	capnp.Struct(s).SetBit(17, v)
}

// User_List is a list of User.
type User_List = capnp.StructList[User]

// NewUser creates a new list of User.
func NewUser_List(s *capnp.Segment, sz int32) (User_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 6}, sz)
	return capnp.StructList[User](l), err
}

// User_Future is a wrapper for a User promised by a client call.
type User_Future struct{ *capnp.Future }

func (f User_Future) Struct() (User, error) {
	p, err := f.Future.Ptr()
	return User(p.Struct()), err
}
func (p User_Future) AuthInfo() AuthInfo_Future {
	return AuthInfo_Future{Future: p.Future.Field(4, nil)}
}
func (p User_Future) Preferences() UserPreferences_Future {
	return UserPreferences_Future{Future: p.Future.Field(5, nil)}
}

type UserRole uint16

// UserRole_TypeID is the unique identifier for the type UserRole.
const UserRole_TypeID = 0xc65d1e648a6ce3dd

// Values of UserRole.
const (
	UserRole_guest      UserRole = 0
	UserRole_member     UserRole = 1
	UserRole_admin      UserRole = 2
	UserRole_superAdmin UserRole = 3
)

// String returns the enum's constant name.
func (c UserRole) String() string {
	switch c {
	case UserRole_guest:
		return "guest"
	case UserRole_member:
		return "member"
	case UserRole_admin:
		return "admin"
	case UserRole_superAdmin:
		return "superAdmin"

	default:
		return ""
	}
}

// UserRoleFromString returns the enum value with a name,
// or the zero value if there's no such value.
func UserRoleFromString(c string) UserRole {
	switch c {
	case "guest":
		return UserRole_guest
	case "member":
		return UserRole_member
	case "admin":
		return UserRole_admin
	case "superAdmin":
		return UserRole_superAdmin

	default:
		return 0
	}
}

type UserRole_List = capnp.EnumList[UserRole]

func NewUserRole_List(s *capnp.Segment, sz int32) (UserRole_List, error) {
	return capnp.NewEnumList[UserRole](s, sz)
}

type AuthInfo capnp.Struct

// AuthInfo_TypeID is the unique identifier for the type AuthInfo.
const AuthInfo_TypeID = 0xdd1ffd9305a51c3a

func NewAuthInfo(s *capnp.Segment) (AuthInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return AuthInfo(st), err
}

func NewRootAuthInfo(s *capnp.Segment) (AuthInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return AuthInfo(st), err
}

func ReadRootAuthInfo(msg *capnp.Message) (AuthInfo, error) {
	root, err := msg.Root()
	return AuthInfo(root.Struct()), err
}

func (s AuthInfo) String() string {
	str, _ := text.Marshal(0xdd1ffd9305a51c3a, capnp.Struct(s))
	return str
}

func (s AuthInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AuthInfo) DecodeFromPtr(p capnp.Ptr) AuthInfo {
	return AuthInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AuthInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AuthInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AuthInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AuthInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AuthInfo) PrimaryAuth() PrimaryAuth {
	return PrimaryAuth(capnp.Struct(s).Uint16(0))
}

func (s AuthInfo) SetPrimaryAuth(v PrimaryAuth) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s AuthInfo) OauthProviders() (OAuthProvider_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return OAuthProvider_List(p.List()), err
}

func (s AuthInfo) HasOauthProviders() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s AuthInfo) SetOauthProviders(v OAuthProvider_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewOauthProviders sets the oauthProviders field to a newly
// allocated OAuthProvider_List, preferring placement in s's segment.
func (s AuthInfo) NewOauthProviders(n int32) (OAuthProvider_List, error) {
	l, err := NewOAuthProvider_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return OAuthProvider_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s AuthInfo) WalletConnections() (WalletConnection_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return WalletConnection_List(p.List()), err
}

func (s AuthInfo) HasWalletConnections() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s AuthInfo) SetWalletConnections(v WalletConnection_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewWalletConnections sets the walletConnections field to a newly
// allocated WalletConnection_List, preferring placement in s's segment.
func (s AuthInfo) NewWalletConnections(n int32) (WalletConnection_List, error) {
	l, err := NewWalletConnection_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return WalletConnection_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s AuthInfo) PasswordHash() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s AuthInfo) HasPasswordHash() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s AuthInfo) PasswordHashBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s AuthInfo) SetPasswordHash(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s AuthInfo) TwoFactorEnabled() bool {
	return capnp.Struct(s).Bit(16)
}

func (s AuthInfo) SetTwoFactorEnabled(v bool) {
	capnp.Struct(s).SetBit(16, v)
}

func (s AuthInfo) RecoveryEmail() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s AuthInfo) HasRecoveryEmail() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s AuthInfo) RecoveryEmailBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s AuthInfo) SetRecoveryEmail(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

// AuthInfo_List is a list of AuthInfo.
type AuthInfo_List = capnp.StructList[AuthInfo]

// NewAuthInfo creates a new list of AuthInfo.
func NewAuthInfo_List(s *capnp.Segment, sz int32) (AuthInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[AuthInfo](l), err
}

// AuthInfo_Future is a wrapper for a AuthInfo promised by a client call.
type AuthInfo_Future struct{ *capnp.Future }

func (f AuthInfo_Future) Struct() (AuthInfo, error) {
	p, err := f.Future.Ptr()
	return AuthInfo(p.Struct()), err
}

type PrimaryAuth uint16

// PrimaryAuth_TypeID is the unique identifier for the type PrimaryAuth.
const PrimaryAuth_TypeID = 0x9387f2133f217d3c

// Values of PrimaryAuth.
const (
	PrimaryAuth_email  PrimaryAuth = 0
	PrimaryAuth_oauth  PrimaryAuth = 1
	PrimaryAuth_wallet PrimaryAuth = 2
)

// String returns the enum's constant name.
func (c PrimaryAuth) String() string {
	switch c {
	case PrimaryAuth_email:
		return "email"
	case PrimaryAuth_oauth:
		return "oauth"
	case PrimaryAuth_wallet:
		return "wallet"

	default:
		return ""
	}
}

// PrimaryAuthFromString returns the enum value with a name,
// or the zero value if there's no such value.
func PrimaryAuthFromString(c string) PrimaryAuth {
	switch c {
	case "email":
		return PrimaryAuth_email
	case "oauth":
		return PrimaryAuth_oauth
	case "wallet":
		return PrimaryAuth_wallet

	default:
		return 0
	}
}

type PrimaryAuth_List = capnp.EnumList[PrimaryAuth]

func NewPrimaryAuth_List(s *capnp.Segment, sz int32) (PrimaryAuth_List, error) {
	return capnp.NewEnumList[PrimaryAuth](s, sz)
}

type OAuthProvider capnp.Struct

// OAuthProvider_TypeID is the unique identifier for the type OAuthProvider.
const OAuthProvider_TypeID = 0xf1768c1fe3b05d82

func NewOAuthProvider(s *capnp.Segment) (OAuthProvider, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return OAuthProvider(st), err
}

func NewRootOAuthProvider(s *capnp.Segment) (OAuthProvider, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return OAuthProvider(st), err
}

func ReadRootOAuthProvider(msg *capnp.Message) (OAuthProvider, error) {
	root, err := msg.Root()
	return OAuthProvider(root.Struct()), err
}

func (s OAuthProvider) String() string {
	str, _ := text.Marshal(0xf1768c1fe3b05d82, capnp.Struct(s))
	return str
}

func (s OAuthProvider) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (OAuthProvider) DecodeFromPtr(p capnp.Ptr) OAuthProvider {
	return OAuthProvider(capnp.Struct{}.DecodeFromPtr(p))
}

func (s OAuthProvider) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s OAuthProvider) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s OAuthProvider) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s OAuthProvider) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s OAuthProvider) Provider() OAuthType {
	return OAuthType(capnp.Struct(s).Uint16(0))
}

func (s OAuthProvider) SetProvider(v OAuthType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s OAuthProvider) ProviderId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s OAuthProvider) HasProviderId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s OAuthProvider) ProviderIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s OAuthProvider) SetProviderId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s OAuthProvider) Email() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s OAuthProvider) HasEmail() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s OAuthProvider) EmailBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s OAuthProvider) SetEmail(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s OAuthProvider) RefreshToken() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s OAuthProvider) HasRefreshToken() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s OAuthProvider) RefreshTokenBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s OAuthProvider) SetRefreshToken(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s OAuthProvider) ExpiresAt() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s OAuthProvider) SetExpiresAt(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

// OAuthProvider_List is a list of OAuthProvider.
type OAuthProvider_List = capnp.StructList[OAuthProvider]

// NewOAuthProvider creates a new list of OAuthProvider.
func NewOAuthProvider_List(s *capnp.Segment, sz int32) (OAuthProvider_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3}, sz)
	return capnp.StructList[OAuthProvider](l), err
}

// OAuthProvider_Future is a wrapper for a OAuthProvider promised by a client call.
type OAuthProvider_Future struct{ *capnp.Future }

func (f OAuthProvider_Future) Struct() (OAuthProvider, error) {
	p, err := f.Future.Ptr()
	return OAuthProvider(p.Struct()), err
}

type OAuthType uint16

// OAuthType_TypeID is the unique identifier for the type OAuthType.
const OAuthType_TypeID = 0xd48425c627366ce9

// Values of OAuthType.
const (
	OAuthType_google    OAuthType = 0
	OAuthType_github    OAuthType = 1
	OAuthType_microsoft OAuthType = 2
	OAuthType_discord   OAuthType = 3
	OAuthType_slack     OAuthType = 4
)

// String returns the enum's constant name.
func (c OAuthType) String() string {
	switch c {
	case OAuthType_google:
		return "google"
	case OAuthType_github:
		return "github"
	case OAuthType_microsoft:
		return "microsoft"
	case OAuthType_discord:
		return "discord"
	case OAuthType_slack:
		return "slack"

	default:
		return ""
	}
}

// OAuthTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func OAuthTypeFromString(c string) OAuthType {
	switch c {
	case "google":
		return OAuthType_google
	case "github":
		return OAuthType_github
	case "microsoft":
		return OAuthType_microsoft
	case "discord":
		return OAuthType_discord
	case "slack":
		return OAuthType_slack

	default:
		return 0
	}
}

type OAuthType_List = capnp.EnumList[OAuthType]

func NewOAuthType_List(s *capnp.Segment, sz int32) (OAuthType_List, error) {
	return capnp.NewEnumList[OAuthType](s, sz)
}

type WalletConnection capnp.Struct

// WalletConnection_TypeID is the unique identifier for the type WalletConnection.
const WalletConnection_TypeID = 0xe38d4a8ab05a080e

func NewWalletConnection(s *capnp.Segment) (WalletConnection, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return WalletConnection(st), err
}

func NewRootWalletConnection(s *capnp.Segment) (WalletConnection, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return WalletConnection(st), err
}

func ReadRootWalletConnection(msg *capnp.Message) (WalletConnection, error) {
	root, err := msg.Root()
	return WalletConnection(root.Struct()), err
}

func (s WalletConnection) String() string {
	str, _ := text.Marshal(0xe38d4a8ab05a080e, capnp.Struct(s))
	return str
}

func (s WalletConnection) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (WalletConnection) DecodeFromPtr(p capnp.Ptr) WalletConnection {
	return WalletConnection(capnp.Struct{}.DecodeFromPtr(p))
}

func (s WalletConnection) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s WalletConnection) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s WalletConnection) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s WalletConnection) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s WalletConnection) WalletType() WalletType {
	return WalletType(capnp.Struct(s).Uint16(0))
}

func (s WalletConnection) SetWalletType(v WalletType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s WalletConnection) Address() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s WalletConnection) HasAddress() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s WalletConnection) AddressBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s WalletConnection) SetAddress(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s WalletConnection) ChainId() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s WalletConnection) SetChainId(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

func (s WalletConnection) Signature() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s WalletConnection) HasSignature() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s WalletConnection) SignatureBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s WalletConnection) SetSignature(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s WalletConnection) Nonce() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s WalletConnection) HasNonce() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s WalletConnection) NonceBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s WalletConnection) SetNonce(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s WalletConnection) ConnectedAt() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s WalletConnection) SetConnectedAt(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

// WalletConnection_List is a list of WalletConnection.
type WalletConnection_List = capnp.StructList[WalletConnection]

// NewWalletConnection creates a new list of WalletConnection.
func NewWalletConnection_List(s *capnp.Segment, sz int32) (WalletConnection_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3}, sz)
	return capnp.StructList[WalletConnection](l), err
}

// WalletConnection_Future is a wrapper for a WalletConnection promised by a client call.
type WalletConnection_Future struct{ *capnp.Future }

func (f WalletConnection_Future) Struct() (WalletConnection, error) {
	p, err := f.Future.Ptr()
	return WalletConnection(p.Struct()), err
}

type WalletType uint16

// WalletType_TypeID is the unique identifier for the type WalletType.
const WalletType_TypeID = 0xafd590ff5fff524b

// Values of WalletType.
const (
	WalletType_metamask      WalletType = 0
	WalletType_walletConnect WalletType = 1
	WalletType_coinbase      WalletType = 2
	WalletType_phantom       WalletType = 3
	WalletType_ledger        WalletType = 4
)

// String returns the enum's constant name.
func (c WalletType) String() string {
	switch c {
	case WalletType_metamask:
		return "metamask"
	case WalletType_walletConnect:
		return "walletConnect"
	case WalletType_coinbase:
		return "coinbase"
	case WalletType_phantom:
		return "phantom"
	case WalletType_ledger:
		return "ledger"

	default:
		return ""
	}
}

// WalletTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func WalletTypeFromString(c string) WalletType {
	switch c {
	case "metamask":
		return WalletType_metamask
	case "walletConnect":
		return WalletType_walletConnect
	case "coinbase":
		return WalletType_coinbase
	case "phantom":
		return WalletType_phantom
	case "ledger":
		return WalletType_ledger

	default:
		return 0
	}
}

type WalletType_List = capnp.EnumList[WalletType]

func NewWalletType_List(s *capnp.Segment, sz int32) (WalletType_List, error) {
	return capnp.NewEnumList[WalletType](s, sz)
}

type UserPreferences capnp.Struct

// UserPreferences_TypeID is the unique identifier for the type UserPreferences.
const UserPreferences_TypeID = 0xb8fa0ec86baf4057

func NewUserPreferences(s *capnp.Segment) (UserPreferences, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return UserPreferences(st), err
}

func NewRootUserPreferences(s *capnp.Segment) (UserPreferences, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return UserPreferences(st), err
}

func ReadRootUserPreferences(msg *capnp.Message) (UserPreferences, error) {
	root, err := msg.Root()
	return UserPreferences(root.Struct()), err
}

func (s UserPreferences) String() string {
	str, _ := text.Marshal(0xb8fa0ec86baf4057, capnp.Struct(s))
	return str
}

func (s UserPreferences) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UserPreferences) DecodeFromPtr(p capnp.Ptr) UserPreferences {
	return UserPreferences(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UserPreferences) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UserPreferences) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UserPreferences) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UserPreferences) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UserPreferences) Theme() Theme {
	return Theme(capnp.Struct(s).Uint16(0))
}

func (s UserPreferences) SetTheme(v Theme) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s UserPreferences) Language() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s UserPreferences) HasLanguage() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s UserPreferences) LanguageBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s UserPreferences) SetLanguage(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s UserPreferences) Timezone() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s UserPreferences) HasTimezone() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s UserPreferences) TimezoneBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s UserPreferences) SetTimezone(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s UserPreferences) EmailNotifications() bool {
	return capnp.Struct(s).Bit(16)
}

func (s UserPreferences) SetEmailNotifications(v bool) {
	capnp.Struct(s).SetBit(16, v)
}

func (s UserPreferences) PushNotifications() bool {
	return capnp.Struct(s).Bit(17)
}

func (s UserPreferences) SetPushNotifications(v bool) {
	capnp.Struct(s).SetBit(17, v)
}

func (s UserPreferences) WeeklyDigest() bool {
	return capnp.Struct(s).Bit(18)
}

func (s UserPreferences) SetWeeklyDigest(v bool) {
	capnp.Struct(s).SetBit(18, v)
}

func (s UserPreferences) ProfileVisibility() ProfileVisibility {
	return ProfileVisibility(capnp.Struct(s).Uint16(4))
}

func (s UserPreferences) SetProfileVisibility(v ProfileVisibility) {
	capnp.Struct(s).SetUint16(4, uint16(v))
}

func (s UserPreferences) DataSharing() bool {
	return capnp.Struct(s).Bit(19)
}

func (s UserPreferences) SetDataSharing(v bool) {
	capnp.Struct(s).SetBit(19, v)
}

func (s UserPreferences) AnalyticsOptIn() bool {
	return capnp.Struct(s).Bit(20)
}

func (s UserPreferences) SetAnalyticsOptIn(v bool) {
	capnp.Struct(s).SetBit(20, v)
}

// UserPreferences_List is a list of UserPreferences.
type UserPreferences_List = capnp.StructList[UserPreferences]

// NewUserPreferences creates a new list of UserPreferences.
func NewUserPreferences_List(s *capnp.Segment, sz int32) (UserPreferences_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[UserPreferences](l), err
}

// UserPreferences_Future is a wrapper for a UserPreferences promised by a client call.
type UserPreferences_Future struct{ *capnp.Future }

func (f UserPreferences_Future) Struct() (UserPreferences, error) {
	p, err := f.Future.Ptr()
	return UserPreferences(p.Struct()), err
}

type Theme uint16

// Theme_TypeID is the unique identifier for the type Theme.
const Theme_TypeID = 0x814d9e6a402cc434

// Values of Theme.
const (
	Theme_light Theme = 0
	Theme_dark  Theme = 1
	Theme_auto  Theme = 2
)

// String returns the enum's constant name.
func (c Theme) String() string {
	switch c {
	case Theme_light:
		return "light"
	case Theme_dark:
		return "dark"
	case Theme_auto:
		return "auto"

	default:
		return ""
	}
}

// ThemeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func ThemeFromString(c string) Theme {
	switch c {
	case "light":
		return Theme_light
	case "dark":
		return Theme_dark
	case "auto":
		return Theme_auto

	default:
		return 0
	}
}

type Theme_List = capnp.EnumList[Theme]

func NewTheme_List(s *capnp.Segment, sz int32) (Theme_List, error) {
	return capnp.NewEnumList[Theme](s, sz)
}

type ProfileVisibility uint16

// ProfileVisibility_TypeID is the unique identifier for the type ProfileVisibility.
const ProfileVisibility_TypeID = 0x87b66a6ae914a8e9

// Values of ProfileVisibility.
const (
	ProfileVisibility_public  ProfileVisibility = 0
	ProfileVisibility_team    ProfileVisibility = 1
	ProfileVisibility_private ProfileVisibility = 2
)

// String returns the enum's constant name.
func (c ProfileVisibility) String() string {
	switch c {
	case ProfileVisibility_public:
		return "public"
	case ProfileVisibility_team:
		return "team"
	case ProfileVisibility_private:
		return "private"

	default:
		return ""
	}
}

// ProfileVisibilityFromString returns the enum value with a name,
// or the zero value if there's no such value.
func ProfileVisibilityFromString(c string) ProfileVisibility {
	switch c {
	case "public":
		return ProfileVisibility_public
	case "team":
		return ProfileVisibility_team
	case "private":
		return ProfileVisibility_private

	default:
		return 0
	}
}

type ProfileVisibility_List = capnp.EnumList[ProfileVisibility]

func NewProfileVisibility_List(s *capnp.Segment, sz int32) (ProfileVisibility_List, error) {
	return capnp.NewEnumList[ProfileVisibility](s, sz)
}
