// Code generated by capnpc-go. DO NOT EDIT.

package rpc

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type MainInterface capnp.Client

// MainInterface_TypeID is the unique identifier for the type MainInterface.
const MainInterface_TypeID = 0x8a8843cb76f95c84

func (c MainInterface) GetAuthService(ctx context.Context, params func(MainInterface_getAuthService_Params) error) (MainInterface_getAuthService_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a8843cb76f95c84,
			MethodID:      0,
			InterfaceName: "schemas/main_interface.capnp:MainInterface",
			MethodName:    "getAuthService",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(MainInterface_getAuthService_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return MainInterface_getAuthService_Results_Future{Future: ans.Future()}, release

}

func (c MainInterface) GetUserService(ctx context.Context, params func(MainInterface_getUserService_Params) error) (MainInterface_getUserService_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a8843cb76f95c84,
			MethodID:      1,
			InterfaceName: "schemas/main_interface.capnp:MainInterface",
			MethodName:    "getUserService",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(MainInterface_getUserService_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return MainInterface_getUserService_Results_Future{Future: ans.Future()}, release

}

func (c MainInterface) GetProjectService(ctx context.Context, params func(MainInterface_getProjectService_Params) error) (MainInterface_getProjectService_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a8843cb76f95c84,
			MethodID:      2,
			InterfaceName: "schemas/main_interface.capnp:MainInterface",
			MethodName:    "getProjectService",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(MainInterface_getProjectService_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return MainInterface_getProjectService_Results_Future{Future: ans.Future()}, release

}

func (c MainInterface) GetCollaborationService(ctx context.Context, params func(MainInterface_getCollaborationService_Params) error) (MainInterface_getCollaborationService_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a8843cb76f95c84,
			MethodID:      3,
			InterfaceName: "schemas/main_interface.capnp:MainInterface",
			MethodName:    "getCollaborationService",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(MainInterface_getCollaborationService_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return MainInterface_getCollaborationService_Results_Future{Future: ans.Future()}, release

}

func (c MainInterface) GetEventService(ctx context.Context, params func(MainInterface_getEventService_Params) error) (MainInterface_getEventService_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a8843cb76f95c84,
			MethodID:      4,
			InterfaceName: "schemas/main_interface.capnp:MainInterface",
			MethodName:    "getEventService",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(MainInterface_getEventService_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return MainInterface_getEventService_Results_Future{Future: ans.Future()}, release

}

func (c MainInterface) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c MainInterface) String() string {
	return "MainInterface(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c MainInterface) AddRef() MainInterface {
	return MainInterface(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c MainInterface) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c MainInterface) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c MainInterface) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (MainInterface) DecodeFromPtr(p capnp.Ptr) MainInterface {
	return MainInterface(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c MainInterface) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c MainInterface) IsSame(other MainInterface) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c MainInterface) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c MainInterface) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A MainInterface_Server is a MainInterface with a local implementation.
type MainInterface_Server interface {
	GetAuthService(context.Context, MainInterface_getAuthService) error

	GetUserService(context.Context, MainInterface_getUserService) error

	GetProjectService(context.Context, MainInterface_getProjectService) error

	GetCollaborationService(context.Context, MainInterface_getCollaborationService) error

	GetEventService(context.Context, MainInterface_getEventService) error
}

// MainInterface_NewServer creates a new Server from an implementation of MainInterface_Server.
func MainInterface_NewServer(s MainInterface_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(MainInterface_Methods(nil, s), s, c)
}

// MainInterface_ServerToClient creates a new Client from an implementation of MainInterface_Server.
// The caller is responsible for calling Release on the returned Client.
func MainInterface_ServerToClient(s MainInterface_Server) MainInterface {
	return MainInterface(capnp.NewClient(MainInterface_NewServer(s)))
}

// MainInterface_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func MainInterface_Methods(methods []server.Method, s MainInterface_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 5)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a8843cb76f95c84,
			MethodID:      0,
			InterfaceName: "schemas/main_interface.capnp:MainInterface",
			MethodName:    "getAuthService",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetAuthService(ctx, MainInterface_getAuthService{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a8843cb76f95c84,
			MethodID:      1,
			InterfaceName: "schemas/main_interface.capnp:MainInterface",
			MethodName:    "getUserService",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetUserService(ctx, MainInterface_getUserService{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a8843cb76f95c84,
			MethodID:      2,
			InterfaceName: "schemas/main_interface.capnp:MainInterface",
			MethodName:    "getProjectService",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetProjectService(ctx, MainInterface_getProjectService{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a8843cb76f95c84,
			MethodID:      3,
			InterfaceName: "schemas/main_interface.capnp:MainInterface",
			MethodName:    "getCollaborationService",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetCollaborationService(ctx, MainInterface_getCollaborationService{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a8843cb76f95c84,
			MethodID:      4,
			InterfaceName: "schemas/main_interface.capnp:MainInterface",
			MethodName:    "getEventService",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetEventService(ctx, MainInterface_getEventService{call})
		},
	})

	return methods
}

// MainInterface_getAuthService holds the state for a server call to MainInterface.getAuthService.
// See server.Call for documentation.
type MainInterface_getAuthService struct {
	*server.Call
}

// Args returns the call's arguments.
func (c MainInterface_getAuthService) Args() MainInterface_getAuthService_Params {
	return MainInterface_getAuthService_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c MainInterface_getAuthService) AllocResults() (MainInterface_getAuthService_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return MainInterface_getAuthService_Results(r), err
}

// MainInterface_getUserService holds the state for a server call to MainInterface.getUserService.
// See server.Call for documentation.
type MainInterface_getUserService struct {
	*server.Call
}

// Args returns the call's arguments.
func (c MainInterface_getUserService) Args() MainInterface_getUserService_Params {
	return MainInterface_getUserService_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c MainInterface_getUserService) AllocResults() (MainInterface_getUserService_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return MainInterface_getUserService_Results(r), err
}

// MainInterface_getProjectService holds the state for a server call to MainInterface.getProjectService.
// See server.Call for documentation.
type MainInterface_getProjectService struct {
	*server.Call
}

// Args returns the call's arguments.
func (c MainInterface_getProjectService) Args() MainInterface_getProjectService_Params {
	return MainInterface_getProjectService_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c MainInterface_getProjectService) AllocResults() (MainInterface_getProjectService_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return MainInterface_getProjectService_Results(r), err
}

// MainInterface_getCollaborationService holds the state for a server call to MainInterface.getCollaborationService.
// See server.Call for documentation.
type MainInterface_getCollaborationService struct {
	*server.Call
}

// Args returns the call's arguments.
func (c MainInterface_getCollaborationService) Args() MainInterface_getCollaborationService_Params {
	return MainInterface_getCollaborationService_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c MainInterface_getCollaborationService) AllocResults() (MainInterface_getCollaborationService_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return MainInterface_getCollaborationService_Results(r), err
}

// MainInterface_getEventService holds the state for a server call to MainInterface.getEventService.
// See server.Call for documentation.
type MainInterface_getEventService struct {
	*server.Call
}

// Args returns the call's arguments.
func (c MainInterface_getEventService) Args() MainInterface_getEventService_Params {
	return MainInterface_getEventService_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c MainInterface_getEventService) AllocResults() (MainInterface_getEventService_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return MainInterface_getEventService_Results(r), err
}

// MainInterface_List is a list of MainInterface.
type MainInterface_List = capnp.CapList[MainInterface]

// NewMainInterface_List creates a new list of MainInterface.
func NewMainInterface_List(s *capnp.Segment, sz int32) (MainInterface_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[MainInterface](l), err
}

type MainInterface_getAuthService_Params capnp.Struct

// MainInterface_getAuthService_Params_TypeID is the unique identifier for the type MainInterface_getAuthService_Params.
const MainInterface_getAuthService_Params_TypeID = 0xa9cd7c85fa34a151

func NewMainInterface_getAuthService_Params(s *capnp.Segment) (MainInterface_getAuthService_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return MainInterface_getAuthService_Params(st), err
}

func NewRootMainInterface_getAuthService_Params(s *capnp.Segment) (MainInterface_getAuthService_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return MainInterface_getAuthService_Params(st), err
}

func ReadRootMainInterface_getAuthService_Params(msg *capnp.Message) (MainInterface_getAuthService_Params, error) {
	root, err := msg.Root()
	return MainInterface_getAuthService_Params(root.Struct()), err
}

func (s MainInterface_getAuthService_Params) String() string {
	str, _ := text.Marshal(0xa9cd7c85fa34a151, capnp.Struct(s))
	return str
}

func (s MainInterface_getAuthService_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MainInterface_getAuthService_Params) DecodeFromPtr(p capnp.Ptr) MainInterface_getAuthService_Params {
	return MainInterface_getAuthService_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MainInterface_getAuthService_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MainInterface_getAuthService_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MainInterface_getAuthService_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MainInterface_getAuthService_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// MainInterface_getAuthService_Params_List is a list of MainInterface_getAuthService_Params.
type MainInterface_getAuthService_Params_List = capnp.StructList[MainInterface_getAuthService_Params]

// NewMainInterface_getAuthService_Params creates a new list of MainInterface_getAuthService_Params.
func NewMainInterface_getAuthService_Params_List(s *capnp.Segment, sz int32) (MainInterface_getAuthService_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[MainInterface_getAuthService_Params](l), err
}

// MainInterface_getAuthService_Params_Future is a wrapper for a MainInterface_getAuthService_Params promised by a client call.
type MainInterface_getAuthService_Params_Future struct{ *capnp.Future }

func (f MainInterface_getAuthService_Params_Future) Struct() (MainInterface_getAuthService_Params, error) {
	p, err := f.Future.Ptr()
	return MainInterface_getAuthService_Params(p.Struct()), err
}

type MainInterface_getAuthService_Results capnp.Struct

// MainInterface_getAuthService_Results_TypeID is the unique identifier for the type MainInterface_getAuthService_Results.
const MainInterface_getAuthService_Results_TypeID = 0xef3f5c0b14fc9394

func NewMainInterface_getAuthService_Results(s *capnp.Segment) (MainInterface_getAuthService_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return MainInterface_getAuthService_Results(st), err
}

func NewRootMainInterface_getAuthService_Results(s *capnp.Segment) (MainInterface_getAuthService_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return MainInterface_getAuthService_Results(st), err
}

func ReadRootMainInterface_getAuthService_Results(msg *capnp.Message) (MainInterface_getAuthService_Results, error) {
	root, err := msg.Root()
	return MainInterface_getAuthService_Results(root.Struct()), err
}

func (s MainInterface_getAuthService_Results) String() string {
	str, _ := text.Marshal(0xef3f5c0b14fc9394, capnp.Struct(s))
	return str
}

func (s MainInterface_getAuthService_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MainInterface_getAuthService_Results) DecodeFromPtr(p capnp.Ptr) MainInterface_getAuthService_Results {
	return MainInterface_getAuthService_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MainInterface_getAuthService_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MainInterface_getAuthService_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MainInterface_getAuthService_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MainInterface_getAuthService_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MainInterface_getAuthService_Results) Service() AuthService {
	p, _ := capnp.Struct(s).Ptr(0)
	return AuthService(p.Interface().Client())
}

func (s MainInterface_getAuthService_Results) HasService() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MainInterface_getAuthService_Results) SetService(v AuthService) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// MainInterface_getAuthService_Results_List is a list of MainInterface_getAuthService_Results.
type MainInterface_getAuthService_Results_List = capnp.StructList[MainInterface_getAuthService_Results]

// NewMainInterface_getAuthService_Results creates a new list of MainInterface_getAuthService_Results.
func NewMainInterface_getAuthService_Results_List(s *capnp.Segment, sz int32) (MainInterface_getAuthService_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[MainInterface_getAuthService_Results](l), err
}

// MainInterface_getAuthService_Results_Future is a wrapper for a MainInterface_getAuthService_Results promised by a client call.
type MainInterface_getAuthService_Results_Future struct{ *capnp.Future }

func (f MainInterface_getAuthService_Results_Future) Struct() (MainInterface_getAuthService_Results, error) {
	p, err := f.Future.Ptr()
	return MainInterface_getAuthService_Results(p.Struct()), err
}
func (p MainInterface_getAuthService_Results_Future) Service() AuthService {
	return AuthService(p.Future.Field(0, nil).Client())
}

type MainInterface_getUserService_Params capnp.Struct

// MainInterface_getUserService_Params_TypeID is the unique identifier for the type MainInterface_getUserService_Params.
const MainInterface_getUserService_Params_TypeID = 0x8062e5d9993dd5d4

func NewMainInterface_getUserService_Params(s *capnp.Segment) (MainInterface_getUserService_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return MainInterface_getUserService_Params(st), err
}

func NewRootMainInterface_getUserService_Params(s *capnp.Segment) (MainInterface_getUserService_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return MainInterface_getUserService_Params(st), err
}

func ReadRootMainInterface_getUserService_Params(msg *capnp.Message) (MainInterface_getUserService_Params, error) {
	root, err := msg.Root()
	return MainInterface_getUserService_Params(root.Struct()), err
}

func (s MainInterface_getUserService_Params) String() string {
	str, _ := text.Marshal(0x8062e5d9993dd5d4, capnp.Struct(s))
	return str
}

func (s MainInterface_getUserService_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MainInterface_getUserService_Params) DecodeFromPtr(p capnp.Ptr) MainInterface_getUserService_Params {
	return MainInterface_getUserService_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MainInterface_getUserService_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MainInterface_getUserService_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MainInterface_getUserService_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MainInterface_getUserService_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// MainInterface_getUserService_Params_List is a list of MainInterface_getUserService_Params.
type MainInterface_getUserService_Params_List = capnp.StructList[MainInterface_getUserService_Params]

// NewMainInterface_getUserService_Params creates a new list of MainInterface_getUserService_Params.
func NewMainInterface_getUserService_Params_List(s *capnp.Segment, sz int32) (MainInterface_getUserService_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[MainInterface_getUserService_Params](l), err
}

// MainInterface_getUserService_Params_Future is a wrapper for a MainInterface_getUserService_Params promised by a client call.
type MainInterface_getUserService_Params_Future struct{ *capnp.Future }

func (f MainInterface_getUserService_Params_Future) Struct() (MainInterface_getUserService_Params, error) {
	p, err := f.Future.Ptr()
	return MainInterface_getUserService_Params(p.Struct()), err
}

type MainInterface_getUserService_Results capnp.Struct

// MainInterface_getUserService_Results_TypeID is the unique identifier for the type MainInterface_getUserService_Results.
const MainInterface_getUserService_Results_TypeID = 0x9065a50fa79ae66a

func NewMainInterface_getUserService_Results(s *capnp.Segment) (MainInterface_getUserService_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return MainInterface_getUserService_Results(st), err
}

func NewRootMainInterface_getUserService_Results(s *capnp.Segment) (MainInterface_getUserService_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return MainInterface_getUserService_Results(st), err
}

func ReadRootMainInterface_getUserService_Results(msg *capnp.Message) (MainInterface_getUserService_Results, error) {
	root, err := msg.Root()
	return MainInterface_getUserService_Results(root.Struct()), err
}

func (s MainInterface_getUserService_Results) String() string {
	str, _ := text.Marshal(0x9065a50fa79ae66a, capnp.Struct(s))
	return str
}

func (s MainInterface_getUserService_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MainInterface_getUserService_Results) DecodeFromPtr(p capnp.Ptr) MainInterface_getUserService_Results {
	return MainInterface_getUserService_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MainInterface_getUserService_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MainInterface_getUserService_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MainInterface_getUserService_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MainInterface_getUserService_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MainInterface_getUserService_Results) Service() UserService {
	p, _ := capnp.Struct(s).Ptr(0)
	return UserService(p.Interface().Client())
}

func (s MainInterface_getUserService_Results) HasService() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MainInterface_getUserService_Results) SetService(v UserService) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// MainInterface_getUserService_Results_List is a list of MainInterface_getUserService_Results.
type MainInterface_getUserService_Results_List = capnp.StructList[MainInterface_getUserService_Results]

// NewMainInterface_getUserService_Results creates a new list of MainInterface_getUserService_Results.
func NewMainInterface_getUserService_Results_List(s *capnp.Segment, sz int32) (MainInterface_getUserService_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[MainInterface_getUserService_Results](l), err
}

// MainInterface_getUserService_Results_Future is a wrapper for a MainInterface_getUserService_Results promised by a client call.
type MainInterface_getUserService_Results_Future struct{ *capnp.Future }

func (f MainInterface_getUserService_Results_Future) Struct() (MainInterface_getUserService_Results, error) {
	p, err := f.Future.Ptr()
	return MainInterface_getUserService_Results(p.Struct()), err
}
func (p MainInterface_getUserService_Results_Future) Service() UserService {
	return UserService(p.Future.Field(0, nil).Client())
}

type MainInterface_getProjectService_Params capnp.Struct

// MainInterface_getProjectService_Params_TypeID is the unique identifier for the type MainInterface_getProjectService_Params.
const MainInterface_getProjectService_Params_TypeID = 0xf96844903c020a29

func NewMainInterface_getProjectService_Params(s *capnp.Segment) (MainInterface_getProjectService_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return MainInterface_getProjectService_Params(st), err
}

func NewRootMainInterface_getProjectService_Params(s *capnp.Segment) (MainInterface_getProjectService_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return MainInterface_getProjectService_Params(st), err
}

func ReadRootMainInterface_getProjectService_Params(msg *capnp.Message) (MainInterface_getProjectService_Params, error) {
	root, err := msg.Root()
	return MainInterface_getProjectService_Params(root.Struct()), err
}

func (s MainInterface_getProjectService_Params) String() string {
	str, _ := text.Marshal(0xf96844903c020a29, capnp.Struct(s))
	return str
}

func (s MainInterface_getProjectService_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MainInterface_getProjectService_Params) DecodeFromPtr(p capnp.Ptr) MainInterface_getProjectService_Params {
	return MainInterface_getProjectService_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MainInterface_getProjectService_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MainInterface_getProjectService_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MainInterface_getProjectService_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MainInterface_getProjectService_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// MainInterface_getProjectService_Params_List is a list of MainInterface_getProjectService_Params.
type MainInterface_getProjectService_Params_List = capnp.StructList[MainInterface_getProjectService_Params]

// NewMainInterface_getProjectService_Params creates a new list of MainInterface_getProjectService_Params.
func NewMainInterface_getProjectService_Params_List(s *capnp.Segment, sz int32) (MainInterface_getProjectService_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[MainInterface_getProjectService_Params](l), err
}

// MainInterface_getProjectService_Params_Future is a wrapper for a MainInterface_getProjectService_Params promised by a client call.
type MainInterface_getProjectService_Params_Future struct{ *capnp.Future }

func (f MainInterface_getProjectService_Params_Future) Struct() (MainInterface_getProjectService_Params, error) {
	p, err := f.Future.Ptr()
	return MainInterface_getProjectService_Params(p.Struct()), err
}

type MainInterface_getProjectService_Results capnp.Struct

// MainInterface_getProjectService_Results_TypeID is the unique identifier for the type MainInterface_getProjectService_Results.
const MainInterface_getProjectService_Results_TypeID = 0x81cee22b1a1e7d87

func NewMainInterface_getProjectService_Results(s *capnp.Segment) (MainInterface_getProjectService_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return MainInterface_getProjectService_Results(st), err
}

func NewRootMainInterface_getProjectService_Results(s *capnp.Segment) (MainInterface_getProjectService_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return MainInterface_getProjectService_Results(st), err
}

func ReadRootMainInterface_getProjectService_Results(msg *capnp.Message) (MainInterface_getProjectService_Results, error) {
	root, err := msg.Root()
	return MainInterface_getProjectService_Results(root.Struct()), err
}

func (s MainInterface_getProjectService_Results) String() string {
	str, _ := text.Marshal(0x81cee22b1a1e7d87, capnp.Struct(s))
	return str
}

func (s MainInterface_getProjectService_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MainInterface_getProjectService_Results) DecodeFromPtr(p capnp.Ptr) MainInterface_getProjectService_Results {
	return MainInterface_getProjectService_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MainInterface_getProjectService_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MainInterface_getProjectService_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MainInterface_getProjectService_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MainInterface_getProjectService_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MainInterface_getProjectService_Results) Service() ProjectService {
	p, _ := capnp.Struct(s).Ptr(0)
	return ProjectService(p.Interface().Client())
}

func (s MainInterface_getProjectService_Results) HasService() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MainInterface_getProjectService_Results) SetService(v ProjectService) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// MainInterface_getProjectService_Results_List is a list of MainInterface_getProjectService_Results.
type MainInterface_getProjectService_Results_List = capnp.StructList[MainInterface_getProjectService_Results]

// NewMainInterface_getProjectService_Results creates a new list of MainInterface_getProjectService_Results.
func NewMainInterface_getProjectService_Results_List(s *capnp.Segment, sz int32) (MainInterface_getProjectService_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[MainInterface_getProjectService_Results](l), err
}

// MainInterface_getProjectService_Results_Future is a wrapper for a MainInterface_getProjectService_Results promised by a client call.
type MainInterface_getProjectService_Results_Future struct{ *capnp.Future }

func (f MainInterface_getProjectService_Results_Future) Struct() (MainInterface_getProjectService_Results, error) {
	p, err := f.Future.Ptr()
	return MainInterface_getProjectService_Results(p.Struct()), err
}
func (p MainInterface_getProjectService_Results_Future) Service() ProjectService {
	return ProjectService(p.Future.Field(0, nil).Client())
}

type MainInterface_getCollaborationService_Params capnp.Struct

// MainInterface_getCollaborationService_Params_TypeID is the unique identifier for the type MainInterface_getCollaborationService_Params.
const MainInterface_getCollaborationService_Params_TypeID = 0xdc773850ce295794

func NewMainInterface_getCollaborationService_Params(s *capnp.Segment) (MainInterface_getCollaborationService_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return MainInterface_getCollaborationService_Params(st), err
}

func NewRootMainInterface_getCollaborationService_Params(s *capnp.Segment) (MainInterface_getCollaborationService_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return MainInterface_getCollaborationService_Params(st), err
}

func ReadRootMainInterface_getCollaborationService_Params(msg *capnp.Message) (MainInterface_getCollaborationService_Params, error) {
	root, err := msg.Root()
	return MainInterface_getCollaborationService_Params(root.Struct()), err
}

func (s MainInterface_getCollaborationService_Params) String() string {
	str, _ := text.Marshal(0xdc773850ce295794, capnp.Struct(s))
	return str
}

func (s MainInterface_getCollaborationService_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MainInterface_getCollaborationService_Params) DecodeFromPtr(p capnp.Ptr) MainInterface_getCollaborationService_Params {
	return MainInterface_getCollaborationService_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MainInterface_getCollaborationService_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MainInterface_getCollaborationService_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MainInterface_getCollaborationService_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MainInterface_getCollaborationService_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// MainInterface_getCollaborationService_Params_List is a list of MainInterface_getCollaborationService_Params.
type MainInterface_getCollaborationService_Params_List = capnp.StructList[MainInterface_getCollaborationService_Params]

// NewMainInterface_getCollaborationService_Params creates a new list of MainInterface_getCollaborationService_Params.
func NewMainInterface_getCollaborationService_Params_List(s *capnp.Segment, sz int32) (MainInterface_getCollaborationService_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[MainInterface_getCollaborationService_Params](l), err
}

// MainInterface_getCollaborationService_Params_Future is a wrapper for a MainInterface_getCollaborationService_Params promised by a client call.
type MainInterface_getCollaborationService_Params_Future struct{ *capnp.Future }

func (f MainInterface_getCollaborationService_Params_Future) Struct() (MainInterface_getCollaborationService_Params, error) {
	p, err := f.Future.Ptr()
	return MainInterface_getCollaborationService_Params(p.Struct()), err
}

type MainInterface_getCollaborationService_Results capnp.Struct

// MainInterface_getCollaborationService_Results_TypeID is the unique identifier for the type MainInterface_getCollaborationService_Results.
const MainInterface_getCollaborationService_Results_TypeID = 0xc9ad31ceca5c7d21

func NewMainInterface_getCollaborationService_Results(s *capnp.Segment) (MainInterface_getCollaborationService_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return MainInterface_getCollaborationService_Results(st), err
}

func NewRootMainInterface_getCollaborationService_Results(s *capnp.Segment) (MainInterface_getCollaborationService_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return MainInterface_getCollaborationService_Results(st), err
}

func ReadRootMainInterface_getCollaborationService_Results(msg *capnp.Message) (MainInterface_getCollaborationService_Results, error) {
	root, err := msg.Root()
	return MainInterface_getCollaborationService_Results(root.Struct()), err
}

func (s MainInterface_getCollaborationService_Results) String() string {
	str, _ := text.Marshal(0xc9ad31ceca5c7d21, capnp.Struct(s))
	return str
}

func (s MainInterface_getCollaborationService_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MainInterface_getCollaborationService_Results) DecodeFromPtr(p capnp.Ptr) MainInterface_getCollaborationService_Results {
	return MainInterface_getCollaborationService_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MainInterface_getCollaborationService_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MainInterface_getCollaborationService_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MainInterface_getCollaborationService_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MainInterface_getCollaborationService_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MainInterface_getCollaborationService_Results) Service() CollaborationService {
	p, _ := capnp.Struct(s).Ptr(0)
	return CollaborationService(p.Interface().Client())
}

func (s MainInterface_getCollaborationService_Results) HasService() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MainInterface_getCollaborationService_Results) SetService(v CollaborationService) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// MainInterface_getCollaborationService_Results_List is a list of MainInterface_getCollaborationService_Results.
type MainInterface_getCollaborationService_Results_List = capnp.StructList[MainInterface_getCollaborationService_Results]

// NewMainInterface_getCollaborationService_Results creates a new list of MainInterface_getCollaborationService_Results.
func NewMainInterface_getCollaborationService_Results_List(s *capnp.Segment, sz int32) (MainInterface_getCollaborationService_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[MainInterface_getCollaborationService_Results](l), err
}

// MainInterface_getCollaborationService_Results_Future is a wrapper for a MainInterface_getCollaborationService_Results promised by a client call.
type MainInterface_getCollaborationService_Results_Future struct{ *capnp.Future }

func (f MainInterface_getCollaborationService_Results_Future) Struct() (MainInterface_getCollaborationService_Results, error) {
	p, err := f.Future.Ptr()
	return MainInterface_getCollaborationService_Results(p.Struct()), err
}
func (p MainInterface_getCollaborationService_Results_Future) Service() CollaborationService {
	return CollaborationService(p.Future.Field(0, nil).Client())
}

type MainInterface_getEventService_Params capnp.Struct

// MainInterface_getEventService_Params_TypeID is the unique identifier for the type MainInterface_getEventService_Params.
const MainInterface_getEventService_Params_TypeID = 0xaf10a6d5f63cf731

func NewMainInterface_getEventService_Params(s *capnp.Segment) (MainInterface_getEventService_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return MainInterface_getEventService_Params(st), err
}

func NewRootMainInterface_getEventService_Params(s *capnp.Segment) (MainInterface_getEventService_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return MainInterface_getEventService_Params(st), err
}

func ReadRootMainInterface_getEventService_Params(msg *capnp.Message) (MainInterface_getEventService_Params, error) {
	root, err := msg.Root()
	return MainInterface_getEventService_Params(root.Struct()), err
}

func (s MainInterface_getEventService_Params) String() string {
	str, _ := text.Marshal(0xaf10a6d5f63cf731, capnp.Struct(s))
	return str
}

func (s MainInterface_getEventService_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MainInterface_getEventService_Params) DecodeFromPtr(p capnp.Ptr) MainInterface_getEventService_Params {
	return MainInterface_getEventService_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MainInterface_getEventService_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MainInterface_getEventService_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MainInterface_getEventService_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MainInterface_getEventService_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// MainInterface_getEventService_Params_List is a list of MainInterface_getEventService_Params.
type MainInterface_getEventService_Params_List = capnp.StructList[MainInterface_getEventService_Params]

// NewMainInterface_getEventService_Params creates a new list of MainInterface_getEventService_Params.
func NewMainInterface_getEventService_Params_List(s *capnp.Segment, sz int32) (MainInterface_getEventService_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[MainInterface_getEventService_Params](l), err
}

// MainInterface_getEventService_Params_Future is a wrapper for a MainInterface_getEventService_Params promised by a client call.
type MainInterface_getEventService_Params_Future struct{ *capnp.Future }

func (f MainInterface_getEventService_Params_Future) Struct() (MainInterface_getEventService_Params, error) {
	p, err := f.Future.Ptr()
	return MainInterface_getEventService_Params(p.Struct()), err
}

type MainInterface_getEventService_Results capnp.Struct

// MainInterface_getEventService_Results_TypeID is the unique identifier for the type MainInterface_getEventService_Results.
const MainInterface_getEventService_Results_TypeID = 0xc277ced9032b2309

func NewMainInterface_getEventService_Results(s *capnp.Segment) (MainInterface_getEventService_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return MainInterface_getEventService_Results(st), err
}

func NewRootMainInterface_getEventService_Results(s *capnp.Segment) (MainInterface_getEventService_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return MainInterface_getEventService_Results(st), err
}

func ReadRootMainInterface_getEventService_Results(msg *capnp.Message) (MainInterface_getEventService_Results, error) {
	root, err := msg.Root()
	return MainInterface_getEventService_Results(root.Struct()), err
}

func (s MainInterface_getEventService_Results) String() string {
	str, _ := text.Marshal(0xc277ced9032b2309, capnp.Struct(s))
	return str
}

func (s MainInterface_getEventService_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MainInterface_getEventService_Results) DecodeFromPtr(p capnp.Ptr) MainInterface_getEventService_Results {
	return MainInterface_getEventService_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MainInterface_getEventService_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MainInterface_getEventService_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MainInterface_getEventService_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MainInterface_getEventService_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MainInterface_getEventService_Results) Service() EventService {
	p, _ := capnp.Struct(s).Ptr(0)
	return EventService(p.Interface().Client())
}

func (s MainInterface_getEventService_Results) HasService() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s MainInterface_getEventService_Results) SetService(v EventService) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// MainInterface_getEventService_Results_List is a list of MainInterface_getEventService_Results.
type MainInterface_getEventService_Results_List = capnp.StructList[MainInterface_getEventService_Results]

// NewMainInterface_getEventService_Results creates a new list of MainInterface_getEventService_Results.
func NewMainInterface_getEventService_Results_List(s *capnp.Segment, sz int32) (MainInterface_getEventService_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[MainInterface_getEventService_Results](l), err
}

// MainInterface_getEventService_Results_Future is a wrapper for a MainInterface_getEventService_Results promised by a client call.
type MainInterface_getEventService_Results_Future struct{ *capnp.Future }

func (f MainInterface_getEventService_Results_Future) Struct() (MainInterface_getEventService_Results, error) {
	p, err := f.Future.Ptr()
	return MainInterface_getEventService_Results(p.Struct()), err
}
func (p MainInterface_getEventService_Results_Future) Service() EventService {
	return EventService(p.Future.Field(0, nil).Client())
}

const schema_f0f0f0f0f0f0f0f0 = "x\xda\xcc|{x\x14E\xbaw\xbd\xddI\x06\xd0\x98" +
	"4\x03~\x02\xe2\x80\x12\x81\x00\x02\x01<0\x10'\x17" +
	"\x02$\x10LO\x12Q\x04\xfd:3\x05t\x9cK\xe8" +
	"\xee\x04\xa2\xb2xcU<\xec\x01\x05]xD\x85\x95" +
	"]Q\x91\xcbQ\x14\xf7\xe1\xec\x87\x8a\x8a+\xec\xca\xc2" +
	"*^v\x175*^VY\xd7UT\x9c\xef\xa9\xea" +
	"\xae\xee\x9aI'3\x09z\x9e\xe5\xaf\xd0]]o\xd5" +
	"{\xf9\xbd\x97zk\xc6\xcc\xe8_\x9256\xf7\xf5\xc9" +
	"H\xa8}F\xc8\xceI\x1c9Z\xbc\xfeX[\xc3M" +
	"H\x1a\x01\x08ey\x10\x1a\xf7\xda\xc0^\x02\xcaJ\x1c" +
	"Yu\xdb\xe6\xc3oi7!\xa9\x10\x10\xca\x16\xc8\xab" +
	"\x03\x03\xbf\x05\x04\xdew\x06.A\x90\xa8\xf3\xcd]\xbe" +
	"\xe7\xf8\xfb7!y\x00\x08\x89\xd5K\xaf\x18\xdf\xfb\xf3" +
	"\x83\x8f\xa1l\x91\x8c,\xbe`.x\xe5\x0b\xc8\x9f\xd5" +
	"\x17\xf8\x00A\xe2\xf6e\x17\xf4\x1f\xf1\xee\xa1\x9bMJ" +
	"\xd9@^a_\xa1\x80\xc0\xbb\xcc\x17@\x908\xfa\xc7" +
	"\xbf\xcf/\xbd<\xe7v$\x0d\xb5\x09n\xf4\xfd\x83\x10" +
	"\xdc\xe9#\x04\xb3\xb7\xb6\x1d\xbf\x7f\xff\xbc;\x904\x86" +
	"\xad5wP#Yk\xf9\x9a\x9dc<o-\xb3\xde" +
	"\x98s\xf7\x1cTE\xe6.\x18D\xe6\xdep\xd3\xde\x0b" +
	"\xbe\x7fe\xfa\x9d\xd6f\xe8\x80\x8aA\xfd\xc9\x80\xf9t" +
	"@\xd5c\x1f\xc4?\x9f_s'\x92\x87\x81\xc0\xa8/" +
	"\x1b\xf4.\xa1\xbef\xd0\x87\x08\x12\xef\xb6\x0d\x9e>\xbf" +
	"w\xfeJk\x0a\xba\xcb\xe8\xe0^d\x8a\x15\x83\xb7#" +
	"H\xdc6\xefT\xcb\xef\xcb\xefX\x89\xa4\x81b\xe2\x0b" +
	"\xeb\x1fB0\xae\xe0\xc2\xb9\xe0\x9dt!\xf9`\xc2\x85" +
	"\xd3\xc1\xdb\xef\"\x0fB\x89\xd6\x1d\x7f]\xf9\xee\xef\xca" +
	"\x7fam\x97\xce\x07\x17=J\x08J\x17\x91\xf9\xde\x9e" +
	"\xef\x9b\xf5\xde\x83/&\x0d\xd8v\xd1a2`\x1f\x1d" +
	"\xd0\xf8\xc1\x86\xdf\xe4m\xc1\xaby\x8e\xce\x1f\xd2\x9b\xac" +
	"\xa8y\x08\xd9\xd4\xf27w\xb4\xf6\x1d\xbab5\x92\x06" +
	"p\x02B0n\xdd\x90F\xf0n\x1d\xe2A\xc8\xbbe" +
	"\xc8r\x04\x89'\xef^\xfcZ\xf1\xc5\xd7\xde\xcb\xb1\xb6" +
	"\x8d\xcc\x94\x95\xe83\xfe\x9a\xf3\xc7\xdf\xf3\xf3{\xadU" +
	"P\"\xef\x0c\xa1jp\x92\x12\x99\xb8hN\xbf\xe2\x1d" +
	"\xc6}\x16\xef)\xe3\x0a\x0a\xe6\x92U\x94\x16\x10\xb1]" +
	"\xb2\xeb\xf7\xdf\x1cz\xbd\xe5\x97\xbc\\7\x15l\xa6r" +
	"\xa5\x03>\x1d~\xec\xd6\xaa\x9b\xb6\xfc\x12\xc9\x85`\xef" +
	"T\xbaX\x10\x08\xef.\xa6\xcas\xf0\x8dj\xe1\x83\xdc" +
	"\x01\xeb-\"t\xc4\x84\xa1\x0d\x84\x88<\x94\xf0\xe2\x9e" +
	"\x0f_=\xe7\x83\x93\xd2\x06$\x0f\x05{\x9d'\x87\xbe" +
	"B\xa8d\x0f#T\xa4\x93W\x07Z\xeb\x1b7\xf0*" +
	"\x80\x87Qn-\x1bF6\xf2\x9b\xa6~'\xf6\xf4\xde" +
	"\xba\x81\xe8\xb3\xc8\xe93\xe5\xc6\xa6aU\xe0}j\x18" +
	"\xf9s\xe7\xb0\xff\xa2\xfa\\=F\xaf\xf4\xec\xb9\x9f\xad" +
	"\x9aN\xd8ZH\x15bM!\xa1x\xdd\x9e\xef\xa6=" +
	"\xf3\xbb\x82\x07x\xce\xc0\x88 \x190p\x04\x19p\xeb" +
	"\x81?\x1d\xdaS\xb4\xe1\x01^\xc2\xcbFP\xde\xae\x19" +
	"Avu\xe4\xd9\xa1?\xec\xdc\xf4\xf8C\xfc\x0c\xa3F" +
	"R\x9b\xa9\x18If\x98~\x0d\xec\x16{\xfe\xed!\xb6" +
	"m\x93\xb9#\xa9\x92<5\x92L\x11\xbc\xe6\x87p\xd1" +
	"\xee}\x9b\x92F\xd4\x8f\xa2#\xd4QD\xb1\x1f\x9f|" +
	"\xe9\xd3_\xeel\xdb\x9c\xa4\xfa\xc5\x97\x08\x94\xb9\x97\x90" +
	"\x11\xabF}x\xc1d\xf9\xf5_\xb5\xd3\xa3\xe1\xa3\x8b" +
	"\xc0;i4\xd1\xa3\x09\xa3\x89\x1e}\xf5\xa9\xda{]" +
	"\xe9\xc1-\xa9\x98\x90C\xadet/\xf0.\x1bM\xf9" +
	"4\xfa%\xc2\xc3\xc7n\x9b\xbd\xa3\xed\x7f>z\x84\x0c" +
	"\x07n8\xe5\xa5<6\x08^<\x96L\xae\x8c%[" +
	"9\xf7\xedsn/{\xef\xea\xadH\x1a\x00\xa9xs" +
	"zl\x11xs\x8b\xc8\xe0\x9eEd\xb0\xbci\xfc\xb7" +
	"+n<\xb8\x95\x03\xb6ME\x14\xd8\x0e\xdf\xbb3v" +
	"\xc9\x8d9\x8f!i\x98-\xb7\xf5E\x14g\xb6\x15\x11" +
	"E(Y\xf9\x8b\x87\x9e./}\x02I\x03\xc4\xa4\xed" +
	"\xbeS\xe4\x07\xefg\x94\xc8\x89\xa2\xdb\xbd\x93\xc6\x11;" +
	">\xe7\xb9\xf3\x1fm^S\xfd\x04o \x83\xc7Q\xf5" +
	"\x1e;\x8eL7\xf6\xeb)\xff:\xfa\xeb\xfc\xed\xdcJ" +
	"\xe4q\xd4\xb6\xce\xfd\xe4\xd0\xaa\xb9\x1b\xc7m\xb7dC" +
	"_U\x8e\xa3\x8c\x9fO?\x0d\x9f\xdbl\xc4\x7f\xd6\xb0" +
	"=I\xab\x97\x8d35d\x1cQ\x80\xf9\x93\xaf\xfc\xe1" +
	"\xcd!\xd7oo'\x1a\x18\xaf\x81\xb7\xefx\xb2Vi" +
	"\xfc\xe5\x08\x12\x8f^\xf8\xa7\xea\x95\x0f\xde\xfb\xdf<F" +
	"\x16\x8c/\"\xc4\x8a\xc7\x13bw\x0c\xfah\xc1\xa1\xb5" +
	"\x7f\xf8\xefT\xd9\x99\xb82\xde\x0f\xde(\x9dN\x1dO" +
	"\xf8[\xf9\xc6\xb8\xa5\x81\xc0\x13O\xf2\xdb\xee9\x81\xc2" +
	"W\xbf\x09d\xba\xca\xaf\x96\xfd\xf9\xd0\xf5\x8d\xbb-{" +
	"\xa3\x9b\x9b4\x81\x9a\x87<\x81\xea]\x9f}\xdb\x12s" +
	"~\xb1\xbb\x1d\x9bG]\x1a\x04o\xe9\xa5T\x0d/\xf5" +
	"\x88\xde\xfa\x89\x84\xcf\x0f6\x8f\xb8q\xe3#\x93\x9e\xe6" +
	"\xfdQ\xf1Dj\x0b\xf5\x13\x09+\x9e\x9a\xdc|\xd7\xdd" +
	"\xc3\xf3\xf7$1\xeb\xa9\x89o\x92%\x1d\xa0#\xf2\xef" +
	"\xdb\xff\xeb[\xe1\xff\xecIU7\x13N&U\x81\xb7" +
	"r\x12\xd9a\xc5$\xb2\xbe\xda'\x96\xae.\xd9<~" +
	"O\xbb\xf5\x0d\xf6\x97\x81w\xac\x9f\x1a\xa3\xdf\x03\xde\xe3" +
	"\xe4\xcf\xc4\xbf\x9e\xef{\x15\xde\x7f\xffoM\x86\xd0\xed" +
	"\x1e\xf0\xef\x02\x94\x95\x80\x17'\xeezq\xdf\xf3\xfbx" +
	"3\xdf\xe3\xa7\x0aw\xd0Ox\xb9\xe8\xf6\x03_\xdep" +
	"Dx\x8e7s<Y#[\xbby2Yx\xcf\x8b" +
	"F\x88\xc7\x0e-y\x8eG\xfa\xe3\x93\xa9\xfb:5\x99" +
	"0;\xf4\xf4L\xbd\x05\xff\xf0\xbc\x05F\x94z\xbf)" +
	"T\x93FM!\x03\xae>\xda\xf7\x81\xbb\xe6\xbd\xfcB" +
	"\x12\xc6VO\xa1\xccQ\xa6\x90\xed\xee\xbe\xe1\xe5\xd3\xbb" +
	"\xae\xef\xb7\xdf\xd5\x16'\x15\x07\xc1[]L\x98SY" +
	"L\x96<u\xff\x84\x81\xd3\x8fl:\xc0/\xb9\xad\xb8" +
	"\x8c\x10<]L\x96<x\xd9\xbcW\x0e\x8d\xddv " +
	"\xc99]F\xddB\xebedE{\x0f7\xbct\xf0" +
	"\xef{\x0f\xb4c\xef\xfa\xcbn\x01\xef\xb6\xcb\xc8\x07[" +
	"/{\x09\xbc'\x03\x84\xbd\xe3\x7f\xb5\xee\xb3\xac\xde\xfd" +
	"_i7\xfcX\xc0\x0f\xde\x13\x01\xba\x80\xc0K\xe0\x1d" +
	"XJ\x86\xaf\xed\xd5+w\xc7\xdd_\x1e\xe2\x9dNv" +
	")u\xe7\xfdJ\xc9\xfa&\xc7\x1a\x9ey}i\xcea" +
	"^\x7f[KM\xf4.\x0d \xf8klkU\xdb\xdd" +
	"\xffu\x98{\xbd\xb3\x94\xb2k?y\x9d8\xf8\xec\x87" +
	"\xfd7>\xff\xdea\xde\x9d\x9c(\xa5\xee\x04\xca\xc8\x80" +
	"\x99\x17{{\xee\x9e\xfd\xb3?\xf1\xf1BA\x195\xdd" +
	"Ie\xdb\x11|\xb7\xdf{\xfa\xe47\x1b\x8fp\x04\x8e" +
	"\x96}L^\x9f\xa0\xdf\xff\xe5\xe91\x9e\xf5\xfd\xc7\x1e" +
	"\xe5\xbf\xefYN\xb5f`9\x11A\xdb\x91{\xb6\xfe" +
	"\xc7\xb4}G\xf9\x15\xec)\xa7[<XNf\xf8U" +
	"\xf9\xd1\xdf\xbe\xd0\xf6\xb3\xd7]\xd5\xfd\xb3r\x0d\xbc0" +
	"\x95H\xf4t9\x91\xff\xc0\xd6\xdb^\xe8yd\xd01" +
	"\xde\xbe\x8eN\xa5\xd3\x9d\x98J8v\xe3\xaf\xef\xf3\x1e" +
	"\xd8\xdbt,\xd5?R\xc2\x95\x15\x0d\xe0\x9d_A\xfe" +
	"\xbc\xaab\x0e\xc1\xf6\x9f\xf7\xbd\xe1\x93\xa6\xc3\xb9o\xf2" +
	"0{p\x1a\xdd\xe0\xf1idy\xfd\x8f\xd5\xf7\xec\xb7" +
	"\xa5_\xd2\x00\x98N%\xd0o:\x190m\xe0\xe7'" +
	"\x06\x1dox\x8bG\xac\xca\xe9\xd7\x93\x01\x98\x0eX;" +
	"g\xf8\xa1\x9a\x89K\xde\xe6\x90u\xfd\xf4 A\xd6\xdf" +
	"|\xf8\xf0\xcd\xc3\xff\xe0\xff\x0b\xcf\x9bu\xd3)\xf1\xad" +
	"\xf4\xd3\x91\xeb6\xf7\xbaq\xd7\xc5\xef\"y\x8cm0" +
	"\x07\xa6S\xdf\xdcF\x07\\\x11\x1dp\xef\xc7\x7f_\xfd" +
	".\x1fqd\xcf\xa0!\xe5\xe0\x19\x84\xfd\xb9W\xde\xe5" +
	"\xf9T\xfa\xe2]\x9e\xc4\xde\x19\xd4\xe4^\x9bAW7" +
	"f\xc0\xcf\xfb~\x92\xfb^;\x8d=9\xc3\x0f^\xa8" +
	"\xa4nk\xc6\xed\xe0=M\xfeL\x1c~\xf2\xb1=[" +
	"\xae\xb8\xb2-\xc9\x0d\xb7UR\x95;UI$\xf4\xf5" +
	"=w\x1d\xc7\xd5\xbfk\xe3)\x1e\xab\xa2\x14?\xab\x0a" +
	" \xf8\xe1\xe6\xf7\xefz\xe8\xe4\x9d\x1fp*\x9f;s" +
	"\x17U\x98\x99D\x80_\xaeYl\xac]\xb1\xe9#\x1e" +
	"\x87ZgR\x09\xaf\x9aI\xb64c\xd0\xd0\xefF\x1e" +
	"\x12O$-\xa1`\x16e\xdb\xa4Yd\x09\xdf\xed\xf9" +
	"\xc3-\x9bf\xee8\xc1\x81\\n\xf5\x06\x02r?\xe4" +
	"\x9ch8o\xff\xdf\xf87\xa7gm&o*\xc7\xac" +
	"\x1c<CX\xfaq\x12\xf4|6\x8b\x9aJv5\x99" +
	"\xf5\xc0\xf0\xff\xf8p\xfd\xad\x1b>N\x8a1\xab\x9f%" +
	"d?\xab\xa6\xac\xbc\xe7\xfb>g\xcd\x0b|\xce\x83I" +
	"\xeel:C\xc1l2\xe0\xd4Y\x9f\xcf>\xf1\xf1\xd9" +
	"_$\x05c\x15\xe6\x88\xf9\xb3\xc9\xe6\xa7\\v|\xc6" +
	"\xfe\xab\x07|\xc1o\xfe\xc0l\xca\xddwf\x93\xcd\xf7" +
	",\x0a\xfey\xc3o_\xfbG\x12w.\xa7\xdc]u" +
	"9\x190\xf3\x85\xea7\xcf\x95\xa6\xff\x93\xf7\xd6\xc3k" +
	"\xe8\x0c\xc55d\x11e\xeb\x1e\x9fS\xde\xf6\xcf\xafR" +
	"\xe2\x13\x13\xfaj\x04\xf0\xaa5\xc4\xdc0\x1d\x8cG_" +
	"\xf1\xd6\x91\xc8\x98\xafya\xae\xa8\xa1\xeex#\x1dP" +
	"\xb2\xec\x9dk\x8ag\xbc\xf45o\x1e\xfbj\xa8\xb4\x8e" +
	"\xd2\x01'\xcf\x0f\xf4\x7fyK\xf8\x9bT\xf3\xce&#" +
	"O\xd5\x94\x81\xb7\xa7L\xb5V\xa6\xf68\xbc\x970e" +
	"\xf5\xd4E\xa78c\xa9\x0f^H\x8ce\xc5\xfa\xf2E" +
	"\x9b\xef\xd8\xf0\xad+NT\x07\xab\xc0\xab\x04\xe9\x1e\x82" +
	"t\xa2\xb7\xfa\x1d\xddv\xd5E\xaf\x7f\xc7C\xeb\xfeZ" +
	"\x1aP\x1e\xab%\xac\x8e\xfa!\xfb\xe4\xdd_}\xc7\xa9" +
	"Bq\xdd\xa3D\x15\xee\xbb\xe0\xd4\xf3\xfe\x09\x81\xef\x99" +
	"\x98\xcc\x80\xb6\x8e\xda|E\x1dQ\x85GW\x1c\x9a\xb2" +
	"\xf1\xfc\xe9\xdf\xf3(4\xb0\x9e\xa2\xe6\xd8z2\xf9\x03" +
	"{g\x15n\xff\x9f\x89\xa7yO\xb7\xca\x1c\xb0\xa9\x9e" +
	"\xb0\xe5\x9b\x8aM\xdf\xdd\xd0\xf8B\x82\xf7L\xfb\xea)" +
	"\x89c\xf5KP\x02%\xd0\xab\x09=\xb4\x08G\x15}" +
	"\xb4'\xaa\xa8\xb1k\xd5\x98\x81\xb5\x05J\x08_\x12R" +
	"\x9abM\xfejE\x8dU\xda\xcf\x16b\xa3^\xc7Z" +
	"-\xd6Z\xd4\x10\x1eR\xa3hJTG\xc8\x9e#G" +
	"k\x0a]\xab\x9bouk\x86\x1a-\xde\x88C\x86\xf5" +
	"\xcd%a\x1c\xc1\x06\xb6\x1e\x0e\x09\x98S\xc8=\xc4," +
	"\x84\xb2\x00!ix\x10!y\x98\x08\xf2x\x01$\x80" +
	">dg\xd2\xd8\"\x84\xe4\x91\"\xc8\x13\x05H4\x99" +
	"\xdfV\"\x08\xc3\xd9H\x80\xb3\x11\xf8\x8c\xf8u8\xc6" +
	"\xfeg/'\xcbe9\xd5j\x04\xebF<\x86\xeb\x9b" +
	"\xc2\x8ah\xe0\x1a\x00\xb9\x8fM}\x19!\xb4T\x04\xf9" +
	"6\x8e\xfa\xcd\x0d\x08\xc97\x89 \xff\xa7\x00 \xf4!" +
	"x \xddY\x86\x90|\x9b\x08\xf2j\x01$1\xab\x0f" +
	"\x88\x08I\xab\xfc\x08\xc9w\x88 \xaf\x15@\xca\x12\xfa" +
	"@\x16B\xd2\x9a\xb9\x08\xc9\xabE\x90\xef\x17\xc0g\xa8" +
	"F\x04\xdb\xeb\x0cc=\xa4\xa9M\x06\xf2\xa8q{\xf5" +
	"\xcb\xc3\xcdx\xaab`\xc8F\x02d#\x08\xe8\x86b" +
	"4\xeb\x90\x978\xf7\xcb\xba\xdd7D\x8f\xbd\x89\x10@" +
	"\x1e\x82\x84\xa2\xeb\xea\xc2\x18\xc6H\xac\x0c\xb7\xdb{\x86" +
	"\xe2L\x96\xce\x90 \xd6\xf3\x9a#\x86.g\xd9,\xc9" +
	"%;\xed!\x82\xdcG\x80\xe5\x163ArBV\x04" +
	" qt\xddT\x80\xd3\x19\xa6B\x16]}H\x8d\xaf" +
	"\x9d\x06\x10.\x0e\x11A\x1e\xc3\xc9`T\x91\xa3\x16\x81" +
	"f\x1dk\x95\xe9\x84\xdf\xc3e!\xe5\xf1HDi\x88" +
	"k\x8a\xa1\xc6clExih\x91\x12[\x88+\xcb" +
	"+\xca\x95XX\x0d+\x86\xc3\x88\xaeO\xa777\x10" +
	"\xa96\xd8:\x1e\xc4:\x99\x09!\x9e\xa9~\x87\xa9\x01" +
	"\xdd\xd0\xb0\x12\x05\xc9\xc9\xb6Rx\xeaIoV\xcdM" +
	"d\xd9\xd58\xda\x80\xb5`<\x82M\xaab\xb2$y" +
	"\xa2Q:\x14\xf2\x13\x81~oe\xbf\xb2\xeb\xf1\xe7\x09" +
	"\xd1\xfc4\x82\xach\xc11\x9b\xa4\x86\x9b\"J+}" +
	"\xa4\x13(\xf0\x101\xe6\xdb\xd4\x94*\x84\xe4\xff+\x82" +
	"\x1c\x11\x80IQ%\xb6\xb0H\x04\xd9\x10@\x12\xc04" +
	"\xa5\xc5D\xb4\x11\x11\xe4\xa5\xc4\x94\xc04\xa5f\xf2\xb0" +
	"I\x04\xf9F\x01\x128f\xa8Fke\x18!d\x8b" +
	"\xd9|V\xd7\x8a\xc4&\x0cyN^n\xda\x86\xaf9" +
	"f\xa8\x11fB\x1dhH\x06l\x0di\x98\xb0\x95a" +
	"\x86\x8dx\xf2\xd9\xf6>+\x08`M\x15A\xae\xe1\xd4" +
	"\xb5\x9a<\x9c%\x82|%\xd9\xa8\x85\x19\xf5dO5" +
	"\"\xc8\xf3\xdcQ,\x11\xb5\xe8 \xc0\x90\x9f\xd8Q\xfd" +
	"\\\xe5\xdc\xaf\xeb\x0eX\x82\xe9\x08\xe3\xd2\xd9\xb9\x18\xb2" +
	"0.\x1b!\xbb\x14\x00,\x8c\x90\xd6\\\x8f\x04\xe9N" +
	"\x0f\x80]\xff\x04VL\x93\x96\x91w\xcd\x1e\x10l\x8f" +
	"\x09\xact)\xa9w#A\xc2\x1e\x10\xed\xd0\x13X\x9e" +
	"#]\xf5\x1c\x12\xa4z\x0fd\xd9\x09?\xb0\xb4M\xaa" +
	"\xbc\x05\x09R\xa9'\xb1\x10\x1b\xa5\xcd\xc6\xa2Z\x140" +
	"Y]\x02\x09\xe6]\x92\x1fQ\x89\x00\x13\x09XO\xa9" +
	"\xe9\x09)\xb6\x87\xccwT%\xc1yV\x03\x0e\xbb\xb2" +
	"]dN\xd7a\x09<\x12_\xa8\xc6\x1c\x18\xe4\xc4L" +
	"\x84W\"\x82<\x8b\x13se#B\xf2\x0c\x11\xe4:" +
	"N\xccr\xa1#\xfb\x14\xa1ix\x81\x86\xf5Eu(" +
	"\x8f\x7f\x9cG\xf0\x0c\xf2\x13\x0fN+\xf9\xfe\x8e\x95=" +
	"6eb\x89\xed\xd6|9yba\x0d\xfc\x9b,\xbc" +
	"\x1b!\x85\xbd\x81\xb4\x0e\xc8\xce\x82S\xc02+\x1dP" +
	"\xe7\xd5\xb56\x99&Aw=a.\x9dal\x10!" +
	"\x10\xa4Q\x85\x08\x81(\x15\x94!\x04Y\xd2\xc0*\x84" +
	"\x12\xa1fM\x8fk\xd5q$\xb6\xe0\x84\x8e#8d" +
	"\xa8q\x04\xb1<\x1cV\x8d\xe5\xa1x4\x8acF\xa2" +
	"I\xc3:\x8e\x850\xe2\xc2!O\xc6>\x03\xc7\xc2T" +
	"k\xed\xfdw\xdb\x9f\x06\x03\xa6\xbb\xe1\x19XE\x01\x0b" +
	"\xe4a\x0e\xee\xe8\x04K\xcfAP#\x02\xe4'\xf6\x0a" +
	"g}\xfa\x89z\xe9J\xc2\x89s\xba\xe3CuC\xd1" +
	"\x8c9\xb8!XW^\x8bu]\x8d\xc7\x1c\x07\xd4\x95" +
	"\xd8N7?N\x8a\xed\xe2\x0b\x16`\xad\x1d\xeeef" +
	"\xc8\xcc-qk(r\x8b.\xaa\x9c5\xf8pTQ" +
	"#6\xbd&E\xd7\x97\xc4\xb5$\xdf\xd3\x05\x07\xa2c" +
	"E\x0b-r\xa2\x1d\xd3\x7f\xa4\x8d8\x89\xca\xdf(\x82" +
	"|\x87\x13q\xae(r\xa2P\xdbM\xde\xe9\xe7\xc2P" +
	"\x16q\xae*r\xc2P\xdf\xe2f\xac\xb5\xda\xb1\xe5\x02" +
	"5b`M\x87|\xa7\xc4oy\x97\x88\x1aU\x0d\xc8" +
	"B\x02d!\x08\xc4\x17,\xd0\xb1\xfd\xdf\x9f$\xc2b" +
	"\xa29cO\xea\xa23\x89\x90E\x86x\xd2\xce\xc3\xc4" +
	".\x80\xab\xed\xfc9m\xaar4\xdaV\xe8\xc2\xe4d" +
	"\xa5E\x0dc\x8d\xa8O^\xe2D\xe4\xd2\xa1/\x16\xdc" +
	"v\xc4\x8aR\xf2B\xf10\xfe1\xc2\x127\xd4\x0cZ" +
	"F\x7f\x9e\x90&\xb0\xe8\x149k\xa9\xfeN3\xd5\x06" +
	"!\x02\x9b\xe7\xdb4\x9e\"\xda\xb7C\x04\xf9UN`" +
	"\x07\x08K^\x16A~\x9f\x13\xd8q\xc2\x93\xb7E\x90" +
	"\xbf!\xca+\x9a\xca\xfb\x15\xd1\xf2/D\x90\xbf\x17\x00" +
	"\xb2L\xdd=E\xbe\xfeF\x84\xda,\x10@\xca\x86>" +
	"\x90\x8d\x90\x17\xa0\x11\xa1 \x88P{6y\x9c#\xf4" +
	"\x81\x1c\x84\xbc=AC\xa8\xb6\x07y\xde\x07\x04;S" +
	"\xb2`-/\xb1\xa5\xe7\xe1\xb5'?x\xf2a\x06k" +
	"M\x9a\x1a\xd7T\xa3\x95\xc3\xbe\xbcDx\xde\x88\x0b\xff" +
	"\xb1v\xe4\x7fZ\x83\xf2\x0ce\xa1=\x05\x11\xcd9\x08" +
	"\x96\xc7\x97\xc4\xf8\x8c#\xa1\xea5\xcd\x0d\x115D&" +
	"\x02$\x00\x10\x95\xa32\x09\x97\xa2\xbc\x05\x06\xd6X\xe8" +
	"\xc9\x1e\x97!\x1f^\x10\xd7\xec\xac\xee\x0c0\xc4\xc9'" +
	"\\\xf4p\xaa\xa3\x87\xa5\xc4H\xa6\x88 \xcf\xc8\x10\xf6" +
	"}F\xdcP\"\xcc\xe8\x7f\x14'@M\x06~\xaa\xfc" +
	">\x9do\x0c\xab\xba\xd2\x10\xc1uK\xe2\xd3\x94\x90\x11" +
	"\xd7\xecr\x03\x879~\xb7\xe8\xa8\x88\x03\"\xa6\xc2\xd5" +
	"U\x0e\x10u\x9e\x81v\xd5et\x9eFV\x86\xb12" +
	"\xa4F\xc9\xebr\x96\xac\x86\xb1R\x19\xfe1\xe0o\x8e" +
	"\x12\x89`\xc3\x16&\xc7\xbd\xb9\x0e\xa3l\xc0.\xe3C" +
	"K+\xc7\x93\x83\x1c`/\xa1\xd3\xd9\xa9\xdb\xcc`\xe2" +
	"\xda\xc4\xea\xa3\xdb-P\\\xae\x84\xc3\x1a\xd6ug\xa9" +
	"\xea\xc2\x98b4k\x1c\x96g\xac\x01\xa6\xe9\x90'\xba" +
	"\xbd|.E%\xec\x9a'\x82\xbc\xc8Y>.r\xd2" +
	"V{\xf9*avX\x04\xb9\x89\xf3\xbd\xd1\"'\x99" +
	"Mv\xb3\xddq\xa6\x9et\xe9\xb6S\xacqRn\x1a" +
	"Kp\xfb\x09\xba\xa4\xdcE\xdc\xd2\xd9~\xf8\xa5\xdb\xfb" +
	"\xe1\xf3pW#\xd4\xd5X\xc8\x06\xb0\x8c2l\xd1m" +
	"S$q\xf7\xb5\xa6\x04\xe1\x854\x08\x1fUF\x83\xf0" +
	"\x023\x08\x1fh\x06\xe1}\x83\x08\xd1Lc\xb9\xb5\xa8" +
	"<\xa2\xd9\xcb\xa3X\xd7\x95\x85\x98\xf7m\x9d\xd3%\\" +
	"3=\xd8 \x9bc\xaf\xf5GH~U\x04\xf9\x0d\x87" +
	"cG\x09\x17\x8f\x88 \xff\x8d\xe3\xd8;U\x96\x03\xfb" +
	"\x88\xab\xf7\xb5\x11\xf5\x7f_\x04\xf9\x0b.\xfa\xfa\x8c|" +
	"\xfe\xa9\xe5\xea\xb2E\xea\xc0\xa4\xaf\xfc\x8e\xab\x93r\xb2" +
	"\xa8\xfb\x92N\x11\xa7\xf8O\x11\x82\xc4\xa7y\xb2\xfb\x80" +
	"\x07!\xe94!\xf4\xbd\x08\xb5=@\x00Qu|\x8e" +
	"\xa1F\xb1n(Q\x04M\xb6\x13\xe9za$\x81\x09" +
	"\x1b\xeaZ\x9b8kJA\xb3\xbc\xb0b(\x90\xef\xd4" +
	"\xf0\xad0!\x8a\x0d\x85\xbc\"\xc4\xf2\x9d\x03\xe4\x8c\x82" +
	"\x083i\x8a\x05\x95\xd8B\xa0bO\x97\x9f^\xc8\x01" +
	"\x0b\x03\xe0\xb9\\zJ}\x0d3)\x0f\x8e\x85m\xb7" +
	"\x15\x8e\x87\x9aIF\xe6Z\x15\x15;\xc0\x8bz\x1f\xad" +
	"\x9f\xa5\xac\xac\xd0me~7\xdfP\xe4`^^L" +
	"\x89:\xacUZ\x14C\xb1\xb3\x97\x94\xdc\xa2\x8by2" +
	"\x87\xcb\x99\x95\xdeS\xf1\x83\xec\xd4\x02\x8f \xf6\xb5K" +
	"\x13Yyp\x88\x00\x01\xaa&\xba\x13*\xd8\xdd,)" +
	"\x19b\x87\x96\x16\xa8\xa5UM\xc2\xd1\x1e\xb4\xf4\xc4\xce" +
	"\xcb\x80u\x89\x90@Y\x90\x0a<\x00\xf6\x89\x19\xb0\xf3" +
	"\x12\xa9_\x11\x12\xa4\\O^\x0c/5J\xc0\x17\x8a" +
	"\xc4u\x9c\xbe\x92cn\x98\x12\xbe\x84|Ic%O" +
	"\xca6\x8b\x9cr\x82\x8fn3e{\xdd\xa8`\xf0\x8c" +
	"f~\xa6Sd\xef4Ja\x01^\x875\x90\xe6P" +
	"\x888H\x16yf\xea\x0cq,\x85\x0e+\x15pQ" +
	"E\x99\x13U\xd8AE\x83\x15\x9c\xcdp\xa1\xdd\xa0\x84" +
	"\xaekn*\x8f#O\x18\xa7\x86\xcd\x19\x96d\xe2Z" +
	"\xad\x8f\x06\xee\xd4\xfa\xa8=\x0d\xf4Sw\xd0\xb7\x90\xba" +
	"\x83\xdcB\x84\x02J\xc8P[p\x9e\x1a\x8e\xe0<e" +
	"\x89\xd2z\xa6\x11Ug\x06\x90QQ^t\xa5\x1b3" +
	"\xb4\x80\xda\xd0l\xc4\xb5\x14,\xe1\xe2L\x1bJ4\xb7" +
	"Hi\xae\x13)\xa5\x00s\"D\xa6W\x1b\x9a\x91\x8f" +
	"\xecK\xb7!/\xa2\xe8Fi\xc8P\x91\xd8\xd2>\xc1" +
	"\xc8\xa0P\x12o6\xec\x08\xb3\x03C\xe9v\x05\xdd:" +
	"\x98h_Aw\x0f[l\x9cU\x1b\xf8\xa3\x02\x0bg" +
	"\x17\x97\xf1G\x05\xa2\xcbQA\xa7eu\x0fv\x98\xb9" +
	"\xdc\\\x98\x0e\xf9N\xf7n\xe7\x85\xf6t{5\x1d\xdb" +
	"\x18\x0av\xec\xec\x16X\xa3\x82w1hH\xf0\xaa@" +
	"\xe0\x8e\xf5\x97\x00\xeb\xcd\xf0\xce\x87\xb9H\xf0\xd6\x83\x07" +
	"\x04\xbb[\x06X[\x85\xb7\x92~[\x0a\x1e\x10\xed^" +
	"d`}N\xde\x09\xf4\xed(\xf0@\x96\xdd\xdb\x04\xac" +
	"#\xc6;\x18\x82H\xf0\xf6\x03\x0fd\xdb}4\xc0N" +
	"\x8e\xbd\xb9\xd0\x88\x04o6x \xc7nN\x00\xd6!" +
	",\x9dZ\x89\x04\xe9+\x0fx\xec\xd3j`\xdd\x05\xd2" +
	"\x89[\x90 \x1d\xf7@\x0f\xbbg\x15X\x1b\xa8t\xf4" +
	"z$H\x07=\xd0\xd3\xeeT\x03v\xc6/\xed\xdb\x8c" +
	"\x04i\xaf\x07z\xd9]\xc4\xc0\xdaQ\xa5\x9dd\xce\xad" +
	"\x1e8\xcb\xee\x98\x03\xd6[$m$\xef\xd6y\xac|" +
	"\xbaFC>\xcaz\xee\x8c\x00\x89\xf4\xbf\xa6\\\xf9\x01" +
	"\xec\xc8\xd9y\xa2\x84\xc3\xf4\xa8\x0c\x81V\x02\x09\x0dG" +
	"\xe3-\xb8\x1a\xa3\xbch\x03\xd6\xec)\xaa1\xb0\xd34" +
	"\x84\x92\xcf\"\x08\x82\xe8\xe4\x19K\xcdQ\xc0L\xaf\x93" +
	"\x87\x95\xc6\x94H\xab\xe1QC\xe49\xab\xd9\x80e\x09" +
	"\xc8!\xc4?\xe3]\\\x06\xe6\xe5d\x05&15\xa4" +
	"\xbb%\x8b\xff\x8bI7\x9fr\xb9\xd5\x80Y\xfd\xb5\xc4" +
	"\x01\xc2b\xf2l\xa2Y\xbd\xf0\x11\xcc\xe3\x02\x0f\xfel" +
	"\xa1\xe3\x1aEVG\xc1@\xb5\x1d\xb4\x12\xe3\xe40\xa7" +
	"\xcc%\xf5\xf3\xbb\xa5~\x1a\x9f*\x09V\xaa\xd4\xe0@" +
	"\xce\xf2\x16\xac\xe9j<f\xa7{z\xbcY\x0ba\x0e" +
	"\xb45\x0dG\x14\x03\xf9\xd4x\x8c\x07s\xa5Y'\xfe" +
	"\x09yb.\x81jV\x9ap\xce\xda\x0e\xc1\x1a\xd6\xb4" +
	"\x0c\xac\x8bLZL\xec6J\x90\x86\xb51\x01\xeb\xf4" +
	"\x95\x14\x0d\x09\xd2U\x04gX\x9f?\xb0\xf64\xa9\xba" +
	"\x11\x09R\x05A\x19\xd6\x81\x05\xac\xf5F\x9a\xd4\x80\x04" +
	"i\xac\x87Wo3\x94d\xb6A\x83K\xe4\xa3\xcf\xa8" +
	"Q\x99\xa7\xc3(\xcfz\xb0\x10\x1b\xb51\xa5IG\x9e" +
	"Eq\xa3\xcb\x87r\xc4E1\x97\xdd\xed\x80\x87\xf5\x1a" +
	"t\xab\xfc\xe3w\x9cu\xa7\xe5\x9f\x80\x8eC\x1a6\xba" +
	"_-'\x91>\x0dv\xf8\x10\xc9\xb5Q\xe2G\xb4\xea" +
	"\xee\x04\xban-\x06\xeeguv\xffp\xd7\x1b\x1b\x92" +
	"\xfb\x85~\xcc\xd08\x85\x10\xf3\x09\x1a\x0dQ\xc4\xe4^" +
	"\x06\xd7\x08\x85+\x0a\xb1\x1c5Z\xe8\x86\x16i\x0a+" +
	"\xa9\xf9\xb7\x16\x8f\x90\xcc}\xf4\x1b[\xbe\x9c;\xf4\xc5" +
	"\xf7XKC\xe6aI9=\xb1\xac\x89\xeb\xaa\xa1\xc6" +
	"!\x96\x12\x89\xf6vS\xf9\xde\x9d\xe7\xdb\xb0\x14z!" +
	"\x01z!\x80V\xf6W\xe7\x99v\xf7\xfbeX]\xeb" +
	"\xa7Q\xf4\x1e\x99)\xba\xdbR\xbb\xa0\xf0vGw\x8a" +
	"\xc2gg\xc8\x15\xeb\xa0\x85\xc0;k/\x07v\xb3K" +
	"zm\xa5\x19^9\x97b\x80\xddh\x90\xf6\x11x\xdf" +
	"C\xe0\x9d5\xff\x01\xbb\xd0$m\x0b\"A\xdaB\xe0" +
	"\x9du\xd9\x03\xeb+\x96\xd6?K\xc3+\xc8\xb2\xaf\xea" +
	"\x00\xbb\xcd$\xdd\xb9\x01\x09\xd2\x0a\x12@\xb2N``" +
	"=\xc3R\xeb\xddf\x8bH\x8e}/\x09\xd8\xdd4I" +
	"}\x94\xb6\x88$\x98\x84\x81\x89\x98\xba\x0c\xf6\x14\xf9h" +
	"BF\x83)\xf3\x14\x1c\x81\x15\xd6Q\x18\x04\x86\x83\x01" +
	"\x13\x08\xc9@\xeb\xa0\x01\xd8I\x83\x18\x8f\x95@\xa21" +
	"\xae\xc6\xe6\xe0\x86 \xb0\xf3\x07 O\xd9\xe1#\xb0\xd3" +
	"\xc7<\x12s%;\xa0\x8e\xcaB\xb5V'\x8a-\x0d" +
	"\xd6W\xcc\xf5\xe9\xbeV\x86\x04i?\x91\x06k*\x86" +
	"\xfd^d\xf6\xb3\xef!\xd2\xd8I\xa4\xc1Zj\x815" +
	"\xdbK[\x08\xe76\x11i\xb0{I\xc0\xaemH\xeb" +
	"\x88\xb3]E\xa4\xc1n\x02\x02\xbb|&\xddL\x02\xe1" +
	"V\"\x0dv\x99\x02\xd8\xdd\x18)z\x8b\xd9\x94\x93c" +
	"\xdf\xa7\x02v\xb1F\xbaj%m\xcaYn\xb9\xea\xe4" +
	"Hy\x81\x1a\xc1\xdc\x13\xc0\x0b\xb0\x86c!\x0c\xba\x1d" +
	"\xe4\xd6\xeb\xc8\x835\xddq\xf65\xc0\xce\x94\x08\x97-" +
	"W\x0b\x96\xaf%\xcfXa\x03\x98\x03F)\xf1m\xba" +
	"\xc3\x07\xd6uB\x0c\xd9)\xe5\xa4;\xcb\xbf\x85;\xcb" +
	"O\xc6\x80\x18^\x12$S\x825gf\xc73|D" +
	"\xc1\x18\xc4\xf8\xa3\xbbw\xf7\x15:\xa0p\xa6\xcd=I" +
	"<`\x9e\x89#\xd5\xc8\x1d\xf3\xbaw\xe9\x9cI\xb6\xfe" +
	"\xe3\x1c,\xe7dJ8\xb5-8]o@\x99[\x17" +
	"S\x91\xe3\xb6\xdc\xfc\x02\x97\xf8\xdb\xdd\xde\x9d&\xfe9" +
	"\x19\xea\x045\"\xd7\x0e\xda3T\x87\x14V\xb1t\xd5" +
	"\x8cU|\x99q\xca\xdf\x0dNe\xd6g\xdb\xa5\xd0\xca" +
	"\xad\x1e\xdb\xa5\xae\xd4\xb4\xdd]>\x1a\xa2\xa6${\x85" +
	".\xc9^\xd0\xed\\\xcc\xef\x16\xbe\x15:\xe1[\x9e\xd1" +
	"JOU\xec\xeb\xc4\xd6\xa9J\x06Q]\x07\xa7*]" +
	"`\xa3\x93\xeb\xbb\xf55\xfd\xc4}\xf3IU\x06\x8f\x1a" +
	"\xa2\xd5\xda\xf3l\xf2\xeb\x09\xa5\xb5\"\xc8\x0fq\xe47" +
	"\x924\xf9~\x11\xe4G8\xad\xdbB\xc2\xca\x87E\x90" +
	"wp5\xbcm\xd7#$?.\x82\xfc\x0cw\x92\xf6" +
	"\xd4.\x84\xe4gD\x90_\x10\x00\xb2\xcd\x83\xb4}\x04" +
	"\xdd\xff\x9f\x08\xf2\xdb\x02\xf8ZT\xbc\xc4\xa9\x82\x9a\x15" +
	"b\xcbM\xd9Oi\xbd\xa02\x8c\x91\xa88\x0fC\xf1" +
	"hS\x04\x1b*\x0a\xc4cA\xc5\xc0vH\xab\xb4`" +
	"MY\x88\xeb@\x8d\xe2\xbaxy<\xea#\xe3\x9c\xa2" +
	"\xaa\x11o\xa25^0k\xbc:\xd7La\xdf\x19M" +
	"9!\xe9Z\x1f\xb5\x1b|\xf0uX\xdd \xcb\xedX" +
	"\x8d\xba~\x8c\xdci{zW\x8e\x82\xce4\xc1u\xeb" +
	"\\\xd4\xb8\xce\xc5\x905\x1a\xf9\xe8xgA\xf6\xed\x9f" +
	"\xd4\x05\x9dA\xa8\x9fz\x88\xd35\xf3Lw\x8d\xc22" +
	"\xc5\x94\x16\x9c\xfc\xee0\x93\x05\xbd)\x8d\x97\x9d\xb5\xd0" +
	"v\x90#\x9f\x01\xc9\x8c\xdb\xe2\xd3\xba!\x97f\xbe\x80" +
	"\x12\xd3\x978\x1d\xa0gz\x14\x91i)!\xbd\x8c\xc4" +
	"\x8eB7.k8\x8f\xe6p\xecw\x1f\x80\xfd\xd2\x85" +
	"\xb4\xb3\xc8\xcc\xc5\x9c\x9fk\x00\xf6#\x17\xd2\xfa\xb9H" +
	"\x90\xd6\x90\xac\x81\xfd\xa6\x01\xb0+{\xd2\x0a\x92\x19," +
	"\xf3\x80\xc8.\xe5r\xd7{\x177\"ARI\xd6\xc0" +
	"n\xa4\x03\xbb\x89-\xcd\xf7#A\x92I\xd6\xc0\xee\xac" +
	"\x01\xbb\xc4'U\x909\x8b=>\xda\xebS\x02\x09\xd6" +
	"\xf2\x88Dc\x11\xfb\xef\x1c%\x82<\x11l\x94\xa4F" +
	"\x99%\x100\xcbs%\x90h\xc1\x9a\xba\xa0\xb5\"\x8a" +
	"<\x8a\x1aI\x1f\xea\xa7\xe2\x12-\x0f.\x8a\x1bn\x05" +
	"\x98\x8c/\x93\x04\x9d\xca\xac\xdd\xd9\xd2J4\xcc\x10A" +
	"\xbe\xa9[\x97I\xdcZ/\xce\xf4J\xc9\x8f\xa7\x85\xd9" +
	"\x995\x88\xfft\x17\xad\xba\x16\x1f\xbb\xb4\xfdf^\x83" +
	"-\xcb\xb0\x06\xcb\xc5\xf8\xf6/et\xf5zSr\xbf" +
	"\x04;S\xe1T\xd2\x9fi\xf3XQ\x9a\xe6\xb1\xd4\xad" +
	"t\xbd\xcf*\xa3^\x08\xcb\xaa2\xfe\x88\xf6\\0y" +
	"\x9d\xd1]4\x97\xce\xbb\x7f\xdf\x82j\xa6\xf6\xe4\x16\xae" +
	"t!\xd1\xebF\xcfO\xe6wc\xec\xfb\xf6]\xaf\xb7" +
	";Q\x0c=\xe4t\x88v\xe1\x08O%_:\xf1Y" +
	"\xc3\xe9\x8d\xf0\xd2\xcde\xbb;?\xc2\xebJ'\xaa]" +
	"\x88\xfd\xf7\xb8\xe6\xd4\xe5\xa2\x11+qw\x0b\x04\x1b2" +
	"\xeeC\xb6(\"O\x88B\xe1\x9c\x92\xed\xd7\xbd|\xce" +
	"\xb7\xcft\xb5\x04\xc5\xdc\xba\xa2F\xd2\x97\xc0;\x08." +
	"\xddb\xa5\xa9\x8a\xa1\xd0Bw\x07\x16\xd4\xa8\xc7\xbb\xe5" +
	"a\xdd\xce\xc4\xdd\xda}\xf8B\x96b\x8dD@8e" +
	"\xff\xbeG7\x9c\x86\x1d\xc5\xb8\xd5:\xaa8\x92\xba5" +
	"\xd0\xec\xa7\xec(\xa1K\xd7;\x85R\xf2p\xbf[\x1e" +
	"N\xb8\xfaK\x11\xe4\x879=\xda\xe4w\x92s\xb0\xd2" +
	"\xf0-\xe4\xd9C\"\xc8\x8f\x934\\4\xd3\xf0\xad~" +
	".a\xcf\xce2\xf3\xf0mA'aO\x85\xdbN\x1a" +
	" \x9d\xcb\xec\xf6\xaf5\x99`\x1c0o\xd9A\xbe\xf3" +
	"\xe3;\x8c\x11\xce\x8d;\xc8w~&\xab{p\x9ar" +
	"\xdd=\xd5\xb9uR\xf8\xa8\xa7F\x8cR\xd9]\x98\xa6" +
	"\xec\xc1\xfcX\x12gY\x10\xb0\x95\xa8\xc3#\"\xc8O" +
	"rU\x8f\x9d\x85\x16g_&\xec\x1ed\xb2{?\x19" +
	"\xf9\x82\x08\xf2\x1fS\x1aL\xdd\x7fC\xc0a3\x7f\x05" +
	"&/\xe5\x0aL\xf2\xdd\x97<\xf7\xbb/\xaew]\xba" +
	"\x83\x1c.WA\\\xcb\xf7+\x11\x92\xc7\x88 Oi" +
	"\x87\xcet65\xa4\x00IF\xcb\xe3a\xecr\xbf\"" +
	"\xb3\xa0\xa6\xdd\xed\xfen8\xc64\x8dl\x9d\xf7\xdf\xfb" +
	"\xbb\xd3\x7f\xdf\x8d[\x059]\xcdG\\~\x90\xa3," +
	"M\x96\xd0q\x8e\xd2\xfdE%\xd5\xb8\xdd\"\xadL|" +
	"N7\xae\xdf\xba]\xf1+J\xb3\x7f\xbb\x89\xd8\xfe\x91" +
	")\xb7\xdd\xff\xff\x00\x00\x00\xff\xffu\x82N\x94"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_f0f0f0f0f0f0f0f0,
		Nodes: []uint64{
			0x8062e5d9993dd5d4,
			0x8072dbd2a2848dd4,
			0x80e4e1b97f5a1f54,
			0x81cee22b1a1e7d87,
			0x87064f415deed0d5,
			0x885cc59ce1e5a905,
			0x887ddb0730b19143,
			0x8947cafc1ebd809a,
			0x89505def6fe6ab4a,
			0x8a10125d4721e5e2,
			0x8a8843cb76f95c84,
			0x8e43bfe28adfb079,
			0x8ec69fe34c1f5ddc,
			0x9065a50fa79ae66a,
			0x9085271579b0da7f,
			0x965f263dd17192b4,
			0x968693341c5e3414,
			0x9774b03d19576838,
			0x9876d7cef8cbb22e,
			0x98a5804a83d929ec,
			0x991b0de6024dd8cd,
			0x9a11f1e60ecce793,
			0x9a6a55793f5bf111,
			0x9aa912b9e91970a7,
			0x9cb9074973304d87,
			0x9e25bfb846fbb96b,
			0x9e9a32b9ced3c983,
			0xa0aca1b1fe27bad4,
			0xa0e00903b6015e47,
			0xa1c1b63264fe5e52,
			0xa2e5b1f3b7363bac,
			0xa3d7513b1ee72d8d,
			0xa5cd41951269ecf5,
			0xa8e8bee5b04e84ab,
			0xa95be342870edc16,
			0xa9cd7c85fa34a151,
			0xab067c2e6eb196d2,
			0xae4143b7a08e8a40,
			0xae4d9175aa1cc20e,
			0xaf10a6d5f63cf731,
			0xaf339d5a8dceeb16,
			0xaf627e6f74751664,
			0xaf7a24dafe583b5d,
			0xb3969f8a4dd322aa,
			0xb3cf94ce66e82088,
			0xb4ae3f3f7833d849,
			0xb66a7aced67df549,
			0xb68e57ffadc114ac,
			0xb739a89d7c2b759f,
			0xb91029928b753bb5,
			0xb9170183a6c59710,
			0xb934a2409078ae53,
			0xbb9cc5655915c3f6,
			0xc1c3c1c6b238c601,
			0xc202d47bf3c98768,
			0xc277ced9032b2309,
			0xc3fe6576734bb763,
			0xc4c85c8b9e15d55b,
			0xc5197ab2fdc87bb6,
			0xc9a1d4471d35c544,
			0xc9ad31ceca5c7d21,
			0xc9bdeecdc762d2bd,
			0xca1a1204ed95a334,
			0xcef392b00d0a0a94,
			0xd20678d7b8626e3b,
			0xd28f0092e54aa96e,
			0xd2e3c39d1ae7bacd,
			0xd37e4eb60913264b,
			0xd49df8f1fd0013c5,
			0xd5311a990730b7de,
			0xd5c14637a993d4e5,
			0xd77ee5c4bbd543a3,
			0xd920d409c484791d,
			0xd970bdc91397a67c,
			0xda0dd270eb7b1586,
			0xda19a5190955d91a,
			0xdb62e120e9ef1d46,
			0xdc773850ce295794,
			0xde3acf2981a4e7a7,
			0xe226b27c0aa2952c,
			0xe290eeea961b6d56,
			0xe2f011ec078b580d,
			0xe30deb15861b3094,
			0xe55856a5b9abb4d2,
			0xe5bf4d65e18b93f7,
			0xe689f1a08be48100,
			0xe8a18594747191f3,
			0xe903ce2cfb272048,
			0xe9b04ba182cfb9fb,
			0xe9e0c51862e906fe,
			0xea780248218a3049,
			0xea9a8399e73729c9,
			0xef3f5c0b14fc9394,
			0xf00ceae94eef0bf9,
			0xf01b5bc548e13e3c,
			0xf2d1bb9ad6523209,
			0xf4471116da4dc44b,
			0xf5f4e54357ac9542,
			0xf7306cd4db562f65,
			0xf7c7483d5edd7d40,
			0xf864a5c81a3f1cf1,
			0xf96844903c020a29,
			0xfa9a88a268439985,
			0xfbd72359add519db,
			0xfbf592f105013a6d,
			0xfc3f353ac3f91e97,
			0xfc471c9d3cce85aa,
			0xfd38beaf2a4cbd9e,
			0xffc46a7bfba145f8,
		},
		Compressed: true,
	})
}
